package org.infoscoop.dao.model;

// Generated 2010/03/29 15:54:59 by Hibernate Tools 3.3.0.GA

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * IsAccesslogs generated by hbm2java
 */
@Entity
@Table(name = "is_accesslogs", uniqueConstraints = @UniqueConstraint(columnNames = {
		"UID", "DATE" }))
public class Accesslog implements java.io.Serializable {

	private Integer id;
	private String uid;
	private String date;

	public Accesslog() {
	}

	public Accesslog(String uid, String date) {
		this.uid = uid;
		this.date = date;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "UID", nullable = false, length = 150)
	public String getUid() {
		return this.uid;
	}

	public void setUid(String uid) {
		this.uid = uid;
	}

	@Column(name = "DATE", nullable = false, length = 8)
	public String getDate() {
		return this.date;
	}

	public void setDate(String date) {
		this.date = date;
	}

}
