package org.infoscoop.dao.model;

// Generated 2010/03/29 15:54:59 by Hibernate Tools 3.3.0.GA

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

import org.json.JSONException;
import org.json.JSONObject;

/**
 * IsAuthcredentials generated by hbm2java
 */
@Entity
@Table(name = "is_authcredentials")
public class AuthCredential implements java.io.Serializable {
	public static final Integer LOGIN_AUTH_CREDENTIAL = new Integer(-1);
	public static final Integer COMMON_AUTH_CREDENTIAL = new Integer(0);

	private Integer id;
	private String uid;
	private int sysNum;
	private String authType;
	private String authDomain;
	private String authUid;
	private String authPasswd;

	public AuthCredential() {
	}

	public AuthCredential(String uid, int sysNum, String authType,
			String authUid) {
		this.uid = uid;
		this.sysNum = sysNum;
		this.authType = authType;
		this.authUid = authUid;
	}

	public AuthCredential(String uid, int sysNum, String authType,
			String authDomain, String authUid, String authPasswd) {
		this.uid = uid;
		this.sysNum = sysNum;
		this.authType = authType;
		this.authDomain = authDomain;
		this.authUid = authUid;
		this.authPasswd = authPasswd;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "UID", nullable = false, length = 300)
	public String getUid() {
		return this.uid;
	}

	public void setUid(String uid) {
		this.uid = uid;
	}

	@Column(name = "sysNum", nullable = false)
	public int getSysNum() {
		return this.sysNum;
	}

	public void setSysNum(int sysNum) {
		this.sysNum = sysNum;
	}

	@Column(name = "authType", nullable = false, length = 16)
	public String getAuthType() {
		return this.authType;
	}

	public void setAuthType(String authType) {
		this.authType = authType;
	}

	@Column(name = "authDomain", length = 64)
	public String getAuthDomain() {
		return this.authDomain;
	}

	public void setAuthDomain(String authDomain) {
		this.authDomain = authDomain;
	}

	@Column(name = "authUid", nullable = false, length = 300)
	public String getAuthUid() {
		return this.authUid;
	}

	public void setAuthUid(String authUid) {
		this.authUid = authUid;
	}

	@Column(name = "authPasswd", length = 512)
	public String getAuthPasswd() {
		return this.authPasswd;
	}

	public void setAuthPasswd(String authPasswd) {
		this.authPasswd = authPasswd;
	}


	public Object toJSON() throws JSONException {
		JSONObject json = new JSONObject();
		json.put("id", this.getId());
		json.put("authType", this.getAuthType());
		json.put("sysNum", this.getSysNum());
		json.put("authUid", this.getAuthUid());
		json.put("authPasswd", this.getAuthPasswd());
		if(this.getAuthDomain() != null){
			json.put("authDomain", this.getAuthDomain());
		}
		return json;
	}
}
