package org.infoscoop.dao.model;

// Generated 2010/03/29 15:54:59 by Hibernate Tools 3.3.0.GA

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * IsGadgets generated by hbm2java
 */
@Entity
@Table(name = "is_gadgets")
public class Gadget implements java.io.Serializable {
	private Integer id;
	private String type;
	private String path;
	private String name;
	private byte[] data;
	private Date lastmodified;

	public Gadget() {
	}

	public Gadget(String type, String path, String name, Date lastmodified) {
		this.type = type;
		this.path = path;
		this.name = name;
		this.lastmodified = lastmodified;
	}

	public Gadget(String type, String path, String name, byte[] data,
			Date lastmodified) {
		this.type = type;
		this.path = path;
		this.name = name;
		this.data = data;
		this.lastmodified = lastmodified;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "type", nullable = false, length = 50)
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	@Column(name = "path", nullable = false, length = 512)
	public String getPath() {
		return this.path;
	}

	public void setPath(String path) {
		this.path = path;
	}

	@Column(name = "name", nullable = false)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "data")
	public byte[] getData() {
		return this.data;
	}

	public void setData(byte[] data) {
		this.data = data;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "lastmodified", nullable = false, length = 19)
	public Date getLastmodified() {
		return this.lastmodified;
	}

	public void setLastmodified(Date lastmodified) {
		this.lastmodified = lastmodified;
	}

}
