package org.infoscoop.dao.model;

// Generated 2010/03/29 15:54:59 by Hibernate Tools 3.3.0.GA

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * IsHolidays generated by hbm2java
 */
@Entity
@Table(name = "is_holidays", uniqueConstraints = @UniqueConstraint(columnNames = {
		"country", "lang" }))
public class Holiday implements java.io.Serializable {

	private Integer id;
	private String country;
	private String lang;
	private String data;
	private Date updatedAt;

	public Holiday() {
	}

	public Holiday(String country, String lang, Date updatedAt) {
		this.country = country;
		this.lang = lang;
		this.updatedAt = updatedAt;
	}

	public Holiday(String country, String lang, String data, Date updatedAt) {
		this.country = country;
		this.lang = lang;
		this.data = data;
		this.updatedAt = updatedAt;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "country", nullable = false, length = 5)
	public String getCountry() {
		return this.country;
	}

	public void setCountry(String country) {
		this.country = country;
	}

	@Column(name = "lang", nullable = false, length = 5)
	public String getLang() {
		return this.lang;
	}

	public void setLang(String lang) {
		this.lang = lang;
	}

	@Column(name = "data", length = 65535)
	public String getData() {
		return this.data;
	}

	public void setData(String data) {
		this.data = data;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated_at", nullable = false, length = 19)
	public Date getUpdatedAt() {
		return this.updatedAt;
	}

	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}

}
