package org.infoscoop.dao.model;

// Generated 2010/03/29 15:54:59 by Hibernate Tools 3.3.0.GA

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * IsI18nlocales generated by hbm2java
 */
@Entity
@Table(name = "is_i18nlocales", uniqueConstraints = @UniqueConstraint(columnNames = {
		"type", "country", "lang" }))
public class I18nlocale implements java.io.Serializable {

	private Integer id;
	private String type;
	private String country;
	private String lang;

	public I18nlocale() {
	}

	public I18nlocale(String type, String country, String lang) {
		this.type = type;
		this.country = country;
		this.lang = lang;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "type", nullable = false, length = 32)
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	@Column(name = "country", nullable = false, length = 5)
	public String getCountry() {
		return this.country;
	}

	public void setCountry(String country) {
		this.country = country;
	}

	@Column(name = "lang", nullable = false, length = 5)
	public String getLang() {
		return this.lang;
	}

	public void setLang(String lang) {
		this.lang = lang;
	}

}
