package org.infoscoop.dao.model;

// Generated 2010/03/29 15:54:59 by Hibernate Tools 3.3.0.GA

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * IsMenucaches generated by hbm2java
 */
@Entity
@Table(name = "is_menucaches", uniqueConstraints = @UniqueConstraint(columnNames = {
		"UID", "url_key" }))
public class MenuCache implements java.io.Serializable {

	private Integer id;
	private String uid;
	private String urlKey;
	private byte[] menuIds;

	public MenuCache() {
	}

	public MenuCache(String uid, String urlKey) {
		this.uid = uid;
		this.urlKey = urlKey;
	}

	public MenuCache(String uid, String urlKey, byte[] menuIds) {
		this.uid = uid;
		this.urlKey = urlKey;
		this.menuIds = menuIds;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "UID", nullable = false, length = 150)
	public String getUid() {
		return this.uid;
	}

	public void setUid(String uid) {
		this.uid = uid;
	}

	@Column(name = "url_key", nullable = false, length = 128)
	public String getUrlKey() {
		return this.urlKey;
	}

	public void setUrlKey(String urlKey) {
		this.urlKey = urlKey;
	}

	@Column(name = "menuIds")
	public byte[] getMenuIds() {
		return this.menuIds;
	}

	public void setMenuIds(byte[] menuIds) {
		this.menuIds = menuIds;
	}

}
