package org.infoscoop.dao.model;

// Generated 2010/03/29 15:54:59 by Hibernate Tools 3.3.0.GA

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Transient;
import javax.persistence.UniqueConstraint;

import org.infoscoop.util.XmlUtil;
import org.w3c.dom.Document;
import org.w3c.dom.Element;
import org.xml.sax.SAXException;

/**
 * IsMenus generated by hbm2java
 */
@Entity
@Table(name = "is_menus", uniqueConstraints = @UniqueConstraint(columnNames = "type"))
public class Menu implements java.io.Serializable {

	private Integer id;
	private String type;
	private String data;

	public Menu() {
	}

	public Menu(String type, String data) {
		this.type = type;
		this.data = data;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "type", unique = true, nullable = false, length = 150)
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	@Column(name = "data", nullable = false, length = 65535)
	public String getData() {
		return this.data;
	}

	public void setData(String data) {
		this.data = data;
	}

	
	@Transient
	public Element getElement() throws SAXException {
		Document doc = (Document) XmlUtil.string2Dom(getData());
		return doc.getDocumentElement();
	}

	public void setElement(Element conf) {
		setData(XmlUtil.dom2String(conf));
	}
}
