package org.infoscoop.dao.model;

// Generated 2010/03/29 15:54:59 by Hibernate Tools 3.3.0.GA

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Transient;
import javax.persistence.UniqueConstraint;
import javax.xml.parsers.DocumentBuilder;
import javax.xml.parsers.DocumentBuilderFactory;
import javax.xml.parsers.FactoryConfigurationError;
import javax.xml.parsers.ParserConfigurationException;

import org.infoscoop.util.XmlUtil;
import org.w3c.dom.Document;
import org.w3c.dom.Element;
import org.xml.sax.SAXException;

/**
 * IsPreferences generated by hbm2java
 */
@Entity
@Table(name = "is_preferences", uniqueConstraints = @UniqueConstraint(columnNames = "UID"))
public class Preference implements java.io.Serializable {

	private Integer id;
	private String uid;
	private String data;

	public Preference() {
	}

	public Preference(String uid, String data) {
		this.uid = uid;
		this.data = data;
	}

	public Preference(String uid) {
		this.uid = uid;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "UID", unique = true, nullable = false, length = 150)
	public String getUid() {
		return this.uid;
	}

	public void setUid(String uid) {
		this.uid = uid;
	}

	@Column(name = "data", nullable = false, length = 65535)
	public String getData() {
		return this.data;
	}

	public void setData(String data) {
		this.data = data;
	}

	@Transient
	public Element getElement() throws SAXException {
		Document doc = (Document) XmlUtil.string2Dom(getData());
		return doc.getDocumentElement();
	}

	public void setElement(Element conf) {
		setData(XmlUtil.dom2String(conf));
	}

	public static Element newElement(String uid) throws ParserConfigurationException, FactoryConfigurationError{
		DocumentBuilder docb = DocumentBuilderFactory.newInstance().newDocumentBuilder();
		Document doc = docb.newDocument();
		Element newEl = doc.createElement("preference");
		newEl.setAttribute("uid", uid);
		doc.appendChild(newEl);
		return doc.getDocumentElement();
	}
}
