package org.infoscoop.dao.model;

// Generated 2010/03/29 15:54:59 by Hibernate Tools 3.3.0.GA

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * IsProperties generated by hbm2java
 */
@Entity
@Table(name = "is_properties", uniqueConstraints = @UniqueConstraint(columnNames = "name"))
public class Property implements java.io.Serializable {

	private Integer id;
	private String name;
	private String category;
	private int advanced;
	private String value;
	private String datatype;
	private String enumValue;
	private int required;
	private String regex;
	private String regexMsg;

	public Property() {
	}

	public Property(String name, int advanced, int required) {
		this.name = name;
		this.advanced = advanced;
		this.required = required;
	}

	public Property(String name, String category, int advanced,
			String value, String datatype, String enumValue, int required,
			String regex, String regexMsg) {
		this.name = name;
		this.category = category;
		this.advanced = advanced;
		this.value = value;
		this.datatype = datatype;
		this.enumValue = enumValue;
		this.required = required;
		this.regex = regex;
		this.regexMsg = regexMsg;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "name", unique = true, nullable = false)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "category", length = 128)
	public String getCategory() {
		return this.category;
	}

	public void setCategory(String category) {
		this.category = category;
	}

	@Column(name = "advanced", nullable = false)
	public int getAdvanced() {
		return this.advanced;
	}

	public void setAdvanced(int advanced) {
		this.advanced = advanced;
	}

	@Column(name = "value", length = 1024)
	public String getValue() {
		return this.value;
	}

	public void setValue(String value) {
		this.value = value;
	}

	@Column(name = "datatype", length = 128)
	public String getDatatype() {
		return this.datatype;
	}

	public void setDatatype(String datatype) {
		this.datatype = datatype;
	}

	@Column(name = "enumValue", length = 1024)
	public String getEnumValue() {
		return this.enumValue;
	}

	public void setEnumValue(String enumValue) {
		this.enumValue = enumValue;
	}

	@Column(name = "required", nullable = false)
	public int getRequired() {
		return this.required;
	}

	public void setRequired(int required) {
		this.required = required;
	}

	@Column(name = "regex", length = 1024)
	public String getRegex() {
		return this.regex;
	}

	public void setRegex(String regex) {
		this.regex = regex;
	}

	@Column(name = "regexMsg", length = 1024)
	public String getRegexMsg() {
		return this.regexMsg;
	}

	public void setRegexMsg(String regexMsg) {
		this.regexMsg = regexMsg;
	}

}
