package org.infoscoop.dao.model;

// Generated 2010/03/29 15:54:59 by Hibernate Tools 3.3.0.GA

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * IsProxyconfsId generated by hbm2java
 */
@Embeddable
public class ProxyconfId implements java.io.Serializable {

	private int temp;
	private String data;
	private Date lastmodified;

	public ProxyconfId() {
	}

	public ProxyconfId(int temp, String data, Date lastmodified) {
		this.temp = temp;
		this.data = data;
		this.lastmodified = lastmodified;
	}

	@Column(name = "temp", nullable = false)
	public int getTemp() {
		return this.temp;
	}

	public void setTemp(int temp) {
		this.temp = temp;
	}

	@Column(name = "data", nullable = false, length = 65535)
	public String getData() {
		return this.data;
	}

	public void setData(String data) {
		this.data = data;
	}

	@Column(name = "lastmodified", nullable = false, length = 19)
	public Date getLastmodified() {
		return this.lastmodified;
	}

	public void setLastmodified(Date lastmodified) {
		this.lastmodified = lastmodified;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ProxyconfId))
			return false;
		ProxyconfId castOther = (ProxyconfId) other;

		return (this.getTemp() == castOther.getTemp())
				&& ((this.getData() == castOther.getData()) || (this.getData() != null
						&& castOther.getData() != null && this.getData()
						.equals(castOther.getData())))
				&& ((this.getLastmodified() == castOther.getLastmodified()) || (this
						.getLastmodified() != null
						&& castOther.getLastmodified() != null && this
						.getLastmodified().equals(castOther.getLastmodified())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getTemp();
		result = 37 * result
				+ (getData() == null ? 0 : this.getData().hashCode());
		result = 37
				* result
				+ (getLastmodified() == null ? 0 : this.getLastmodified()
						.hashCode());
		return result;
	}

}
