var IS_R = {
	"lb_langNL": "Dutch",
	"ms_userSearchonException": "The exception occured during user search.",
	"lb_1monthAgo": "One month ago",
	"lb_countryUK": "United Kingdom",
	"ms_menuLoadOnUnSuccess": "Failed to load menu. {0} -- {1}",
	"lb_countrySE": "Sweden",
	"lb_newGroup": "New group",
	"ms_menuadded": "Menu [{0}] is added.",
	"lb_weekdaySun": "Sun",
	"lb_openSiteMap": "Open the side menu tab",
	"ms_propertyNotFound": "Property not found.",
	"ms_mergeCategoryError404": "{0} : No information to display found.",
	"ms_menuNotFound2": "Cannot find the menu \"{0}\".",
	"ms_invalidURL": "The URL is not valid.",
	"lb_gathering": "Combine",
	"lb_webSiteColon": "Web Site:",
	"lb_all": "ALL",
	"ms_dragNoMerge": "RSS Gadget is not merged while pressing the CTRL key.",
	"lb_add": "Add",
	"lb_countryMX": "Mexico",
	"ms_closeMySiteMap": "Close the my site map tab",
	"lb_refresh": "Refresh",
	"ms_validateError": "Failed in the process of validation. {0}",
	"ms_getdatafailed": "Failed to load the information to display. This system is not available temporarily.",
	"ms_trashContextExplanation": "Delete/Restore can be done by right-clicking.",
	"ms_thisIsFixedTab": "This tab is fixed. So you cannot custimze this.",
	"ms_invalidDateFormat": "Invalid date format specified.",
	"lb_countryUS": "United States",
	"lb_langPtBR": "Portuguese",
	"ms_mergeConfirm": "Are you sure you want to merge {1} with {0}?",
	"ms_confirmDeleteUser": "Are you sure to delete the user?",
	"lb_toTopPage": "TopPage",
	"lb_countryNZ": "New Zealand",
	"lb_selectWallPaperImage": "Please select the image for wall paper.",
	"lb_default": "Default",
	"lb_invalidate": "Disable",
	"lb_setupAll": "Global settings",
	"lb_doNotMerge": "Do not merge ( return it )",
	"lb_noInfo": "No information to display.",
	"lb_dropAll": "Drop all",
	"ms_commandonException": "Command action failed. {0}",
	"ms_iCalNoPermission": "No permission to load calendar {0}.",
	"ms_deletaTabFailed": "Failed to delete tab \"{0}\".",
	"lb_displayAll": "Show all",
	"lb_reset": "reset",
	"lb_date": "Date",
	"ms_requiredItem": "is required item.",
	"lb_langES": "Spanish",
	"lb_today": "Today",
	"lb_warn": "Warning",
	"ms_inputTooLong": "The input string is too long. The length is up to {0} characters.",
	"lb_search": "Search",
	"lb_addTabLink": ">> Add a tab",
	"lb_searchConditionNotSet": "Search condition is not set.",
	"ms_mergeCategoryError10550": "{0} : Information cannot be parsed.",
	"lb_debug": "Debug",
	"ms_failedLoadIcons": "Failed to load gadget icons.",
	"lb_langKO": "Korean",
	"ms_customizeSavingFailure1": "Failed to save the customized information. {0}",
	"lb_freshdaysTerm": "Period of displaying new-arrival icon",
	"ms_targetGroupNotFound": "*There is no group to add users. Please create a group.",
	"lb_close": "Close",
	"ms_gatheringWidgets": "Combine these gadgets?",
	"lb_setting": "Edit",
	"lb_changeColnumFailure": "Failed to change the column. column={0}, msg=[{1}]",
	"lb_doMerge": "Merge",
	"lb_userSearchNoResult": "No results matching your search were found.",
	"lb_added": "Added",
	"lb_initialize": "Initialization",
	"ms_cacheDeleteFailure": "Failed to delete cache memory. {0} -- {1}",
	"lb_langIT": "Italian",
	"lb_credentialList": "Credential List",
	"lb_displayRSS": "Show RSS",
	"lb_weekdayTue": "Tue",
	"ms_previewMenuPath": "Belonging menu.",
	"ms_loadTimeout": "Request timeout occurred while loading.",
	"lb_descLink": "Detail>>",
	"ms_showTabByClick": "This tab is displayed when clicking.",
	"ms_cannotDeleteLastTab": "You must have one tab at least.",
	"ms_deleteTabConfirm": "Are you sure to delete \"{0}\" ?",
	"lb_showAllLatestItems": "Display all of new arrivals.",
	"ms_loadCancel": "Canceling the loading because of current loading. {0}",
	"lb_countryDE": "Germany",
	"ms_sessionTimeoutReLogin": "Session closed. Please login again.",
	"ms_gtOneNum": "Enter a correct number of more than 1.",
	"lb_langJA": "Japanese",
	"lb_title": "Title",
	"lb_countryCA": "Canada",
	"lb_3DaysAgo": "Three days ago",
	"ms_requiredItem2": "It is required item.",
	"lb_countryAU": "Australia",
	"lb_ref": "Reference",
	"ms_multiRssReaderDeleteSubcategory": "Category \"{1}\" of MultiRssReader \"{0}\" is deleted.",
	"ms_infoNotFoundAt": "{0} Cannot find information to display at \"{1}\".",
	"ms_invalidRegexp": "Invalid regexp specified.",
	"ms_inputTooLong2": "The input string is too long. The length is up to {0} characters in the alphanumeric character.\nWhen a multi byte character is included, the multi byte character is counted as about 3 characters.",
	"ms_urlGetInfoException1": "Failed to get information. Make sure that typed URL is correct. {0} -- {1}",
	"lb_noDiplayItem": "There is no information to display.",
	"lb_gadget": "Gadget",
	"ms_changeToFixedTab": "The tab '{0}' was changed to fixed tab. All gadgets in the personalized area were put into the trash box.",
	"ms_staticTabIsChanged": "The tab'{0}' was updated.",
	"ms_showWidgetByClick": "This gadget is displayed when clicking.",
	"lb_countryIE": "Ireland",
	"ms_inputCredential": "Please input Credential.",
	"ms_widgetonExceptionAt": "{0}An error occurred at \"{1}\". {2} -- {3}",
	"lb_weekdayFri": "Fri",
	"lb_langZH": "Chinese",
	"lb_messageClose": "Close messages",
	"lb_countryCH": "Switzerland",
	"ms_menuNotFound": "Cannot find the menu.",
	"lb_generalSetting": "General settings",
	"lb_closeAll": "Close all",
	"ms_iCalLoadFailed": "Failed to load calendar. {0} : {1} -- {2}",
	"lb_clearConfigurationDesc1": "The portal screen is returned to default display.",
	"lb_refreshKey": "Refresh(R)",
	"ms_authFailure": "Authentication failed. Please input a valid user ID and password.",
	"ms_classNotFounf": "Cannot find the class {0}.",
	"lb_addContentsExGadget": "http://www.infoscoop.org/gadgets/hello.xml",
	"ms_stopRefresh": "The update is canceled.",
	"lb_logout": "Logout",
	"lb_mergeView": "Merge Display",
	"lb_countryDK": "Denmark",
	"lb_makeEffective": "enable",
	"lb_sendMail": "Send mail",
	"lb_creator": "Author",
	"lb_notGathering": "Separate",
	"lb_rssViewSetting": "RSS display settings",
	"lb_noNewInfo": "No new arrivals.",
	"lb_preview": "Preview",
	"lb_notfound": "Cannot find information to display.",
	"ms_commandonFailure": "Command action failed. {0} -- {1}",
	"ms_userSearchComplete": "Acquired the result of user search.",
	"lb_noDisplayFrameBorder": "No display frame border:",
	"ms_containerLoadon404": "Error 404: location \"{0} /widsrv \" is not found.",
	"lb_clearConfigurationButton": "Initialization of customized information",
	"ms_infosccopInitializing": "Now infoScoop is initializing.",
	"lb_notConfirm": "No further confirmation.",
	"lb_newBox": "New BOX",
	"lb_any": "{0}",
	"ms_pleaseTurnbackAndSetAuthInfo": "To read articles, turn back to normal size gadget and registor User ID and Password.",
	"ms_widgetBuildError": "An error occurred while creating a gadget.",
	"ms_updatePasswordError": "Failed to upadating password.",
	"lb_resetColumnWidth": "Reset Column Width",
	"ms_sessionTimeout": "Session closed by unexpected reasons. Please login again.",
	"lb_maximizeSendMail": "{0} %0D%0A%0D%0A {1}",
	"ms_invalidIconType": "Invalid icon type is used at the header icon. {0}[type={1}",
	"lb_langDE": "German",
	"lb_resizeFontSmaller": "Smaller font size",
	"lb_getCustomInfoonFailure2": "Failed to get information of screen customization. Please try later.",
	"ms_loadtimeoutAt": "Request timeout occurred while loading {0} \"{1}\" .",
	"lb_yesterday": "Yesterday",
	"ms_menuLoadonFailure": "Failed to load menu.",
	"lb_langFR": "French",
	"ms_mergeCategoryError": "{0} : An error occurred.",
	"lb_langDA": "Danish",
	"ms_iframeForbiddenURL": "Displaying the web site of {0} in portal innerframe is forbidden by administrator. It is displayed in a new window.",
	"lb_itemCount": "Total Articles: {0}",
	"ms_invalidFormat": "Please specify a valid format.",
	"ms_iCalParseFailed": "Failed to analyse calendar. {0} : {1}",
	"ms_urlEncodingonException": "Failed in the process of URL encording. {0} -- {1} : {2}({3})",
	"lb_setupUnfinished": "A gadget is not displayed unless all of the required settings are done.",
	"lb_countryIN": "India",
	"lb_rename": "Rename",
	"lb_widgetDesignSetting": "Gadget Design Setting",
	"lb_new": "New!!",
	"lb_type": "Type",
	"lb_topMenu": "TopMenu",
	"ms_rssreaderUnreadable": "Unable to load settings of RssReader.",
	"lb_changeApply": "Apply changes",
	"ms_forbiddenURL": "The website of the input URL is forbidden by administrator.",
	"lb_bracketTrashEmptyAll": "[Empty the trash box]",
	"ms_changeTabFailed": "Failed to change tab. {0}",
	"ms_doubleEntryFailure": "{0} is canceled because of the failure in second try.",
	"lb_userSearch": "User search",
	"lb_countryIT": "Italy",
	"ms_logofftimeSavingfailure": "Logoff process failed. {0}",
	"lb_addContentsExWebSite": "http://www.infoscoop.org/index.php",
	"ms_widgetBkgcolorError": "{0}An error occurred at \"{1}\".Failed to set up the back-ground-color.",
	"lb_userNotAddedGroup": "No user is added to this group.",
	"lb_langEN": "English",
	"lb_urlExample": "Example of input URL",
	"ms_gtZeroNum": "Enter a correct number of more than 0.",
	"lb_notitle": "No title",
	"ms_urlNoInput": "Please enter URL.",
	"ms_urlTooLong": "URL is too long. The length of URL is up to 2000 characters in the alphanumeric character.\nWhen the multi byte character is included, the multi byte character is counted as about 9 characters.",
	"ms_noPermissionAt": "{0}You do not have permission to access the \"{1}\".",
	"lb_searchCondition": "Set search condition",
	"ms_menuLoadon10408": "Request timeout occurred while loading Menu.",
	"ms_clearConfigurationFailed": "Failed in the initialization of customized information.",
	"lb_widget": "Gadget",
	"lb_1weekAgo": "One week ago",
	"lb_addContentsExRSS": "http://www.infoscoop.org/index.php/en/news.feed",
	"lb_wallPaperSetting": "Wall Paper Setting",
	"lb_addUser": "Add User",
	"lb_openMySiteMap": "Open the my site map tab",
	"lb_containerLoadonException": "Failed to compose screen. : {0}",
	"ms_errorSetAuthInfo": "Failed to authenticate User ID or Password you entered. The User ID and Password were not updated.",
	"ms_lastlogoutSavingfailure": "Customized information at the last logout is not saved.",
	"ms_inputURL": "Please enter URL.",
	"lb_closeAddContents": "Close add contents tab",
	"ms_minimizeFailure": "Failed in minimizing process of {0}.: {1}",
	"lb_illegalToolbarItem": "It is an invalid toolbar item. Uncertain type [{0}]",
	"lb_editGroup": "Group edit",
	"lb_error": "Error",
	"lb_sendMailTitle": "%81u{0}%81v%82%CC%82%B2%8F%D0%89%EE",
	"lb_containerLoginonException": "Failed to compose screen. There might be some errors occurred at the customized information data. Contact the systems manager.",
	"ms_userIdEmpty": "Please enter User ID.",
	"lb_countryES": "Spain",
	"lb_langNO": "Norwegian",
	"ms_iCalCreateFailed": "Failed to create calendar. {0}",
	"ms_datecreatorChangeFailed": "Failed to change the Show/Hide setting of Date/Author of {0}: {1}",
	"lb_delete": "Delete",
	"ms_lineChangeFailure": "Changing the paragraph setting of {0} failed.: {1}",
	"lb_turnbackMaximize": "Back",
	"lb_prev": "Previous",
	"ms_confirmDeleteGroup": "Are you sure to delete the group?",
	"lb_noInfoOnMaximize": "There is no information that can be displayed by maximization.",
	"lb_trashBox": "Trash Box",
	"lb_authType": "Authentication Type",
	"ms_widgetDuplicateWarn": "The gadget cannot be added because the same gadget already exists. ({0})",
	"lb_mail": "Mail",
	"lb_deployAll": "Open all",
	"lb_widgetTitle": "Gadget title",
	"lb_selectWidgetHeaderImage": "Please select the image for background of gadget header.",
	"ms_failedCheckCharLength": "Failed to check the length of input strings.",
	"ms_invalidCharset": "Invalid character set specified.",
	"lb_countryNO": "Norway",
	"lb_saveFilterSetting": "Filter conditions except for [Date] are to be saved as setting of RSS reader.",
	"ms_getdataerror404": "Error 404: location {0} is not found.",
	"lb_countryFR": "France",
	"lb_select": "Select",
	"lb_weekdaySat": "Sat",
	"lb_openMenu": "Show Menu",
	"lb_doubleAdd": "The selected gadget is already added.",
	"lb_messageConsole": "Message Console",
	"ms_emptyAt": "Need to input into {0}.",
	"ms_mergeCategoryError10408": "{0} : Request timeout occurred while loading.",
	"lb_adminLink": "To Management Page",
	"lb_countryCN": "China",
	"lb_getCustomInfoon404": "Failed to get the information of screen customization. The settings of the server is not correct. Contact the Systems Manager.",
	"ms_invalidWidget": "This gadget is not available for now.",
	"lb_category": "Category",
	"lb_deleteDate": "Deleted date",
	"lb_langFI": "Finnish",
	"ms_configNotFound": "The conposed file of {0} does not exist.",
	"lb_edit": "Edit",
	"lb_closeSitemap": "Close the side menu tab",
	"lb_minimize": "Minimize",
	"ms_trashLoadonFailure": "Failed to get Trash Bin information. {0} -- {1}",
	"lb_mergeConfirmDialog": "Gadget merge confirmation dialog",
	"lb_scheduleMonthFormat": "yyyy/M",
	"lb_weekdayThu": "Thu",
	"ms_revertWidget": "It is added to tab \"{0}\". It returns when clicking.",
	"lb_gadgetColon": "Gadget:",
	"ms_cannotAddGadgetToThisTab": "You cannot add any gadgets to this tab.",
	"lb_rssColon": "RSS:",
	"lb_deleteUser": "Delete User",
	"lb_enableRoundCorner": "Round a corner of gadgets:",
	"ms_menuIconException": "An error occurred at icon display settings in menu \"{0}\".:{1}",
	"lb_countryJP": "Japan",
	"ms_errorOnWindowResize": "An error occurred during resizing window.: {0}",
	"lb_weekdayMon": "Mon",
	"lb_resizeFontLarger": "Larger font size",
	"ms_clearConfigurationForceReload": "Going to reload as customized information was initialized.",
	"lb_langSV": "Swedish",
	"ms_mergeCategoryError403": "{0} : You do not have permission to access the site.",
	"lb_addGroup": "Add a Group",
	"ms_iCalLoadTimeout": "Request timeout occurred while loading Calendar. {0}",
	"lb_changeNotApply": "Not change",
	"ms_menuLoadonException": "Failed to load menu. {0}",
	"lb_countryKR": "Korea",
	"lb_openAddContents": "Open the add contents tab",
	"ms_addCheckedUser": "*Add checked User(s) to [{0}].",
	"msg_title": "Message Console",
	"lb_closeLink": "Close<<",
	"lb_initTab": "Initialize tab content",
	"lb_weekdayWed": "Wed",
	"ms_overMaxIntValue": "The input value exceeds the maximum. Max value is 2147483647.",
	"lb_countryFI": "Finland",
	"lb_maximize": "Maximize",
	"lb_setAuth": "Authentication Setting",
	"lb_turnback": "Restore",
	"ms_passwordResetConfirm": "The password authentication failed at the URL below. Do you really want to set the password?",
	"lb_getCustomInfoonFailure1": "Failed to get information of screen customization.: {0} -- {1}",
	"lb_bracketClose": "[Close]",
	"lb_userID": "User ID",
	"lb_password": "Password",
	"ms_inputOverMaxValue": "The input value is too large. Set the value lower than {0}.",
	"ms_urlEncodingFailed": "Failed in the process of URL encording. {0} : {1}({2})",
	"lb_reload": "Refresh",
	"lb_filterDescSettingLink": "Filter setting >>",
	"ms_gtZeroOrAuto": "Please enter \"auto\" or numerical value more than 0.",
	"lb_countryRU": "Russia",
	"ms_trashonException": "Failed to get Trash Bin information. {0}",
	"lb_deploy": "Expand",
	"lb_widgetEditHelp": "Help",
	"lb_businessDate": "Buisiness date",
	"ms_needsAuthentication": "Please register authentication information to maximize gadget.",
	"lb_clearConfigurationDesc2": "When customized information is initialized, all of added gadgets and tabs are deleted.",
	"lb_widgetTitle_empty": "Please specify the gadget title.",
	"lb_selectSubWidgetHeaderImage": "Please select the background color of sub gadget header.",
	"lb_countryNL": "Netherlands",
	"lb_newTab": "new tab",
	"ms_getdatafailure": "Error {0} -- {1}",
	"ms_clearTabConfigurationConfirm": "Are you sure to delete all of added gadgets?\n (The deleted gadgets goes into trash bin).",
	"lb_canBeAddContents": "Widgets that can be added",
	"lb_dateFilterInfo": "Entry for {0}",
	"ms_customizeWidthByDrag": "Drag to control width.",
	"lb_cancel": "Cancel",
	"lb_info": "Information",
	"lb_countryBR": "Brazil",
	"lb_messageMore": "Show more messages",
	"ms_autoReloadCancel": "Auto reload is canceled because of being in loading process. Cancled the auto reload because of loading.{0}",
	"lb_addContents": "Add a gadget",
	"lb_change": "change",
	"lb_resizeFontNormal": "Medium font size",
	"lb_authInfo": "Credential",
	"lb_langRU": "Russian",
	"ms_propertyLoadonFailure": "Failed to load properties.",
	"ms_noPermission": "You do not have permission to access the site.",
	"lb_urlList": "URL list",
	"lb_belong": "Division",
	"ms_widgetonFailureAt": "{0}An error occurred at \"{1}\". {2}",
	"lb_entry": "Submit",
	"lb_name": "Name",
	"lb_siteMap": "SiteMap",
	"lb_previewError": "The preview cannot be displayed",
	"lb_refreshMenu": "Update menu",
	"ms_custmizeFailedReload": "Failed to save the customized information. This browser will be reloaded.",
	"ms_timeOut": "A timeout occurred",
	"ms_noURL": "No URL to link to.",
	"ms_clearConfigurationConfirm": "Are you sure to delete all of added gadgets and tabs?\n (The deleted gadgets goes into trash bin).",
	"lb_changeColumn": "Change the number of Columns",
	"lb_notAvailable": "Not available"
}
