var IS_R = {
	"ms_urlEncodeonExceptionAt": "{0}でURLエンコーディング処理に失敗しました。 {1} : {2}({3})",
	"lb_searchConfigOn10408": "検索設定ファイルの読み込みがタイムアウトしました。",
	"lb_searchResultsOnNewWindow": "検索結果を新しいウィンドウで表示",
	"lb_langNL": "オランダ語",
	"ms_userSearchonException": "ユーザ検索で例外が発生しました。",
	"lb_1monthAgo": "一ヶ月前",
	"lb_countryUK": "イギリス",
	"ms_menuLoadOnUnSuccess": "メニューの読み込みに失敗しました。 {0} -- {1}",
	"lb_countrySE": "スウェーデン",
	"lb_summaryAllView": "サマリー表示/全文表示",
	"lb_newGroup": "新しいグループ",
	"ms_menuadded": "メニュー[{0}]が追加されました。",
	"lb_weekdaySun": "日",
	"lb_dateDisplay": "詳細日時表示/非表示",
	"lb_openSiteMap": "サイドメニューを開きます",
	"ms_propertyNotFound": "プロパティが見つかりません。",
	"ms_mergeCategoryError404": "{0} : 表示する情報が見つかりませんでした。",
	"ms_atompubPostonFauilure": "「{0}」でエラーが発生しました。\n{1} -- {2}\n{3}",
	"lb_titleEdit": "タイトル編集",
	"ms_menuNotFound2": "メニュー「{0}」が見つかりません。",
	"lb_nextPage": "次のページ",
	"lb_pageNum": "ページ{0}",
	"ms_authServiceAccessFailed": "認証サービスに対して正常にアクセス出来ませんでした。システム管理者にお問い合わせください。",
	"ms_noInputComment": "コメントを記入してください",
	"lb_otherLayout": "画面その他",
	"lb_sentMessageOfArticle": "この記事についてのメッセージを送る",
	"ms_customizeSavingonException": "カスタマイズ情報の保存に失敗しました。 {0}",
	"ms_invalidURL": "有効なＵＲＬではありません",
	"ms_notCoverage": "は検索対象外です。",
	"lb_gathering": "まとめる",
	"lb_webSiteColon": "Webサイト:",
	"lb_readingtimeout": "表示する情報の読み込みがタイムアウトしました。この機能は一時的にご利用できません。",
	"lb_all": "全て",
	"lb_shortcutsKeyList": "ショートカットキー 一覧",
	"ms_dragNoMerge": "Ctrlキー押下中はRSSガジェット同士のマージを行いません。",
	"ms_gadgetFuncNotFound": "ガジェット「{0}」に「{1}」という関数は存在しません。",
	"lb_add": "追加",
	"lb_countryMX": "メキシコ",
	"ms_closeMySiteMap": "マイサイトマップを閉じます",
	"lb_incomingMessage": "受信メッセージ",
	"ms_selectSearchSite": "検索対象サイトを少なくとも1つ選択してください。",
	"lb_messageOf": "{0} のメッセージ",
	"lb_siteCategory": "サイト別",
	"lb_refresh": "更新",
	"ms_reportfailure1": "障害報告処理に失敗しました。 {0} -- {1} : {2}({3})",
	"ms_validateError": "バリデーションチェックに失敗しました。{0}",
	"ms_getdatafailed": "データが取得できませんでした。",
	"lb_maximizeShortcutsitemAndSummary": "(アイテム選択時 &amp; サマリー表示時)",
	"lb_previewScreen": "画面を確認する",
	"ms_invalidRssType": "処理できないRSS形式です: {0}",
	"ms_trashContextExplanation": "右クリックで[元に戻す]/[削除]ができます。",
	"ms_thisIsFixedTab": "このタブは固定タブです。カスタマイズできません。",
	"ms_invalidDateFormat": "不正な日付フォーマットです。",
	"lb_countryUS": "アメリカ",
	"lb_langPtBR": "ポルトガル語",
	"ms_mergeConfirm": "「{0}」に「{1}」をマージしますか？",
	"ms_searchEngineLoadon10408": "検索サイト「{0}」へのリクエストがタイムアウトしました。",
	"ms_up_update_from_default_by_admin": "管理者によって、「{0}」ガジェットのユーザ設定「{1}」の値が初期値から「{2}」変更されました。",
	"ms_confirmDeleteUser": "ユーザを削除します、よろしいですか？",
	"lb_toTopPage": "トップページへ",
	"lb_countryNZ": "ニュージーランド",
	"lb_searchForm": "検索フォーム",
	"lb_erroronWidgetMove": "ガジェット「{0}」の移動処理でエラーが発生しました",
	"lb_fullDisplay": "全文表示",
	"lb_selectWallPaperImage": "壁紙に設定する画像を以下から選択してください。",
	"lb_familyName": "姓",
	"lb_default": "デフォルト",
	"lb_invalidate": "無効にする",
	"lb_setupAll": "全体設定",
	"lb_doNotMerge": "マージしない（戻す）",
	"lb_noInfo": "表示可能な情報はありません。",
	"ms_up_update_by_admin": "管理者によって、「{0}」ガジェットのユーザ設定「{1}」の値が「{2}」から「{3}」に変更されました。",
	"lb_dropAll": "まとめてドロップ",
	"ms_commandonException": "コマンドの実行に失敗しました。 {0}",
	"lb_selectSearchSite": "検索サイト選択",
	"ms_iCalNoPermission": "カレンダー「{0}」の読み込み権限がありません。",
	"ms_deletaTabFailed": "タブ「{0}」の削除に失敗しました。",
	"lb_comment": "コメント",
	"lb_displayAll": "全て表示",
	"lb_reset": "リセット",
	"lb_date": "日付",
	"ms_requiredItem": "は必須項目です",
	"lb_langES": "スペイン語",
	"lb_today": "今日",
	"lb_warn": "警告",
	"ms_inputTooLong": "入力文字列が長すぎます。{0}文字以下にしてください。",
	"lb_search": "検索",
	"lb_addTabLink": ">>タブを追加する",
	"lb_searchConditionNotSet": "検索条件が設定されていません。",
	"ms_mergeCategoryError10550": "{0} : 情報が解析できません。",
	"lb_minute": "分",
	"lb_debug": "デバッグ",
	"ms_failedLoadIcons": "ガジェットアイコンの読み込みに失敗しました。",
	"lb_langKO": "韓国語",
	"ms_customizeSavingFailure1": "カスタマイズ情報の保存に失敗しました。{0}",
	"lb_sendBroadcastMsg": "全ユーザにお知らせを送る",
	"ms_urlEncodingUnsuccess": "URLエンコーディング処理に失敗しました。 {0} : ({1})",
	"lb_freshdaysTerm": "新着アイコン表示期間",
	"ms_targetGroupNotFound": "※ユーザを追加するグループがありません。グループを作成してください。",
	"lb_accessStatsTitle": "アクセス統計 - {0}",
	"lb_noEntry": "登録無し",
	"lb_administrator": "管理者",
	"lb_readMore": "もっと読む",
	"lb_close": "閉じる",
	"ms_gatheringWidgets": "以下のガジェットをまとめます。",
	"ms_tabNameTooLong": "タブ名が長すぎます。",
	"lb_searchOption": "検索オプション",
	"lb_setting": "設定",
	"lb_changeColnumFailure": "列変更に失敗しました。column={0}, msg=[{1}]",
	"lb_doMerge": "マージする",
	"lb_userSearchNoResult": "検索結果は 0 件でした。",
	"lb_added": "追加済み",
	"lb_getSystemMessageFailure": "システムメッセージの取得に失敗しました。",
	"ms_widgetTitleEmpty": "ガジェットタイトルを入力してください。",
	"lb_initialize": "初期化",
	"ms_cacheDeleteFailure": "キャッシュの削除に失敗しました。 {0} -- {1}",
	"lb_langIT": "イタリア語",
	"lb_credentialList": "認証情報一覧",
	"lb_displayRSS": "RSSを表示",
	"lb_transmission": "送信",
	"lb_addOtherWidget": "その他のガジェットの追加",
	"lb_recentSixMonth": "最近6ヶ月",
	"lb_weekdayTue": "火",
	"ms_previewMenuPath": "メニューに設定されています。",
	"ms_loadTimeout": "読み込みがタイムアウトしました。",
	"lb_descLink": "詳細>>",
	"ms_showTabByClick": "クリックするとこのタブを表示します",
	"lb_lastmodified": "最終更新日時",
	"lb_keywordTooLong": "検索文字列が長すぎます。",
	"ms_deleteTabConfirm": "「{0}」を削除します。よろしいですか？",
	"lb_showAllLatestItems": "新着をすべて表示",
	"ms_loadCancel": "ロード中のためロードをキャンセルします。{0}",
	"lb_inspectionCount": "閲覧回数",
	"lb_countryDE": "ドイツ",
	"lb_noCreator": "作成者なし",
	"ms_sessionTimeoutReLogin": "セッションが切れました。再度ログインしてください。",
	"ms_gtOneNum": "1以上の適切な数値を入力してください。",
	"lb_langJA": "日本語",
	"lb_title": "タイトル",
	"lb_countryCA": "カナダ",
	"lb_3DaysAgo": "三日前",
	"lb_hour": "時",
	"lb_addSchedule": "スケジュールの新規追加",
	"ms_requiredItem2": "必須項目です",
	"lb_ranking": "ランキング",
	"lb_countryAU": "オーストラリア",
	"lb_ref": "参照",
	"ms_multiRssReaderDeleteSubcategory": "MultiRssReader「{0}」のカテゴリ「{1}」が削除されました。",
	"ms_askToSystemManager": "システム管理者にお問い合わせください。",
	"ms_infoNotFoundAt": "{0}「{1}」に表示する情報が見つかりませんでした。",
	"ms_invalidRegexp": "不正な正規表現です。",
	"ms_inputTooLong2": "入力文字列が長すぎます。半角英数字で{0}文字まで入力可能です。\n全角文字が含まれる場合は全角文字は約3文字として数えられます。",
	"ms_urlGetInfoException1": "情報の取得に失敗しました。入力したURLに誤りがないか確認してください。{0} -- {1}",
	"ms_rankingDurationFailed": "ランキング「{0}」の期間が取得できません。{1}",
	"lb_noDiplayItem": "表示する情報がありません。",
	"lb_gadget": "ガジェット",
	"ms_changeToFixedTab": "タブ「{0}」が固定タブに変更されました。パーソナライズエリアのガジェットは全てゴミ箱に入りました。",
	"ms_showWidgetByClick": "クリックするとこのガジェットを表示します",
	"ms_closeGroupSelect": "グループ選択を閉じます",
	"lb_next": "次へ",
	"ms_searchEngineLoadonException": "検索サイト「{0}」でエラーが発生しました。{1}",
	"lb_countryIE": "アイルランド",
	"ms_inputCredential": "認証情報を入力してください。",
	"ms_widgetonExceptionAt": "{0}「{1}」でエラーが発生しました。{2}",
	"lb_weekdayFri": "金",
	"lb_langZH": "中国語",
	"lb_messageClose": "メッセージを閉じる",
	"lb_countryCH": "スイス",
	"lb_checkNewArriedMessageFailure": "新着メッセージのチェックに失敗しました。",
	"ms_menuNotFound": "メニューが見つかりません。",
	"lb_system": "システム",
	"lb_span": "期間",
	"ms_needLoginForUseWidget": "このガジェットの利用にはログインが必要です。",
	"lb_generalSetting": "一般設定",
	"lb_obstacleReort": "障害報告",
	"ms_getMessageListFailure": "メッセージ一覧の取得に失敗しました。",
	"lb_closeAll": "全て閉じる",
	"ms_iCalLoadFailed": "カレンダーの読み込みに失敗しました。 {0} : {1} -- {2}",
	"lb_clearConfigurationDesc1": "ポータル画面を初期表示に戻します。",
	"lb_searchConfigOn404": "検索設定ファイルの読み込みに失敗しました。\nError 404: location \"{0}\" is not found.\n サーバーの設定に誤りがあります。システム管理者にお問い合わせください。",
	"lb_refreshKey": "更新(R)",
	"ms_authFailure": "認証に失敗しました。正しいユーザID/パスワードを入力してください。",
	"ms_classNotFounf": "クラス{0}が見つかりません。",
	"lb_outboundMessage": "送信メッセージ",
	"lb_addContentsExGadget": "http://www.infoscoop.org/gadgets/hello.xml",
	"ms_stopRefresh": "更新を中止します",
	"lb_postMessageToPublic": "公開メッセージを投稿する",
	"lb_logout": "ログアウト",
	"lb_mergeView": "まとめて表示",
	"lb_countryDK": "デンマーク",
	"lb_makeEffective": "有効にする",
	"lb_sendMail": "メール送信",
	"lb_creator": "作者",
	"ms_up_revert_by_admin": "管理者によって、「{0}」ガジェットのユーザ設定「{1}」の値が初期値に戻されました。",
	"lb_notGathering": "まとめない",
	"lb_rssViewSetting": "RSS表示設定",
	"lb_noNewInfo": "新着情報はありません。",
	"lb_i18n": "国際化",
	"lb_preview": "プレビュー",
	"lb_notfound": "表示する情報が見つかりませんでした。",
	"lb_searchConfigException": "検索設定ファイルの読み込みに失敗しました。検索設定に誤りがあります。システム管理者にお問い合わせ下さい。\n{0}",
	"ms_commandonFailure": "コマンドの実行に失敗しました。 {0} -- {1}",
	"ms_userSearchComplete": "ユーザ検索結果を取得しました。",
	"lb_dateCategory": "日付別",
	"lb_summaryView": "サマリー表示",
	"lb_noDisplayFrameBorder": "ガジェット枠を表示しない：",
	"ms_containerLoadon404": "Error 404: location \"{0} /widsrv \" is not found.",
	"lb_clearConfigurationButton": "カスタマイズ情報の初期化",
	"ms_infosccopInitializing": "infoScoopを初期化しています。",
	"lb_notConfirm": "今後は確認しない",
	"lb_newBox": "新しいBOX",
	"lb_any": "{0}",
	"ms_pleaseTurnbackAndSetAuthInfo": "記事を参照するためには、最大化を解除して認証情報を登録して下さい。",
	"ms_widgetBuildError": "ガジェットの作成中にエラーが発生しました。",
	"ms_updatePasswordError": "パスワードの更新に失敗しました。",
	"lb_creatorFilterLabel": "\"{0}\" から始まる作者",
	"lb_resetColumnWidth": "列の幅を揃える",
	"ms_sessionTimeout": "予期しない理由によりセッションが切れました。再度ログインしてください。",
	"lb_lastAccessDate": "最終アクセス日時",
	"lb_proxy": "プロキシ",
	"ms_rankingNoInfo": "Ranking「{0}」に表示する情報が見つかりませんでした。",
	"lb_maximizeSendMail": "{0} %0D%0A%0D%0A {1}",
	"ms_rankingonException": "Ranking「{0}」でエラーが発生しました。{1}",
	"ms_invalidValue2": "不正な値が入力されました。設定し直して下さい。",
	"lb_rankingUnit": "{0}位&nbsp;",
	"ms_urlEncodeonFailureAt": "{0}でURLエンコーディング処理に失敗しました。 {1} -- {2} : {3}({4})",
	"lb_execute": "実行",
	"ms_invalidIconType": "ヘッダアイコンに有効ではないタイプが使われています。{0}[type={1}",
	"lb_openNewWindow": "新しいウィンドウで開く",
	"lb_group": "{0}グループ",
	"ms_rssSearchFailure": "RSS情報の検索に失敗しました。",
	"lb_creatorCategory": "作者別",
	"lb_langDE": "ドイツ語",
	"lb_destination": "宛先",
	"lb_resizeFontSmaller": "文字サイズを小さくする",
	"lb_getCustomInfoonFailure2": "画面カスタマイズ情報の取得に失敗しました。しばらく経ってから再度ログインしてください。",
	"ms_loadtimeoutAt": "{0}「{1}」で読み込みがタイムアウトしました。",
	"lb_firstPage": "最初のページ",
	"lb_yesterday": "昨日",
	"ms_menuLoadonFailure": "メニューの読み込みに失敗しました。",
	"lb_langFR": "フランス語",
	"ms_duplicateGroupName": "同じ名前のグループが存在します。",
	"ms_mergeCategoryError": "{0} : エラーが発生しました。",
	"lb_defaultPanel": "初期画面",
	"lb_langDA": "デンマーク語",
	"lb_setupSchedule": "スケジュールの設定",
	"ms_iframeForbiddenURL": "Webサイト「{0}」は、管理者によりポータル内フレームへの表示が制限されているため、新しいウィンドウで表示されます。",
	"lb_itemCount": "記事数: {0}件",
	"lb_toOnlineManual": "オンラインマニュアルへ",
	"ms_invalidFormat": "正しいフォーマットを指定してください。",
	"lb_year": "年",
	"lb_information": "お知らせ",
	"ms_iCalParseFailed": "カレンダーの解析に失敗しました。 {0} : {1}",
	"ms_urlEncodingonException": "URLエンコーディング処理に失敗しました。 {0} -- {1} : {2}({3})",
	"lb_reportFailure": "報告失敗",
	"ms_forbiddenurlPage": "選択したWebサイトは、管理者によりポータル内フレームでの表示を制限されています。",
	"lb_setupUnfinished": "ガジェットは必要な設定がすべて完了するまで表示できません。",
	"ms_unsetting": "未設定です。",
	"ms_RankingNoPermission": "Ranking「{0}」の読み込み権限がありません。",
	"lb_administration": "管理",
	"lb_countryIN": "インド",
	"lb_rename": "名称変更",
	"ms_getResultFailureAt": "{0}「{1}」で検索結果の取得に失敗しました。",
	"lb_newArriedMessage": "新着メッセージが届いています．",
	"lb_widgetDesignSetting": "ガジェットのデザイン設定",
	"lb_tab": "タブ",
	"ms_atompubPostonException": "「{0}」でエラーが発生しました。\n{1}\n{2}",
	"ms_selectProfile": "プロファイルを選択してください。",
	"ms_searchNotFound": "検索結果は0件です。",
	"lb_new": "New!!",
	"lb_sec": "秒",
	"lb_type": "タイプ",
	"lb_low": "低",
	"ms_invalidUsernameOrPassword": "ユーザー名またはパスワードが違います。",
	"lb_topMenu": "トップメニュー",
	"ms_maximizeRefreshAfterTimeover": "start refresh on closing maximized gadget after auto refresh canceled by timeover",
	"lb_resetToDefaultSettings": "デフォルトに戻す",
	"ms_rssreaderUnreadable": "RssReader設定が読み込めません。",
	"lb_changeApply": "変更を適用する",
	"ms_forbiddenURL": "入力されたURLのWebサイトは、管理者により閲覧を制限されています。",
	"lb_bracketTrashEmptyAll": "[ごみ箱を空にする]",
	"lb_prevPage": "前のページ",
	"ms_changeTabFailed": "タブの切替に失敗しました。{0}",
	"ms_doubleEntryFailure": "{0}は２回目の実行に失敗したので破棄されました。",
	"lb_userSearch": "ユーザの検索",
	"lb_countryIT": "イタリア",
	"ms_rankingTimeout": "Ranking「{0}」の取得がタイムアウトしました。",
	"ms_logofftimeSavingfailure": "ログオフ処理に失敗しました。{0}",
	"lb_addContentsExWebSite": "http://www.infoscoop.org/index.php/ja/",
	"ms_widgetBkgcolorError": "{0}「{1}」でエラーが発生しました。背景色を設定できませんでした。",
	"lb_messageOfGroup": "{0}グループのメッセージ",
	"lb_userNotAddedGroup": "このグループにはユーザが追加されていません。",
	"lb_langEN": "英語",
	"lb_urlExample": "URL入力例",
	"ms_sorry": "ごめんなさい･･･",
	"ms_gtZeroNum": "0以上の適切な数値を入力してください。",
	"lb_notitle": "タイトル無し",
	"ms_urlNoInput": "URLを入力して下さい。",
	"ms_urlTooLong": "URL が長すぎます。URL の長さは半角英数字で2000文字までです。\n全角文字が含まれる場合は全角文字は約9文字として数えられます。",
	"ms_noPermissionAt": "{0}「{1}」の読み込み権限がありません。",
	"ms_getRssInfoonException": "RSS情報の取得に失敗しました。入力したURLに誤りがないか確認してください。{0} -- {1}",
	"lb_searchUser": "カレンダーの検索と表示",
	"lb_saveSettings": "設定の保存",
	"ms_searchEngineLoadonFailure": "検索サイト「{0}」でエラーが発生しました。{1} -- {2}",
	"ms_getRssInfoonFailure": "RSS情報の取得に失敗しました。入力したURLに誤りがないか確認してください。",
	"lb_searchCondition": "検索条件",
	"ms_erroronSubWidgetMove": "サブカテゴリ「{0}」の移動処理でエラーが発生しました",
	"ms_noInputPassword": "パスワードが入力されていません。",
	"ms_menuLoadon10408": "メニューの読み込みがタイムアウトしました",
	"ms_getInfoFailureAt": "{0} 「{1}」で詳細情報の取得に失敗しました。",
	"ms_clearConfigurationFailed": "カスタマイズ情報の初期化に失敗しました",
	"lb_high": "高",
	"lb_widget": "ガジェット",
	"lb_1weekAgo": "一週間前",
	"lb_addContentsExRSS": "http://www.infoscoop.org/index.php/ja/news.feed",
	"lb_showHelp": "ヘルプを表示",
	"lb_wallPaperSetting": "壁紙設定",
	"lb_addUser": "ユーザ追加",
	"ms_getRssInfoonUnsccess": "RSS情報の取得に失敗しました。入力したURLに誤りがないか確認してください。{0}",
	"lb_month": "月",
	"lb_openMySiteMap": "マイサイトマップを開きます",
	"lb_maximizeShortcutsItemAndFull": "(アイテム選択時 &amp; 全文表示時)",
	"lb_endOfUserSearch": "ユーザ検索の終了",
	"lb_containerLoadonException": "画面の構成に失敗しました: {0}",
	"lb_mySiteMap": "マイサイトマップ",
	"ms_errorSetAuthInfo": "入力したユーザID/パスワードによる認証に失敗しました。ユーザID/パスワードは更新されませんでした。",
	"ms_lastlogoutSavingfailure": "前回ログアウト時のカスタマイズ情報は保存されませんでした。",
	"ms_duplicateProfile": "重複するプロファイルが存在します",
	"ms_inputURL": "URLを入力してください。",
	"lb_closeAddContents": "コンテンツ追加を閉じます",
	"lb_addRssFeed": "RSSフィードの追加",
	"ms_minimizeFailure": "{0}の最小化に失敗しました: {1}",
	"ms_maximizeCloseRefresh": "start refresh on closing maximized gadget",
	"lb_illegalToolbarItem": "不正なツールバーアイコンです。不明なタイプ [{0}]",
	"lb_editGroup": "グループ編集",
	"lb_error": "エラー",
	"lb_sendMailTitle": "[{0}]{1}",
	"lb_containerLoginonException": "画面の構成に失敗しました。カスタマイズ情報データに不整合が発生している可能性があります。システム管理者にお問い合わせください。",
	"ms_userIdEmpty": "ユーザIDを入力してください。",
	"lb_countryES": "スペイン",
	"ms_tabsRefresh": "全てのタブに配置されたガジェットを更新します",
	"lb_langNO": "ノルウェー語",
	"ms_iCalCreateFailed": "カレンダーの生成に失敗しました。 {0}",
	"lb_countOneDay": "1日前",
	"ms_datecreatorChangeFailed": "{0}の日付/作成者の表示/非表示設定の変更に失敗しました: {1}",
	"lb_delete": "削除",
	"ms_lineChangeFailure": "{0}の改行設定の変更に失敗しました: {1}",
	"lb_turnbackMaximize": "戻る",
	"lb_org": "組織",
	"lb_prev": "前へ",
	"ms_confirmDeleteGroup": "グループを削除します、よろしいですか？",
	"ms_sendMessageFailed": "メッセージの送信に失敗しました。",
	"lb_noInfoOnMaximize": "最大化で表示可能な情報がありません。",
	"ms_widgeTitleTooLong": "ガジェットタイトルに指定できる文字数を超えています。",
	"ms_inputTxtBox": "テキストボックスに内容を入力してください。",
	"ms_shortcutsNotice": "※ショートカットキーが使えない場合は日本語入力を無効にしてみてください。",
	"lb_trashBox": "ごみ箱",
	"lb_recentOneWeek": "最近1週間",
	"lb_authType": "認証タイプ",
	"ms_widgetDuplicateWarn": "同じガジェットが既にあるため追加できません。({0})",
	"ms_RankingCriticalerror": "エラーが発生しました.<br/>{0}<br/>このガジェットは現在利用不可能です。",
	"lb_mail": "メール",
	"ms_onSheetReaderSSOonException": "OnSheetシングルサインオン処理に失敗しました。{0}",
	"lb_deployAll": "全て展開",
	"lb_detailAndBlank": "詳細&nbsp;&nbsp;",
	"lb_widgetTitle": "ガジェットタイトル",
	"ms_loginFailed": "ログインに失敗しました。",
	"lb_latestMessage": "最新のメッセージ",
	"lb_selectWidgetHeaderImage": "ガジェットのヘッダの背景に使用する画像を以下から選択してください。",
	"ms_failedCheckCharLength": "入力文字列の長さチェックに失敗しました。",
	"ms_invalidCharset": "不正な文字セットです。",
	"ms_customizeDeleteonFailure": "カスタマイズ情報の削除に失敗しました。 {0} -- {1}",
	"lb_noMessage": "メッセージはありません。",
	"lb_countryNO": "ノルウェー",
	"lb_saveFilterSetting": "[日付]以外の絞込み項目はRSSリーダーの設定として保存されます。",
	"ms_getRssInfoTimeout": "RSS情報の取得がタイムアウトしました",
	"ms_getdataerror404": "Error 404: location {0} is not found.",
	"ms_customizeDeleteonException": "カスタマイズ情報の削除に失敗しました。 {0}",
	"lb_countryFR": "フランス",
	"lb_select": "選択",
	"ms_toggleEditElementByClick": "クリックすると {0} 要素の内容を編集するフォームに切り替わります。",
	"lb_weekdaySat": "土",
	"ms_widgetonExceptionNotAvailableAt": "{0}「{1}」でエラーが発生しました。<br/>{2}<br/>このガジェットは現在利用不可能です。",
	"lb_openMenu": "メニューを開く",
	"lb_saveLoginState": "ログイン状態を保存する",
	"ms_noRssInfo": "このサイトにはRSS情報はありません。",
	"lb_doubleAdd": "選択されたガジェットは既に追加済みです。",
	"ms_atomRegetonException": "Atomの再取得に失敗しました。\n{0}",
	"lb_messageConsole": "メッセージコンソール",
	"ms_selectValidProfile": "有効なプロファイルを選択してください。",
	"ms_emptyAt": "{0} が未入力です。",
	"ms_mergeCategoryError10408": "{0} : 読み込みがタイムアウトしました。",
	"lb_adminLink": "管理画面へ",
	"ms_inputTitle": "タイトルを入力して下さい。",
	"lb_countryCN": "中国",
	"lb_getCustomInfoon404": "画面カスタマイズ情報の取得に失敗しました。サーバーの設定に誤りがあります。システム管理者にお問い合わせください。",
	"ms_invalidWidget": "このガジェットは現在利用不可能です。",
	"lb_category": "カテゴリ",
	"lb_deleteDate": "削除した日",
	"lb_day": "日",
	"lb_forbiddenURL": "禁止URL",
	"ms_invalidOldPassword": "古いパスワードが間違っています。",
	"lb_changePassword": "パスワードの変更",
	"lb_langFI": "フィンランド語",
	"ms_oauthFailed": "認証処理に失敗しました。",
	"ms_getSearchResultFailure": "検索結果の取得に失敗しました。",
	"ms_configNotFound": "{0}の構成ファイルが存在しません。",
	"ms_searchEngineLoadon404": "検索サイト「{0}」に表示する情報が見つかりませんでした。",
	"lb_edit": "編集",
	"lb_loginTitle": "ログイン",
	"lb_closeSitemap": "サイドメニューを閉じます",
	"lb_newpass": "新パスワード",
	"lb_toLogin": "ログイン画面へ",
	"lb_middle": "中",
	"lb_minimize": "最小化",
	"ms_trashLoadonFailure": "ごみ箱情報が取得できませんでした。{0} -- {1}",
	"lb_mergeConfirmDialog": "ガジェットマージ確認ダイアログ",
	"lb_groupList": "グループ一覧",
	"lb_sentMessageTo": "{0}へメッセージを送る",
	"lb_noDate": "日付なし",
	"lb_scheduleMonthFormat": "yyyy年 M月",
	"lb_weekdayThu": "木",
	"ms_revertWidget": "タブ「{0}」に追加されています。クリックすると戻ります。",
	"lb_gadgetColon": "ガジェット:",
	"ms_cannotAddGadgetToThisTab": "このタブにはガジェットを追加することができません。",
	"lb_rssColon": "RSS:",
	"lb_deleteUser": "ユーザー削除",
	"lb_enableRoundCorner": "ガジェットの角を丸くする：",
	"ms_menuIconException": "メニュー「{0}」のアイコン表示設定でエラーが発生しました：{1}",
	"lb_countryJP": "日本",
	"ms_errorOnWindowResize": "ウィンドウリサイズ時の処理でエラーが発生しました: {0}",
	"lb_weekdayMon": "月",
	"lb_addWebPage": "Webページの追加",
	"lb_resizeFontLarger": "文字サイズを大きくする",
	"ms_customizeSavingFailure2": "カスタマイズ情報の保存に失敗しました。 {0} -- {1}",
	"lb_nationalHoliday": "祝日",
	"ms_clearConfigurationForceReload": "カスタマイズ情報が初期化された為、リロードを行います。",
	"ms_onSheetReaderSSOonFailure": "OnSheetシングルサインオン処理に失敗しました。 {0} -- {1}",
	"lb_langSV": "スウェーデン語",
	"lb_browserNotSupported": "現在使用しているブラウザはサポートされていません。",
	"ms_mergeCategoryError403": "{0} : 読み込み権限がありません。",
	"lb_addGroup": "グループ追加",
	"ms_iCalLoadTimeout": "カレンダーの読み込みがタイムアウトしました。 {0}",
	"lb_changeNotApply": "変更しない",
	"lb_showRssInSite": "サイト内RSSの表示：<br/>&nbsp;&nbsp;http://www.nikkeibp.co.jp/<br/>",
	"ms_noInputDestination": "宛先を入力してください。",
	"lb_pageTop": "先頭のページ",
	"lb_allUsersPublicMessage": "全ユーザの公開メッセージ",
	"ms_menuLoadonException": "メニューの読み込みに失敗しました。{0}",
	"lb_doReply": "返信する",
	"lb_countryKR": "韓国",
	"lb_openAddContents": "コンテンツ追加を開きます",
	"ms_addCheckedUser": "※チェックしたユーザを［{0}］に追加します",
	"msg_title": "メッセージコンソール",
	"lb_closeLink": "閉じる<<",
	"lb_initTab": "タブの構成を初期化する",
	"lb_reportFinished": "報告完了",
	"lb_weekdayWed": "水",
	"lb_searchConfigOnFailure": "検索設定ファイルの読み込みに失敗しました。{0} --  {1}",
	"ms_overMaxIntValue": "最大値を超えています。最大値は2147483647です。",
	"ms_teleconSetupRequire": "このガジェットを使用するためには初期設定が必要です。<br/>検索キーワードを設定してください。",
	"lb_lastPage": "最後のページ",
	"ms_enrtyNotFound": "{0}に該当するエントリーが見つかりません。",
	"ms_urlGetInfoException2": "情報の取得に失敗しました。入力したURLに誤りがないか確認してください。{0}",
	"ms_customizeSaved": "カスタマイズ情報を保存しました。",
	"lb_login": "ログイン",
	"lb_countryFI": "フィンランド",
	"ms_on10998": "他のブラウザでinfoScoopが起動されました。このブラウザ上の更新情報は反映されません。",
	"lb_maximize": "最大化",
	"lb_oldPassword": "旧パスワード",
	"lb_postMessageAsPublic": "公開メッセージとして投稿する",
	"lb_setAuth": "認証情報セット",
	"lb_subscribes": "{0}を購読する",
	"ms_menuMoveonError": "メニュー「{0}」の移動処理でエラーが発生しました",
	"lb_turnback": "元に戻す",
	"lb_urlDirectInput": "使い方の例<br/>URLの直接入力：<br/>&nbsp;&nbsp;http://www.nikkeibp.co.jp/index.rdf<br/>",
	"ms_passwordResetConfirm": "設定したパスワードは以下のURLで認証が失敗しましたが、設定しますか？",
	"lb_nextPageLink": "次のページ>>",
	"lb_getCustomInfoonFailure1": "画面カスタマイズ情報の取得に失敗しました: {0} -- {1}",
	"lb_bracketClose": "[閉じる]",
	"lb_userID": "ユーザID",
	"lb_password": "パスワード",
	"lb_holiday": "休日",
	"ms_duplicateDeleteConfirm": "「{0}」は既にタブ「{1}」に表示されています。\n「{2}」からガジェットを削除してもよろしいですか？",
	"lb_relogin": "再ログイン",
	"ms_authServiceNotWork": "認証サービスが正常に機能していません。",
	"ms_inputOverMaxValue": "設定できる最大値を超えています。{0}以下に設定してください。",
	"ms_changePasswordFailed": "パスワードの変更に失敗しました。",
	"ms_invalidValue": "不正な値です。",
	"lb_searchResult": "検索結果",
	"ms_urlEncodingFailed": "URLエンコーディング処理に失敗しました。 {0} : {1}({2})",
	"lb_reload": "再読み込み",
	"lb_filterDescSettingLink": "詳細な絞込み設定 >>",
	"ms_gtZeroOrAuto": "autoまたは0より大きな数値を入力してください。",
	"ms_passwordChanged": "パスワードを変更しました。",
	"lb_countryRU": "ロシア",
	"ms_trashonException": "ごみ箱情報が取得できませんでした。{0}",
	"lb_deploy": "展開",
	"ms_rssSearchTimeout": "RSS情報の検索がタイムアウトしました。",
	"lb_widgetEditHelp": "ヘルプ",
	"lb_eMail": "E-Mail",
	"lb_businessDate": "営業日",
	"ms_needsAuthentication": "ガジェットを最大化するためには認証情報を登録してください。",
	"lb_menu": "メニュー",
	"lb_clearConfigurationDesc2": "カスタマイズ情報を初期化すると追加したタブとガジェットが全て削除されます。",
	"lb_widgetTitle_empty": "ガジェットタイトルを入力してください。",
	"lb_prevItem": "前のアイテム",
	"lb_changePass": "パスワード変更",
	"lb_selectSubWidgetHeaderImage": "サブガジェットのヘッダの背景色を以下から選択してください。",
	"messsage_invalidDefaultValue": "有効ではない初期値が設定されています : {0} UserPref[@name={1}]",
	"lb_countryNL": "オランダ",
	"lb_newTab": "新しいタブ",
	"lb_countDown": "「{0}」まで、あと",
	"lb_recentOneMonth": "最近1ヶ月",
	"lb_property": "プロパティ",
	"ms_getdatafailure": "Error {0} -- {1}",
	"ms_clearTabConfigurationConfirm": "追加したガジェットを全て削除します、よろしいですか？\n(削除したガジェットはごみ箱に入ります)",
	"lb_canBeAddContents": "追加可能なコンテンツ",
	"lb_dateFilterInfo": "{0}のエントリー",
	"ms_customizeWidthByDrag": "ドラッグで幅を調整できます",
	"lb_cancel": "キャンセル",
	"lb_loading": "Loading...",
	"ms_rankingonFailure": "Ranking「{0}」でエラーが発生しました。{1} -- {2}",
	"lb_info": "情報",
	"ms_gadgetError": "ガジェット「{0}」でエラーが発生しました。",
	"lb_countryBR": "ブラジル",
	"ms_title_update_by_admin": "管理者によって、「{0}」ガジェットのタイトルが「{1}」に変更されました。",
	"ms_refferenceAt": "から参照できます。",
	"lb_messageMore": "残りのメッセージを表示",
	"ms_autoReloadCancel": "ロード中のため自動リフレッシュをキャンセルします。{0}",
	"lb_addContents": "コンテンツの追加",
	"lb_change": "変更",
	"ms_noPermission401": "ユーザIDとパスワードを入力してください。",
	"lb_resizeFontNormal": "文字サイズを標準にする",
	"ms_sessionTimeoutByOtherLogin": "セッションが切れました。<br/>別のブラウザでログインされた可能性もあります。<br/>再度ログインしてください。<br/>",
	"lb_authInfo": "認証情報",
	"lb_langRU": "ロシア語",
	"ms_propertyLoadonFailure": "プロパティの読み込みに失敗しました。",
	"lb_nextItem": "次のアイテム",
	"lb_editSummary": "概要を編集",
	"ms_noPermission": "読み込み権限がありません。",
	"lb_urlList": "URL一覧",
	"lb_editDesc": "詳細を編集",
	"lb_belong": "所属",
	"ms_widgetonFailureAt": "{0}「{1}」でエラーが発生しました。{2} -- {3}",
	"lb_entry": "登録",
	"lb_name": "名前",
	"lb_attention": "※",
	"lb_here": "こちら",
	"lb_releaseMaximize": "元に戻る（最大化解除）",
	"lb_siteMap": "サイトマップ",
	"lb_previewError": "プレビューを表示できません。",
	"lb_refreshMenu": "メニューの更新",
	"ms_reportfailure2": "障害報告処理に失敗しました。 {0}",
	"ms_custmizeFailedReload": "カスタマイズ情報の保存に失敗しました。ブラウザの再ロードを行います。",
	"ms_timeAlert": "「{0}」の時間です。",
	"ms_timeOut": "タイムアウトしました。",
	"ms_noURL": "リンク先のURLがありません",
	"ms_searchNotAvailable": "検索設定が読み込めませんでした。現在検索は行えません。",
	"ms_clearConfigurationConfirm": "追加したタブとガジェットを全て削除します、よろしいですか？\n(削除したガジェットはごみ箱に入ります)",
	"ms_atomRegetFailure": "Atomの再取得に失敗しました。\n{0} -- {1}",
	"lb_changeColumn": "列数変更"
}
