var IS_R = {
	"lb_langNL": "オランダ語",
	"ms_userSearchonException": "ユーザ検索で例外が発生しました。",
	"lb_1monthAgo": "一ヶ月前",
	"lb_countryUK": "イギリス",
	"ms_menuLoadOnUnSuccess": "メニューの読み込みに失敗しました。 {0} -- {1}",
	"lb_countrySE": "スウェーデン",
	"lb_newGroup": "新しいグループ",
	"ms_menuadded": "メニュー[{0}]が追加されました。",
	"lb_weekdaySun": "日",
	"lb_openSiteMap": "サイドメニューを開きます",
	"ms_propertyNotFound": "プロパティが見つかりません。",
	"ms_mergeCategoryError404": "{0} : 表示する情報が見つかりませんでした。",
	"ms_menuNotFound2": "メニュー「{0}」が見つかりません。",
	"ms_invalidURL": "有効なＵＲＬではありません",
	"lb_gathering": "まとめる",
	"lb_webSiteColon": "Webサイト:",
	"lb_all": "全て",
	"ms_dragNoMerge": "Ctrlキー押下中はRSSガジェット同士のマージを行いません。",
	"lb_add": "追加",
	"lb_countryMX": "メキシコ",
	"ms_closeMySiteMap": "マイサイトマップを閉じます",
	"lb_refresh": "更新",
	"ms_validateError": "バリデーションチェックに失敗しました。{0}",
	"ms_getdatafailed": "データが取得できませんでした。",
	"ms_trashContextExplanation": "右クリックで[元に戻す]/[削除]ができます。",
	"ms_thisIsFixedTab": "このタブは固定タブです。カスタマイズできません。",
	"ms_invalidDateFormat": "不正な日付フォーマットです。",
	"lb_countryUS": "アメリカ",
	"lb_langPtBR": "ポルトガル語",
	"ms_mergeConfirm": "「{0}」に「{1}」をマージしますか？",
	"ms_confirmDeleteUser": "ユーザを削除します、よろしいですか？",
	"lb_toTopPage": "トップページへ",
	"lb_countryNZ": "ニュージーランド",
	"lb_selectWallPaperImage": "壁紙に設定する画像を以下から選択してください。",
	"lb_default": "デフォルト",
	"lb_invalidate": "無効にする",
	"lb_setupAll": "全体設定",
	"lb_doNotMerge": "マージしない（戻す）",
	"lb_noInfo": "表示可能な情報はありません。",
	"lb_dropAll": "まとめてドロップ",
	"ms_commandonException": "コマンドの実行に失敗しました。 {0}",
	"ms_iCalNoPermission": "カレンダー「{0}」の読み込み権限がありません。",
	"ms_deletaTabFailed": "タブ「{0}」の削除に失敗しました。",
	"lb_displayAll": "全て表示",
	"lb_reset": "リセット",
	"lb_date": "日付",
	"ms_requiredItem": "は必須項目です",
	"lb_langES": "スペイン語",
	"lb_today": "今日",
	"lb_warn": "警告",
	"ms_inputTooLong": "入力文字列が長すぎます。{0}文字以下にしてください。",
	"lb_search": "検索",
	"lb_addTabLink": ">>タブを追加する",
	"lb_searchConditionNotSet": "検索条件が設定されていません。",
	"ms_mergeCategoryError10550": "{0} : 情報が解析できません。",
	"lb_debug": "デバッグ",
	"ms_failedLoadIcons": "ガジェットアイコンの読み込みに失敗しました。",
	"lb_langKO": "韓国語",
	"ms_customizeSavingFailure1": "カスタマイズ情報の保存に失敗しました。{0}",
	"lb_freshdaysTerm": "新着アイコン表示期間",
	"ms_targetGroupNotFound": "※ユーザを追加するグループがありません。グループを作成してください。",
	"lb_close": "閉じる",
	"ms_gatheringWidgets": "以下のガジェットをまとめます。",
	"lb_setting": "設定",
	"lb_changeColnumFailure": "列変更に失敗しました。column={0}, msg=[{1}]",
	"lb_doMerge": "マージする",
	"lb_userSearchNoResult": "検索結果は 0 件でした。",
	"lb_added": "追加済み",
	"lb_initialize": "初期化",
	"ms_cacheDeleteFailure": "キャッシュの削除に失敗しました。 {0} -- {1}",
	"lb_langIT": "イタリア語",
	"lb_credentialList": "認証情報一覧",
	"lb_displayRSS": "RSSを表示",
	"lb_weekdayTue": "火",
	"ms_previewMenuPath": "メニューに設定されています。",
	"ms_loadTimeout": "読み込みがタイムアウトしました。",
	"lb_descLink": "詳細>>",
	"ms_showTabByClick": "クリックするとこのタブを表示します",
	"ms_cannotDeleteLastTab": "タブを全て削除することはできません。",
	"ms_deleteTabConfirm": "「{0}」を削除します。よろしいですか？",
	"lb_showAllLatestItems": "新着をすべて表示",
	"ms_loadCancel": "ロード中のためロードをキャンセルします。{0}",
	"lb_countryDE": "ドイツ",
	"ms_sessionTimeoutReLogin": "セッションが切れました。再度ログインしてください。",
	"ms_gtOneNum": "1以上の適切な数値を入力してください。",
	"lb_langJA": "日本語",
	"lb_title": "タイトル",
	"lb_countryCA": "カナダ",
	"lb_3DaysAgo": "三日前",
	"ms_requiredItem2": "必須項目です",
	"lb_countryAU": "オーストラリア",
	"lb_ref": "参照",
	"ms_multiRssReaderDeleteSubcategory": "MultiRssReader「{0}」のカテゴリ「{1}」が削除されました。",
	"ms_infoNotFoundAt": "{0}「{1}」に表示する情報が見つかりませんでした。",
	"ms_invalidRegexp": "不正な正規表現です。",
	"ms_inputTooLong2": "入力文字列が長すぎます。半角英数字で{0}文字まで入力可能です。\n全角文字が含まれる場合は全角文字は約3文字として数えられます。",
	"ms_urlGetInfoException1": "情報の取得に失敗しました。入力したURLに誤りがないか確認してください。{0} -- {1}",
	"lb_noDiplayItem": "表示する情報がありません。",
	"lb_gadget": "ガジェット",
	"ms_changeToFixedTab": "タブ「{0}」が固定タブに変更されました。パーソナライズエリアのガジェットは全てゴミ箱に入りました。",
	"ms_showWidgetByClick": "クリックするとこのガジェットを表示します",
	"lb_countryIE": "アイルランド",
	"ms_inputCredential": "認証情報を入力してください。",
	"ms_widgetonExceptionAt": "{0}「{1}」でエラーが発生しました。{2}",
	"lb_weekdayFri": "金",
	"lb_langZH": "中国語",
	"lb_messageClose": "メッセージを閉じる",
	"lb_countryCH": "スイス",
	"ms_menuNotFound": "メニューが見つかりません。",
	"lb_generalSetting": "一般設定",
	"lb_closeAll": "全て閉じる",
	"ms_iCalLoadFailed": "カレンダーの読み込みに失敗しました。 {0} : {1} -- {2}",
	"lb_clearConfigurationDesc1": "ポータル画面を初期表示に戻します。",
	"lb_refreshKey": "更新(R)",
	"ms_authFailure": "認証に失敗しました。正しいユーザID/パスワードを入力してください。",
	"ms_classNotFounf": "クラス{0}が見つかりません。",
	"lb_addContentsExGadget": "http://www.infoscoop.org/gadgets/hello.xml",
	"ms_stopRefresh": "更新を中止します",
	"lb_logout": "ログアウト",
	"lb_mergeView": "まとめて表示",
	"lb_countryDK": "デンマーク",
	"lb_makeEffective": "有効にする",
	"lb_sendMail": "メール送信",
	"lb_creator": "作者",
	"lb_notGathering": "まとめない",
	"lb_rssViewSetting": "RSS表示設定",
	"lb_noNewInfo": "新着情報はありません。",
	"lb_preview": "プレビュー",
	"lb_notfound": "表示する情報が見つかりませんでした。",
	"ms_commandonFailure": "コマンドの実行に失敗しました。 {0} -- {1}",
	"ms_userSearchComplete": "ユーザ検索結果を取得しました。",
	"lb_noDisplayFrameBorder": "ガジェット枠を表示しない：",
	"ms_containerLoadon404": "Error 404: location \"{0} /widsrv \" is not found.",
	"lb_clearConfigurationButton": "カスタマイズ情報の初期化",
	"ms_infosccopInitializing": "infoScoopを初期化しています。",
	"lb_notConfirm": "今後は確認しない",
	"lb_newBox": "新しいBOX",
	"lb_any": "{0}",
	"ms_pleaseTurnbackAndSetAuthInfo": "記事を参照するためには、最大化を解除して認証情報を登録して下さい。",
	"ms_widgetBuildError": "ガジェットの作成中にエラーが発生しました。",
	"ms_updatePasswordError": "パスワードの更新に失敗しました。",
	"lb_resetColumnWidth": "列の幅を揃える",
	"ms_sessionTimeout": "予期しない理由によりセッションが切れました。再度ログインしてください。",
	"lb_maximizeSendMail": "{0} %0D%0A%0D%0A {1}",
	"ms_invalidIconType": "ヘッダアイコンに有効ではないタイプが使われています。{0}[type={1}",
	"lb_langDE": "ドイツ語",
	"lb_resizeFontSmaller": "文字サイズを小さくする",
	"lb_getCustomInfoonFailure2": "画面カスタマイズ情報の取得に失敗しました。しばらく経ってから再度ログインしてください。",
	"ms_loadtimeoutAt": "{0}「{1}」で読み込みがタイムアウトしました。",
	"lb_yesterday": "昨日",
	"ms_menuLoadonFailure": "メニューの読み込みに失敗しました。",
	"lb_langFR": "フランス語",
	"ms_mergeCategoryError": "{0} : エラーが発生しました。",
	"lb_langDA": "デンマーク語",
	"ms_iframeForbiddenURL": "Webサイト「{0}」は、管理者によりポータル内フレームへの表示が制限されているため、新しいウィンドウで表示されます。",
	"lb_itemCount": "記事数: {0}件",
	"ms_invalidFormat": "正しいフォーマットを指定してください。",
	"ms_iCalParseFailed": "カレンダーの解析に失敗しました。 {0} : {1}",
	"ms_urlEncodingonException": "URLエンコーディング処理に失敗しました。 {0} -- {1} : {2}({3})",
	"lb_setupUnfinished": "ガジェットは必要な設定がすべて完了するまで表示できません。",
	"lb_countryIN": "インド",
	"lb_rename": "名称変更",
	"lb_widgetDesignSetting": "ガジェットのデザイン設定",
	"lb_new": "New!!",
	"lb_type": "タイプ",
	"lb_topMenu": "トップメニュー",
	"ms_rssreaderUnreadable": "RssReader設定が読み込めません。",
	"lb_changeApply": "変更を適用する",
	"ms_forbiddenURL": "入力されたURLのWebサイトは、管理者により閲覧を制限されています。",
	"lb_bracketTrashEmptyAll": "[ごみ箱を空にする]",
	"ms_changeTabFailed": "タブの切替に失敗しました。{0}",
	"ms_doubleEntryFailure": "{0}は２回目の実行に失敗したので破棄されました。",
	"lb_userSearch": "ユーザの検索",
	"lb_countryIT": "イタリア",
	"ms_logofftimeSavingfailure": "ログオフ処理に失敗しました。{0}",
	"lb_addContentsExWebSite": "http://www.infoscoop.org/index.php/ja/",
	"ms_widgetBkgcolorError": "{0}「{1}」でエラーが発生しました。背景色を設定できませんでした。",
	"lb_userNotAddedGroup": "このグループにはユーザが追加されていません。",
	"lb_langEN": "英語",
	"lb_urlExample": "URL入力例",
	"ms_gtZeroNum": "0以上の適切な数値を入力してください。",
	"lb_notitle": "タイトル無し",
	"ms_urlNoInput": "URLを入力して下さい。",
	"ms_urlTooLong": "URL が長すぎます。URL の長さは半角英数字で2000文字までです。\n全角文字が含まれる場合は全角文字は約9文字として数えられます。",
	"ms_noPermissionAt": "{0}「{1}」の読み込み権限がありません。",
	"lb_searchCondition": "検索条件",
	"ms_menuLoadon10408": "メニューの読み込みがタイムアウトしました",
	"ms_clearConfigurationFailed": "カスタマイズ情報の初期化に失敗しました",
	"lb_widget": "ガジェット",
	"lb_1weekAgo": "一週間前",
	"lb_addContentsExRSS": "http://www.infoscoop.org/index.php/ja/news.feed",
	"lb_wallPaperSetting": "壁紙設定",
	"lb_addUser": "ユーザ追加",
	"lb_openMySiteMap": "マイサイトマップを開きます",
	"lb_containerLoadonException": "画面の構成に失敗しました: {0}",
	"ms_errorSetAuthInfo": "入力したユーザID/パスワードによる認証に失敗しました。ユーザID/パスワードは更新されませんでした。",
	"ms_lastlogoutSavingfailure": "前回ログアウト時のカスタマイズ情報は保存されませんでした。",
	"ms_inputURL": "URLを入力してください。",
	"lb_closeAddContents": "コンテンツ追加を閉じます",
	"ms_minimizeFailure": "{0}の最小化に失敗しました: {1}",
	"lb_illegalToolbarItem": "不正なツールバーアイコンです。不明なタイプ [{0}]",
	"lb_editGroup": "グループ編集",
	"lb_error": "エラー",
	"lb_sendMailTitle": "[{0}]{1}",
	"lb_containerLoginonException": "画面の構成に失敗しました。カスタマイズ情報データに不整合が発生している可能性があります。システム管理者にお問い合わせください。",
	"ms_userIdEmpty": "ユーザIDを入力してください。",
	"lb_countryES": "スペイン",
	"ms_tabsRefresh": "全てのタブに配置されたガジェットを更新します",
	"lb_langNO": "ノルウェー語",
	"ms_iCalCreateFailed": "カレンダーの生成に失敗しました。 {0}",
	"ms_datecreatorChangeFailed": "{0}の日付/作成者の表示/非表示設定の変更に失敗しました: {1}",
	"lb_delete": "削除",
	"ms_lineChangeFailure": "{0}の改行設定の変更に失敗しました: {1}",
	"lb_turnbackMaximize": "戻る",
	"lb_prev": "前へ",
	"ms_confirmDeleteGroup": "グループを削除します、よろしいですか？",
	"lb_noInfoOnMaximize": "最大化で表示可能な情報がありません。",
	"lb_trashBox": "ごみ箱",
	"lb_authType": "認証タイプ",
	"ms_widgetDuplicateWarn": "同じガジェットが既にあるため追加できません。({0})",
	"lb_mail": "メール",
	"lb_deployAll": "全て展開",
	"lb_widgetTitle": "ガジェットタイトル",
	"lb_selectWidgetHeaderImage": "ガジェットのヘッダの背景に使用する画像を以下から選択してください。",
	"ms_failedCheckCharLength": "入力文字列の長さチェックに失敗しました。",
	"ms_invalidCharset": "不正な文字セットです。",
	"lb_countryNO": "ノルウェー",
	"lb_saveFilterSetting": "[日付]以外の絞込み項目はRSSリーダーの設定として保存されます。",
	"ms_getdataerror404": "Error 404: location {0} is not found.",
	"lb_countryFR": "フランス",
	"lb_select": "選択",
	"lb_weekdaySat": "土",
	"lb_openMenu": "メニューを開く",
	"lb_doubleAdd": "選択されたガジェットは既に追加済みです。",
	"lb_messageConsole": "メッセージコンソール",
	"ms_emptyAt": "{0} が未入力です。",
	"ms_mergeCategoryError10408": "{0} : 読み込みがタイムアウトしました。",
	"lb_adminLink": "管理画面へ",
	"lb_countryCN": "中国",
	"lb_getCustomInfoon404": "画面カスタマイズ情報の取得に失敗しました。サーバーの設定に誤りがあります。システム管理者にお問い合わせください。",
	"ms_invalidWidget": "このガジェットは現在利用不可能です。",
	"lb_category": "カテゴリ",
	"lb_deleteDate": "削除した日",
	"lb_langFI": "フィンランド語",
	"ms_configNotFound": "{0}の構成ファイルが存在しません。",
	"lb_edit": "編集",
	"lb_closeSitemap": "サイドメニューを閉じます",
	"lb_minimize": "最小化",
	"ms_trashLoadonFailure": "ごみ箱情報が取得できませんでした。{0} -- {1}",
	"lb_mergeConfirmDialog": "ガジェットマージ確認ダイアログ",
	"lb_scheduleMonthFormat": "yyyy年 M月",
	"lb_weekdayThu": "木",
	"ms_revertWidget": "タブ「{0}」に追加されています。クリックすると戻ります。",
	"lb_gadgetColon": "ガジェット:",
	"ms_cannotAddGadgetToThisTab": "このタブにはガジェットを追加することができません。",
	"lb_rssColon": "RSS:",
	"lb_deleteUser": "ユーザー削除",
	"lb_enableRoundCorner": "ガジェットの角を丸くする：",
	"ms_menuIconException": "メニュー「{0}」のアイコン表示設定でエラーが発生しました：{1}",
	"lb_countryJP": "日本",
	"ms_errorOnWindowResize": "ウィンドウリサイズ時の処理でエラーが発生しました: {0}",
	"lb_weekdayMon": "月",
	"lb_resizeFontLarger": "文字サイズを大きくする",
	"ms_clearConfigurationForceReload": "カスタマイズ情報が初期化された為、リロードを行います。",
	"lb_langSV": "スウェーデン語",
	"ms_mergeCategoryError403": "{0} : 読み込み権限がありません。",
	"lb_addGroup": "グループ追加",
	"ms_iCalLoadTimeout": "カレンダーの読み込みがタイムアウトしました。 {0}",
	"lb_changeNotApply": "変更しない",
	"ms_menuLoadonException": "メニューの読み込みに失敗しました。{0}",
	"lb_countryKR": "韓国",
	"lb_openAddContents": "コンテンツ追加を開きます",
	"ms_addCheckedUser": "※チェックしたユーザを［{0}］に追加します",
	"msg_title": "メッセージコンソール",
	"lb_closeLink": "閉じる<<",
	"lb_initTab": "タブの構成を初期化する",
	"lb_weekdayWed": "水",
	"ms_overMaxIntValue": "最大値を超えています。最大値は2147483647です。",
	"lb_countryFI": "フィンランド",
	"lb_maximize": "最大化",
	"lb_setAuth": "認証情報セット",
	"lb_turnback": "元に戻す",
	"ms_passwordResetConfirm": "設定したパスワードは以下のURLで認証が失敗しましたが、設定しますか？",
	"lb_getCustomInfoonFailure1": "画面カスタマイズ情報の取得に失敗しました: {0} -- {1}",
	"lb_bracketClose": "[閉じる]",
	"lb_userID": "ユーザID",
	"lb_password": "パスワード",
	"ms_inputOverMaxValue": "設定できる最大値を超えています。{0}以下に設定してください。",
	"ms_urlEncodingFailed": "URLエンコーディング処理に失敗しました。 {0} : {1}({2})",
	"lb_reload": "再読み込み",
	"lb_filterDescSettingLink": "詳細な絞込み設定 >>",
	"ms_gtZeroOrAuto": "autoまたは0より大きな数値を入力してください。",
	"lb_countryRU": "ロシア",
	"ms_trashonException": "ごみ箱情報が取得できませんでした。{0}",
	"lb_deploy": "展開",
	"lb_widgetEditHelp": "ヘルプ",
	"lb_businessDate": "営業日",
	"ms_needsAuthentication": "ガジェットを最大化するためには認証情報を登録してください。",
	"lb_clearConfigurationDesc2": "カスタマイズ情報を初期化すると追加したタブとガジェットが全て削除されます。",
	"lb_widgetTitle_empty": "ガジェットタイトルを入力してください。",
	"lb_selectSubWidgetHeaderImage": "サブガジェットのヘッダの背景色を以下から選択してください。",
	"lb_countryNL": "オランダ",
	"lb_newTab": "新しいタブ",
	"ms_getdatafailure": "Error {0} -- {1}",
	"ms_clearTabConfigurationConfirm": "追加したガジェットを全て削除します、よろしいですか？\n(削除したガジェットはごみ箱に入ります)",
	"lb_canBeAddContents": "追加可能なコンテンツ",
	"lb_dateFilterInfo": "{0}のエントリー",
	"ms_customizeWidthByDrag": "ドラッグで幅を調整できます",
	"lb_cancel": "キャンセル",
	"lb_info": "情報",
	"lb_countryBR": "ブラジル",
	"lb_messageMore": "残りのメッセージを表示",
	"ms_autoReloadCancel": "ロード中のため自動リフレッシュをキャンセルします。{0}",
	"lb_addContents": "コンテンツの追加",
	"lb_change": "変更",
	"lb_resizeFontNormal": "文字サイズを標準にする",
	"lb_authInfo": "認証情報",
	"lb_langRU": "ロシア語",
	"ms_propertyLoadonFailure": "プロパティの読み込みに失敗しました。",
	"ms_noPermission": "読み込み権限がありません。",
	"lb_urlList": "URL一覧",
	"lb_belong": "所属",
	"ms_widgetonFailureAt": "{0}「{1}」でエラーが発生しました。{2} -- {3}",
	"lb_entry": "登録",
	"lb_name": "名前",
	"lb_siteMap": "サイトマップ",
	"lb_previewError": "プレビューを表示できません。",
	"lb_refreshMenu": "メニューの更新",
	"ms_custmizeFailedReload": "カスタマイズ情報の保存に失敗しました。ブラウザの再ロードを行います。",
	"ms_timeOut": "タイムアウトしました。",
	"ms_noURL": "リンク先のURLがありません",
	"ms_clearConfigurationConfirm": "追加したタブとガジェットを全て削除します、よろしいですか？\n(削除したガジェットはごみ箱に入ります)",
	"lb_changeColumn": "列数変更"
}
