var IS_R = {
	"ms_urlEncodeonExceptionAt": "Failed in the process of URL encording at {0}. {1} : {2}({3})",
	"lb_searchConfigOn10408": "Request timeout occurred while loading Search configuration file.",
	"lb_searchResultsOnNewWindow": "Display search results on new window.",
	"lb_langNL": "Dutch",
	"ms_userSearchonException": "The exception occured during user search.",
	"lb_1monthAgo": "One month ago",
	"lb_countryUK": "United Kingdom",
	"ms_menuLoadOnUnSuccess": "Failed to load menu. {0} -- {1}",
	"lb_countrySE": "Sweden",
	"lb_summaryAllView": "Summary display/Full display",
	"lb_newGroup": "New group",
	"ms_menuadded": "Menu [{0}] is added.",
	"lb_weekdaySun": "Sun",
	"lb_dateDisplay": "display/undisplay date desctiption",
	"lb_openSiteMap": "Open the side menu tab",
	"ms_propertyNotFound": "Property not found.",
	"ms_mergeCategoryError404": "{0} : No information to display found.",
	"ms_atompubPostonFauilure": "An error occurred at\"{0}\".\n{1} -- {2}\n{3}",
	"lb_titleEdit": "Title edit",
	"ms_menuNotFound2": "Cannot find the menu \"{0}\".",
	"lb_nextPage": "Next page",
	"lb_pageNum": "Page{0}",
	"ms_authServiceAccessFailed": "Failed to access the authentication service. Please contact the system administrator.",
	"ms_noInputComment": "Please enter a comment.",
	"lb_otherLayout": "Other Layout",
	"lb_sentMessageOfArticle": "Send a message about this article",
	"ms_customizeSavingonException": "Failed to save the customized information. {0}",
	"ms_invalidURL": "The URL is not valid.",
	"ms_notCoverage": "is not a search target.",
	"lb_gathering": "Combine",
	"lb_webSiteColon": "Web Site:",
	"lb_readingtimeout": "Request timeout occurred while loading data to display. This function is temporarily unavailable.",
	"lb_all": "ALL",
	"lb_shortcutsKeyList": "Shortcut key list",
	"ms_dragNoMerge": "RSS Gadget is not merged while pressing the CTRL key.",
	"ms_gadgetFuncNotFound": "The function named {1} does not exist in Gadget {0}.",
	"lb_add": "Add",
	"lb_countryMX": "Mexico",
	"ms_closeMySiteMap": "Close the my site map tab",
	"ms_selectSearchSite": "Please select at least one search site.",
	"lb_siteCategory": "by Site",
	"lb_refresh": "Refresh",
	"ms_reportfailure1": "The process of error report failed. {0} -- {1} : {2}({3})",
	"ms_validateError": "Failed in the process of validation. {0}",
	"ms_getdatafailed": "Failed to load the information to display. This system is not available temporarily.",
	"lb_maximizeShortcutsitemAndSummary": "(Item selected &amp; summary display)",
	"lb_previewScreen": "Confirm profile",
	"ms_invalidRssType": "Unsupported RSS format: {0}",
	"ms_trashContextExplanation": "Delete/Restore can be done by right-clicking.",
	"ms_thisIsFixedTab": "This tab is fixed. So you cannot custimze this.",
	"ms_invalidDateFormat": "Invalid date format specified.",
	"lb_countryUS": "United States",
	"lb_langPtBR": "Portuguese",
	"ms_mergeConfirm": "Are you sure you want to merge {1} with {0}?",
	"ms_searchEngineLoadon10408": "Request timeout occurred while accessing to search site \"{0}\".",
	"ms_up_update_from_default_by_admin": "UserPref {1} value has been changed to {2} from default value in {0} gadget by system administrator.",
	"ms_confirmDeleteUser": "Are you sure to delete the user?",
	"lb_toTopPage": "TopPage",
	"lb_countryNZ": "New Zealand",
	"lb_searchForm": "Search Form",
	"lb_erroronWidgetMove": "An error occurred during the process of moving gadget \"{0}\".",
	"lb_fullDisplay": "Full display",
	"lb_selectWallPaperImage": "Please select the image for wall paper.",
	"lb_familyName": "Last Name",
	"lb_default": "Default",
	"lb_invalidate": "Disable",
	"lb_setupAll": "Global settings",
	"lb_doNotMerge": "Do not merge ( return it )",
	"lb_noInfo": "No information to display.",
	"ms_up_update_by_admin": "UserPref {1} value has been changed to {3} from {2} in {0} gadget by system administrator.",
	"lb_dropAll": "Drop all",
	"ms_commandonException": "Command action failed. {0}",
	"lb_selectSearchSite": "Select Search Site",
	"ms_iCalNoPermission": "No permission to load calendar {0}.",
	"ms_deletaTabFailed": "Failed to delete tab \"{0}\".",
	"lb_comment": "Comment",
	"lb_displayAll": "Show all",
	"lb_reset": "reset",
	"lb_date": "Date",
	"ms_requiredItem": "is required item.",
	"lb_langES": "Spanish",
	"lb_today": "Today",
	"lb_warn": "Warning",
	"ms_inputTooLong": "The input string is too long. The length is up to {0} characters.",
	"lb_search": "Search",
	"lb_addTabLink": ">> Add a tab",
	"lb_searchConditionNotSet": "Search condition is not set.",
	"ms_mergeCategoryError10550": "{0} : Information cannot be parsed.",
	"lb_minute": ":",
	"lb_debug": "Debug",
	"ms_failedLoadIcons": "Failed to load gadget icons.",
	"lb_langKO": "Korean",
	"ms_customizeSavingFailure1": "Failed to save the customized information. {0}",
	"ms_urlEncodingUnsuccess": "Failed in the process of URL encoding. {0} : ({1})",
	"lb_freshdaysTerm": "Period of displaying new-arrival icon",
	"ms_targetGroupNotFound": "*There is no group to add users. Please create a group.",
	"lb_accessStatsTitle": "Access statistics",
	"lb_noEntry": "No entry",
	"lb_administrator": "Administrators",
	"lb_close": "Close",
	"ms_gatheringWidgets": "Combine these gadgets?",
	"ms_tabNameTooLong": "The tab name is too long.",
	"lb_searchOption": "Search options",
	"lb_setting": "Edit",
	"lb_changeColnumFailure": "Failed to change the column. column={0}, msg=[{1}]",
	"lb_doMerge": "Merge",
	"lb_userSearchNoResult": "No results matching your search were found.",
	"lb_added": "Added",
	"lb_getSystemMessageFailure": "Failed to get a system message.",
	"ms_widgetTitleEmpty": "Please specify the gadget title.",
	"lb_initialize": "Initialization",
	"ms_cacheDeleteFailure": "Failed to delete cache memory. {0} -- {1}",
	"lb_langIT": "Italian",
	"lb_credentialList": "Credential List",
	"lb_displayRSS": "Show RSS",
	"lb_transmission": "Send",
	"lb_addOtherWidget": "Add other gadgets",
	"lb_recentSixMonth": "Six month recently",
	"lb_weekdayTue": "Tue",
	"ms_previewMenuPath": "Belonging menu.",
	"ms_loadTimeout": "Request timeout occurred while loading.",
	"lb_descLink": "Detail>>",
	"ms_showTabByClick": "This tab is displayed when clicking.",
	"lb_lastmodified": "Last modified",
	"lb_keywordTooLong": "The search keyword is too long.",
	"ms_deleteTabConfirm": "Are you sure to delete \"{0}\" ?",
	"lb_showAllLatestItems": "Display all of new arrivals.",
	"ms_loadCancel": "Canceling the loading because of current loading. {0}",
	"lb_inspectionCount": "Subscribed",
	"lb_countryDE": "Germany",
	"lb_noCreator": "No author",
	"ms_sessionTimeoutReLogin": "Session closed. Please login again.",
	"ms_gtOneNum": "Enter a correct number of more than 1.",
	"lb_langJA": "Japanese",
	"lb_title": "Title",
	"lb_countryCA": "Canada",
	"lb_3DaysAgo": "Three days ago",
	"lb_hour": ":",
	"lb_addSchedule": "Add a new schedule",
	"ms_requiredItem2": "It is required item.",
	"lb_ranking": "Ranking",
	"lb_countryAU": "Australia",
	"lb_ref": "Reference",
	"ms_multiRssReaderDeleteSubcategory": "Category \"{1}\" of MultiRssReader \"{0}\" is deleted.",
	"ms_askToSystemManager": "Please contact the system administrator.",
	"ms_infoNotFoundAt": "{0} Cannot find information to display at \"{1}\".",
	"ms_invalidRegexp": "Invalid regexp specified.",
	"ms_inputTooLong2": "The input string is too long. The length is up to {0} characters in the alphanumeric character.\nWhen a multi byte character is included, the multi byte character is counted as about 3 characters.",
	"ms_urlGetInfoException1": "Failed to get information. Make sure that typed URL is correct. {0} -- {1}",
	"ms_rankingDurationFailed": "Cannot get the period of the Ranking \"{0}\". {1}",
	"lb_noDiplayItem": "There is no information to display.",
	"lb_gadget": "Gadget",
	"ms_changeToFixedTab": "The tab '{0}' was changed to fixed tab. All gadgets in the personalized area were put into the trash box.",
	"ms_showWidgetByClick": "This gadget is displayed when clicking.",
	"ms_closeGroupSelect": "Close the group edit.",
	"lb_next": "Next",
	"ms_searchEngineLoadonException": "An error occurred at the search site \"{0}\".{1}",
	"lb_countryIE": "Ireland",
	"ms_inputCredential": "Please input Credential.",
	"ms_widgetonExceptionAt": "{0}An error occurred at \"{1}\". {2} -- {3}",
	"lb_weekdayFri": "Fri",
	"lb_langZH": "Chinese",
	"lb_messageClose": "Close messages",
	"lb_countryCH": "Switzerland",
	"ms_menuNotFound": "Cannot find the menu.",
	"lb_span": "Period",
	"lb_generalSetting": "General settings",
	"lb_obstacleReort": "Error report",
	"lb_closeAll": "Close all",
	"ms_iCalLoadFailed": "Failed to load calendar. {0} : {1} -- {2}",
	"lb_clearConfigurationDesc1": "The portal screen is returned to default display.",
	"lb_searchConfigOn404": "Failed to load the search setting file. \nError 404: location \"{0}\" is not found.\n The settings of the server is not correct. Contact the System Manager.",
	"lb_refreshKey": "Refresh(R)",
	"ms_authFailure": "Authentication failed. Please input a valid user ID and password.",
	"ms_classNotFounf": "Cannot find the class {0}.",
	"lb_addContentsExGadget": "http://www.infoscoop.org/gadgets/hello.xml",
	"ms_stopRefresh": "The update is canceled.",
	"lb_logout": "Logout",
	"lb_mergeView": "Merge Display",
	"lb_countryDK": "Denmark",
	"lb_makeEffective": "enable",
	"lb_sendMail": "Send mail",
	"lb_creator": "Author",
	"ms_up_revert_by_admin": "{0} setting was changed by a administrator. UserPref {1} value was reverted to default value.",
	"lb_notGathering": "Separate",
	"lb_rssViewSetting": "RSS display settings",
	"lb_noNewInfo": "No new arrivals.",
	"lb_i18n": "I18N",
	"lb_preview": "Preview",
	"lb_notfound": "Cannot find information to display.",
	"lb_searchConfigException": "Failed to load the search setting file. The search settings is not correct. Contact the System Manager.\n{0}",
	"ms_commandonFailure": "Command action failed. {0} -- {1}",
	"ms_userSearchComplete": "Acquired the result of user search.",
	"lb_dateCategory": "by Date",
	"lb_summaryView": "Summary display",
	"lb_noDisplayFrameBorder": "No display frame border:",
	"ms_containerLoadon404": "Error 404: location \"{0} /widsrv \" is not found.",
	"lb_clearConfigurationButton": "Initialization of customized information",
	"ms_infosccopInitializing": "Now infoScoop is initializing.",
	"lb_notConfirm": "No further confirmation.",
	"lb_newBox": "New BOX",
	"lb_any": "{0}",
	"ms_pleaseTurnbackAndSetAuthInfo": "To read articles, turn back to normal size gadget and registor User ID and Password.",
	"ms_widgetBuildError": "An error occurred while creating a gadget.",
	"ms_updatePasswordError": "Failed to upadating password.",
	"lb_creatorFilterLabel": "Author whose name starts with \"{0}\"",
	"lb_resetColumnWidth": "Reset Column Width",
	"ms_sessionTimeout": "Session closed by unexpected reasons. Please login again.",
	"lb_lastAccessDate": "Last access date",
	"lb_proxy": "Proxy",
	"ms_rankingNoInfo": "Cannot find information to display in Ranking \"{0}\".",
	"lb_maximizeSendMail": "{0} %0D%0A%0D%0A {1}",
	"ms_rankingonException": "An error occurred at Ranking \"{0}\". {1}",
	"ms_invalidValue2": "Invalid value is typed. Please set again.",
	"lb_rankingUnit": "No.{0}&nbsp;",
	"ms_urlEncodeonFailureAt": "Failed in the process of URL encording at {0}. {1} -- {2} : {3}({4})",
	"lb_execute": "Execute",
	"ms_invalidIconType": "Invalid icon type is used at the header icon. {0}[type={1}",
	"lb_openNewWindow": "Open with new window",
	"ms_rssSearchFailure": "Failed to search RSS information.",
	"lb_creatorCategory": "by Author",
	"lb_langDE": "German",
	"lb_resizeFontSmaller": "Smaller font size",
	"lb_getCustomInfoonFailure2": "Failed to get information of screen customization. Please try later.",
	"ms_loadtimeoutAt": "Request timeout occurred while loading {0} \"{1}\" .",
	"lb_firstPage": "First Page",
	"lb_yesterday": "Yesterday",
	"ms_menuLoadonFailure": "Failed to load menu.",
	"lb_langFR": "French",
	"ms_duplicateGroupName": "The same group name already exists.",
	"ms_mergeCategoryError": "{0} : An error occurred.",
	"lb_defaultPanel": "Default Layout",
	"lb_langDA": "Danish",
	"lb_setupSchedule": "Setting schedule",
	"ms_iframeForbiddenURL": "Displaying the web site of {0} in portal innerframe is forbidden by administrator. It is displayed in a new window.",
	"lb_itemCount": "Total Articles: {0}",
	"lb_toOnlineManual": "To online manual page.",
	"ms_invalidFormat": "Please specify a valid format.",
	"lb_year": "/",
	"ms_iCalParseFailed": "Failed to analyse calendar. {0} : {1}",
	"ms_urlEncodingonException": "Failed in the process of URL encording. {0} -- {1} : {2}({3})",
	"lb_reportFailure": "Report was failed.",
	"ms_forbiddenurlPage": "Displaying this web site in portal innerframe is forbidden by administrator.",
	"lb_setupUnfinished": "A gadget is not displayed unless all of the required settings are done.",
	"ms_unsetting": "None setting.",
	"ms_RankingNoPermission": "You do not have permission to access the Ranking \"{0}\".",
	"lb_administration": "Administration",
	"lb_countryIN": "India",
	"lb_rename": "Rename",
	"ms_getResultFailureAt": "{0}Failed to get search results at \"{1}\".",
	"lb_widgetDesignSetting": "Gadget Design Setting",
	"lb_tab": "Tab",
	"ms_atompubPostonException": "An error occurred at\"{0}\".\n{1}\n{2}",
	"ms_selectProfile": "You must select a profile.",
	"ms_searchNotFound": "no results matching your search were found.",
	"lb_new": "New!!",
	"lb_sec": "-",
	"lb_type": "Type",
	"lb_low": "Low",
	"ms_invalidUsernameOrPassword": "The username or password you enterd is incorrect.",
	"lb_topMenu": "TopMenu",
	"ms_maximizeRefreshAfterTimeover": "start refresh on closing maximized gadget after auto refresh canceled by timeover",
	"lb_resetToDefaultSettings": "Reset to default",
	"ms_rssreaderUnreadable": "Unable to load settings of RssReader.",
	"lb_changeApply": "Apply changes",
	"ms_forbiddenURL": "The website of the input URL is forbidden by administrator.",
	"lb_bracketTrashEmptyAll": "[Empty the trash box]",
	"lb_prevPage": "Previous page",
	"ms_changeTabFailed": "Failed to change tab. {0}",
	"ms_doubleEntryFailure": "{0} is canceled because of the failure in second try.",
	"lb_userSearch": "User search",
	"lb_countryIT": "Italy",
	"ms_rankingTimeout": "Request timeout occurred while loading Ranking of {0}.",
	"ms_logofftimeSavingfailure": "Logoff process failed. {0}",
	"lb_addContentsExWebSite": "http://www.infoscoop.org/index.php",
	"ms_widgetBkgcolorError": "{0}An error occurred at \"{1}\".Failed to set up the back-ground-color.",
	"lb_userNotAddedGroup": "No user is added to this group.",
	"lb_langEN": "English",
	"lb_urlExample": "Example of input URL",
	"ms_sorry": "We're sorry...",
	"ms_gtZeroNum": "Enter a correct number of more than 0.",
	"lb_notitle": "No title",
	"ms_urlNoInput": "Please enter URL.",
	"ms_urlTooLong": "URL is too long. The length of URL is up to 2000 characters in the alphanumeric character.\nWhen the multi byte character is included, the multi byte character is counted as about 9 characters.",
	"ms_noPermissionAt": "{0}You do not have permission to access the \"{1}\".",
	"ms_getRssInfoonException": "Failed to get RSS information. Make sure that the typed URL is correct. {0} -- {1}",
	"lb_searchUser": "Search and display calendar",
	"lb_saveSettings": "Save settings",
	"ms_searchEngineLoadonFailure": "An error occurred at the search site \"{0}\".{1} -- {2}",
	"ms_getRssInfoonFailure": "Failed to get RSS information. Make sure that the typed URL is correct.",
	"lb_searchCondition": "Set search condition",
	"ms_erroronSubWidgetMove": "An error occurred during the process of moving sub-category \"{0}\".",
	"ms_noInputPassword": "No password specified.",
	"ms_menuLoadon10408": "Request timeout occurred while loading Menu.",
	"ms_getInfoFailureAt": "{0} Failed to get detailed information at \"{1}\".",
	"ms_clearConfigurationFailed": "Failed in the initialization of customized information.",
	"lb_high": "High",
	"lb_widget": "Gadget",
	"lb_1weekAgo": "One week ago",
	"lb_addContentsExRSS": "http://www.infoscoop.org/index.php/en/news.feed",
	"lb_showHelp": "Display help",
	"lb_wallPaperSetting": "Wall Paper Setting",
	"lb_addUser": "Add User",
	"ms_getRssInfoonUnsccess": "Failed to get RSS information. Make sure that the typed URL is correct. {0}",
	"lb_month": "/",
	"lb_openMySiteMap": "Open the my site map tab",
	"lb_maximizeShortcutsItemAndFull": "(Item selected &amp; full display)",
	"lb_endOfUserSearch": "Close user search form",
	"lb_containerLoadonException": "Failed to compose screen. : {0}",
	"lb_mySiteMap": "My sitemap",
	"ms_errorSetAuthInfo": "Failed to authenticate User ID or Password you entered. The User ID and Password were not updated.",
	"ms_lastlogoutSavingfailure": "Customized information at the last logout is not saved.",
	"ms_duplicateProfile": "Profiles are duplicated.",
	"ms_inputURL": "Please enter URL.",
	"lb_closeAddContents": "Close add contents tab",
	"lb_addRssFeed": "Add an RSS feed",
	"ms_minimizeFailure": "Failed in minimizing process of {0}.: {1}",
	"ms_maximizeCloseRefresh": "start refresh on closing maximized gadget",
	"lb_illegalToolbarItem": "It is an invalid toolbar item. Uncertain type [{0}]",
	"lb_editGroup": "Group edit",
	"lb_error": "Error",
	"lb_sendMailTitle": "%81u{0}%81v%82%CC%82%B2%8F%D0%89%EE",
	"lb_containerLoginonException": "Failed to compose screen. There might be some errors occurred at the customized information data. Contact the systems manager.",
	"ms_userIdEmpty": "Please enter User ID.",
	"lb_countryES": "Spain",
	"ms_tabsRefresh": "Gadgets arranged in all tabs is renewed.",
	"lb_langNO": "Norwegian",
	"ms_iCalCreateFailed": "Failed to create calendar. {0}",
	"lb_countOneDay": "During a day",
	"ms_datecreatorChangeFailed": "Failed to change the Show/Hide setting of Date/Author of {0}: {1}",
	"lb_delete": "Delete",
	"ms_lineChangeFailure": "Changing the paragraph setting of {0} failed.: {1}",
	"lb_turnbackMaximize": "Back",
	"lb_org": "Organization",
	"lb_prev": "Previous",
	"ms_confirmDeleteGroup": "Are you sure to delete the group?",
	"lb_noInfoOnMaximize": "There is no information that can be displayed by maximization.",
	"ms_widgeTitleTooLong": "The number of characters for the gadget title is exceeded.",
	"ms_inputTxtBox": "Please enter text into the textbox.",
	"ms_shortcutsNotice": "-",
	"lb_trashBox": "Trash Box",
	"lb_recentOneWeek": "One week recently",
	"lb_authType": "Authentication Type",
	"ms_widgetDuplicateWarn": "The gadget cannot be added because the same gadget already exists. ({0})",
	"ms_RankingCriticalerror": "An error occurred.<br/>{0}<br/>This gadget is not available for now.",
	"lb_mail": "Mail",
	"ms_onSheetReaderSSOonException": "The process of OnSheet Single Sign-On failed. {0}",
	"lb_deployAll": "Open all",
	"lb_detailAndBlank": "Detail&nbsp;&nbsp;",
	"lb_widgetTitle": "Gadget title",
	"ms_loginFailed": "Failed to log in.",
	"lb_selectWidgetHeaderImage": "Please select the image for background of gadget header.",
	"ms_failedCheckCharLength": "Failed to check the length of input strings.",
	"ms_invalidCharset": "Invalid character set specified.",
	"ms_customizeDeleteonFailure": "Failed to delete the customized information. {0} -- {1}",
	"lb_noMessage": "There is no message.",
	"lb_countryNO": "Norway",
	"lb_saveFilterSetting": "Filter conditions except for [Date] are to be saved as setting of RSS reader.",
	"ms_getRssInfoTimeout": "Request timeout occurred while loading RSS data.",
	"ms_getdataerror404": "Error 404: location {0} is not found.",
	"ms_customizeDeleteonException": "Failed to delete the customized information. {0}",
	"lb_countryFR": "France",
	"lb_select": "Select",
	"ms_toggleEditElementByClick": "It is changed into the form that edits the content of {0} element if it is clicked.",
	"lb_weekdaySat": "Sat",
	"ms_widgetonExceptionNotAvailableAt": "{0}An error occurred at \"{1}\"<br/>{2}<br/>This gadget is not available for now.",
	"lb_openMenu": "Show Menu",
	"lb_saveLoginState": "Stay logged in",
	"ms_noRssInfo": "No Rss feed found at this site.",
	"lb_doubleAdd": "The selected gadget is already added.",
	"ms_atomRegetonException": "Failed to get this Atom.\n{0}",
	"lb_messageConsole": "Message Console",
	"ms_selectValidProfile": "Select a valid profile.",
	"ms_emptyAt": "Need to input into {0}.",
	"ms_mergeCategoryError10408": "{0} : Request timeout occurred while loading.",
	"lb_adminLink": "To Management Page",
	"ms_inputTitle": "Please input the title.",
	"lb_countryCN": "China",
	"lb_getCustomInfoon404": "Failed to get the information of screen customization. The settings of the server is not correct. Contact the Systems Manager.",
	"ms_invalidWidget": "This gadget is not available for now.",
	"lb_category": "Category",
	"lb_deleteDate": "Deleted date",
	"lb_day": "-",
	"lb_forbiddenURL": "Forbidden URL",
	"ms_invalidOldPassword": "The old password is wrong.",
	"lb_changePassword": "Change password",
	"lb_langFI": "Finnish",
	"ms_oauthFailed": "Authorization failed",
	"ms_getSearchResultFailure": "Failed to get search results.",
	"ms_configNotFound": "The conposed file of {0} does not exist.",
	"ms_searchEngineLoadon404": "Could not find any information to show in the search site \"{0}\".",
	"lb_edit": "Edit",
	"lb_loginTitle": "login",
	"lb_closeSitemap": "Close the side menu tab",
	"lb_newpass": "New password",
	"lb_toLogin": "to login page",
	"lb_middle": "Medium",
	"lb_minimize": "Minimize",
	"ms_trashLoadonFailure": "Failed to get Trash Bin information. {0} -- {1}",
	"lb_mergeConfirmDialog": "Gadget merge confirmation dialog",
	"lb_groupList": "A list of the groups",
	"lb_noDate": "No date",
	"lb_scheduleMonthFormat": "yyyy/M",
	"lb_weekdayThu": "Thu",
	"ms_revertWidget": "It is added to tab \"{0}\". It returns when clicking.",
	"lb_gadgetColon": "Gadget:",
	"ms_cannotAddGadgetToThisTab": "You cannot add any gadgets to this tab.",
	"lb_rssColon": "RSS:",
	"lb_deleteUser": "Delete User",
	"lb_enableRoundCorner": "Round a corner of gadgets:",
	"ms_menuIconException": "An error occurred at icon display settings in menu \"{0}\".:{1}",
	"lb_countryJP": "Japan",
	"ms_errorOnWindowResize": "An error occurred during resizing window.: {0}",
	"lb_weekdayMon": "Mon",
	"lb_addWebPage": "Add a Web page",
	"lb_resizeFontLarger": "Larger font size",
	"ms_customizeSavingFailure2": "Failed to save the customized information. {0} -- {1}",
	"lb_nationalHoliday": "Holiday",
	"ms_clearConfigurationForceReload": "Going to reload as customized information was initialized.",
	"ms_onSheetReaderSSOonFailure": "The process of OnSheet Single Sign-On failed. {0} -- {1}",
	"lb_langSV": "Swedish",
	"lb_browserNotSupported": "The current browser is not supported.",
	"ms_mergeCategoryError403": "{0} : You do not have permission to access the site.",
	"lb_addGroup": "Add a Group",
	"ms_iCalLoadTimeout": "Request timeout occurred while loading Calendar. {0}",
	"lb_changeNotApply": "Not change",
	"lb_showRssInSite": "To show RSS files in this site:<br/>&nbsp;&nbsp;http://www.nikkeibp.co.jp/",
	"ms_noInputDestination": "Please input an address.",
	"lb_pageTop": "Top page",
	"ms_menuLoadonException": "Failed to load menu. {0}",
	"lb_countryKR": "Korea",
	"lb_openAddContents": "Open the add contents tab",
	"ms_addCheckedUser": "*Add checked User(s) to [{0}].",
	"msg_title": "Message Console",
	"lb_closeLink": "Close<<",
	"lb_initTab": "Initialize tab content",
	"lb_reportFinished": "Reported.",
	"lb_weekdayWed": "Wed",
	"lb_searchConfigOnFailure": "Failed to load the search setting file. {0} --  {1}",
	"ms_overMaxIntValue": "The input value exceeds the maximum. Max value is 2147483647.",
	"ms_teleconSetupRequire": "Initial setting is necessary to use this gadget.<br/>Please enter a word to look up.",
	"lb_lastPage": "Last Page",
	"ms_enrtyNotFound": "{0} is not found.",
	"ms_urlGetInfoException2": "Failed to get information. Make sure that typed URL is correct. {0}",
	"ms_customizeSaved": "Saved the information to customize.",
	"lb_login": "Login",
	"lb_countryFI": "Finland",
	"ms_on10998": "infoScoop is started in another browser. Updated information on this browser is not sended to the server.",
	"lb_maximize": "Maximize",
	"lb_oldPassword": "Old password",
	"lb_setAuth": "Authentication Setting",
	"ms_menuMoveonError": "An error occurred during movement process of menu \"{0}\".",
	"lb_turnback": "Restore",
	"lb_urlDirectInput": "Examples of how to use<br/>Direct input of URL: <br/>&nbsp;&nbsp;http://www.nikkeibp.co.jp/index.rdf",
	"ms_passwordResetConfirm": "The password authentication failed at the URL below. Do you really want to set the password?",
	"lb_nextPageLink": "Next page >>",
	"lb_getCustomInfoonFailure1": "Failed to get information of screen customization.: {0} -- {1}",
	"lb_bracketClose": "[Close]",
	"lb_userID": "User ID",
	"lb_password": "Password",
	"lb_holiday": "Holiday",
	"ms_duplicateDeleteConfirm": "\"{0}\" already exists in the tab \"{1}\".\n Do you want to delete the gadget from \"{2}\"?",
	"lb_relogin": "Relogin",
	"ms_authServiceNotWork": "The authentication service doesn't work properly.",
	"ms_inputOverMaxValue": "The input value is too large. Set the value lower than {0}.",
	"ms_changePasswordFailed": "Failed to change password.",
	"ms_invalidValue": "Invalid value specified",
	"lb_searchResult": "Search Results",
	"ms_urlEncodingFailed": "Failed in the process of URL encording. {0} : {1}({2})",
	"lb_reload": "Refresh",
	"lb_filterDescSettingLink": "Filter setting >>",
	"ms_gtZeroOrAuto": "Please enter \"auto\" or numerical value more than 0.",
	"ms_passwordChanged": "The password was changed.",
	"lb_countryRU": "Russia",
	"ms_trashonException": "Failed to get Trash Bin information. {0}",
	"lb_deploy": "Expand",
	"ms_rssSearchTimeout": "Request timeout occurred while searching RSS information.",
	"lb_widgetEditHelp": "Help",
	"lb_eMail": "E-Mail",
	"lb_businessDate": "Buisiness date",
	"ms_needsAuthentication": "Please register authentication information to maximize gadget.",
	"lb_menu": "Menu",
	"lb_clearConfigurationDesc2": "When customized information is initialized, all of added gadgets and tabs are deleted.",
	"lb_widgetTitle_empty": "Please specify the gadget title.",
	"lb_prevItem": "Previous item",
	"lb_changePass": "Change password",
	"lb_selectSubWidgetHeaderImage": "Please select the background color of sub gadget header.",
	"messsage_invalidDefaultValue": "Invalid initial value is set. : {0} UserPref[@name={1}]",
	"lb_countryNL": "Netherlands",
	"lb_newTab": "new tab",
	"lb_countDown": "until time to {0}",
	"lb_recentOneMonth": "One month recently",
	"lb_property": "Properties",
	"ms_getdatafailure": "Error {0} -- {1}",
	"ms_clearTabConfigurationConfirm": "Are you sure to delete all of added gadgets?\n (The deleted gadgets goes into trash bin).",
	"lb_canBeAddContents": "Widgets that can be added",
	"lb_dateFilterInfo": "Entry for {0}",
	"ms_customizeWidthByDrag": "Drag to control width.",
	"lb_cancel": "Cancel",
	"lb_loading": "Loading...",
	"ms_rankingonFailure": "An error occurred at Ranking \"{0}\". {1} -- {2}",
	"lb_info": "Information",
	"ms_gadgetError": "An error occurred in gadget {0}.",
	"lb_countryBR": "Brazil",
	"ms_title_update_by_admin": "Title of {0} was changed to {1} by system administrator.",
	"ms_refferenceAt": "is a reference.",
	"lb_messageMore": "Show more messages",
	"ms_autoReloadCancel": "Auto reload is canceled because of being in loading process. Cancled the auto reload because of loading.{0}",
	"lb_addContents": "Add a gadget",
	"lb_change": "change",
	"ms_noPermission401": "Eenter User ID and Password.",
	"lb_resizeFontNormal": "Medium font size",
	"ms_sessionTimeoutByOtherLogin": "The session timeout. <br/>Also, it is possible to be logged in with another browser. <br/>Please log in again.",
	"lb_authInfo": "Credential",
	"lb_langRU": "Russian",
	"ms_propertyLoadonFailure": "Failed to load properties.",
	"lb_nextItem": "Next item",
	"lb_editSummary": "Edit Summary",
	"ms_noPermission": "You do not have permission to access the site.",
	"lb_urlList": "URL list",
	"lb_editDesc": "Edit description",
	"lb_belong": "Division",
	"ms_widgetonFailureAt": "{0}An error occurred at \"{1}\". {2}",
	"lb_entry": "Submit",
	"lb_name": "Name",
	"lb_attention": "*",
	"lb_here": "Here",
	"lb_releaseMaximize": "Maximization release",
	"lb_siteMap": "SiteMap",
	"lb_previewError": "The preview cannot be displayed",
	"lb_refreshMenu": "Update menu",
	"ms_reportfailure2": "The process of error report failed. {0}",
	"ms_custmizeFailedReload": "Failed to save the customized information. This browser will be reloaded.",
	"ms_timeAlert": "It is time of the \"{0}\"",
	"ms_timeOut": "A timeout occurred",
	"ms_noURL": "No URL to link to.",
	"ms_searchNotAvailable": "Failed to load the search settings. So now the search function is unavailable.",
	"ms_clearConfigurationConfirm": "Are you sure to delete all of added gadgets and tabs?\n (The deleted gadgets goes into trash bin).",
	"ms_atomRegetFailure": "Failed to get this Atom.\n{0} -- {1}",
	"lb_changeColumn": "Change the number of Columns"
}
