var IS_R = {
	"lb_langNL": "荷兰语",
	"ms_userSearchonException": "用户搜索发生例外。",
	"lb_1monthAgo": "一个月前",
	"lb_countryUK": "英国",
	"ms_menuLoadOnUnSuccess": "菜单读取失败。 {0} -- {1}",
	"lb_countrySE": "瑞典",
	"lb_newGroup": "新的组",
	"ms_menuadded": "追加了菜单[{0}]。",
	"lb_weekdaySun": "周日",
	"lb_openSiteMap": "打开侧栏菜单",
	"ms_propertyNotFound": "找不到属性。",
	"ms_mergeCategoryError404": "{0} : 未找到要表示的信息。",
	"ms_menuNotFound2": "未找到菜单「{0}」。",
	"ms_invalidURL": "不是有效的ＵＲＬ",
	"lb_gathering": "归纳",
	"lb_webSiteColon": "网页:",
	"lb_all": "所有",
	"ms_dragNoMerge": "一直压下Ctrl键，RSS阅读器之间不能进行归并。",
	"lb_add": "追加",
	"lb_countryMX": "墨西哥",
	"ms_closeMySiteMap": "关闭网站地图",
	"lb_refresh": "更新",
	"ms_validateError": "验证检验失败。{0}",
	"ms_getdatafailed": "没有取得数据。",
	"ms_trashContextExplanation": "右击鼠标可以[还原]/[删除]。",
	"ms_thisIsFixedTab": "这个标签是固定标签。不能自定义。",
	"ms_invalidDateFormat": "不正确日期格式。",
	"lb_countryUS": "美国",
	"lb_langPtBR": "葡萄牙语",
	"ms_mergeConfirm": "把「{1}」归并到「{0}」上吗？",
	"ms_confirmDeleteUser": "可以删除用户吗？",
	"lb_toTopPage": "首页",
	"lb_countryNZ": "新西兰",
	"lb_selectWallPaperImage": "请从以下选择壁纸设定画像。",
	"lb_default": "默认",
	"lb_invalidate": "设为无效",
	"lb_setupAll": "全体设定",
	"lb_doNotMerge": "不合并（返回）",
	"lb_noInfo": "没有可能表示的信息。",
	"lb_dropAll": "一并向下拖放",
	"ms_commandonException": "命令的执行失败。 {0}",
	"ms_iCalNoPermission": "没有读取日历「{0}」的权限。",
	"ms_deletaTabFailed": "栏标「{0}」删除失败。",
	"lb_displayAll": "全部表示",
	"lb_reset": "重置",
	"lb_date": "日期",
	"ms_requiredItem": "是必须项目",
	"lb_langES": "西班牙语",
	"lb_today": "今天",
	"lb_warn": "警告",
	"ms_inputTooLong": "输入的字符串过长。请限定在{0}文字以下。",
	"lb_search": "搜索",
	"lb_addTabLink": ">>追加栏标",
	"lb_searchConditionNotSet": "未设定搜索条件。",
	"ms_mergeCategoryError10550": "{0} : 不能解析信息。",
	"lb_debug": "调试",
	"ms_failedLoadIcons": "小工具图标读取失败。",
	"lb_langKO": "韩语",
	"ms_customizeSavingFailure1": "自定义信息保存失败。{0}",
	"lb_freshdaysTerm": "新到图标的表示期限",
	"ms_targetGroupNotFound": "※没有可追加用户的组。请创建组。",
	"lb_close": "关闭",
	"ms_gatheringWidgets": "归纳一下小工具。",
	"lb_setting": "设定",
	"lb_changeColnumFailure": "列变更失败。column={0}, msg=[{1}]",
	"lb_doMerge": "合并",
	"lb_userSearchNoResult": "搜索结果为0件。",
	"lb_added": "追加完毕",
	"lb_initialize": "初始化",
	"ms_cacheDeleteFailure": "缓存删除失败。 {0} -- {1}",
	"lb_langIT": "意大利语",
	"lb_credentialList": "认证信息一览",
	"lb_displayRSS": "表示RSS",
	"lb_weekdayTue": "周二",
	"ms_previewMenuPath": "在菜单中设定。",
	"ms_loadTimeout": "读取超时。",
	"lb_descLink": "详细>>",
	"ms_showTabByClick": "点击时表示这个标签",
	"ms_cannotDeleteLastTab": "You must have one tab at least.",
	"ms_deleteTabConfirm": "「删除{0}」。可以吗？",
	"lb_showAllLatestItems": "表示新到信息",
	"ms_loadCancel": "正在下载中，取消下载。{0}",
	"lb_countryDE": "德国",
	"ms_sessionTimeoutReLogin": "Session中断。请再登录。",
	"ms_gtOneNum": "输入1以上的适当数字。",
	"lb_langJA": "日语",
	"lb_title": "标题",
	"lb_countryCA": "加拿大",
	"lb_3DaysAgo": "三天前",
	"ms_requiredItem2": "是必须项目",
	"lb_countryAU": "澳大利亚",
	"lb_ref": "浏览",
	"ms_multiRssReaderDeleteSubcategory": "MultiRssReader「{0}」类别「{1}」被删除。",
	"ms_infoNotFoundAt": "未找到{0}「{1}」中表示的信息。",
	"ms_invalidRegexp": "不正确的正规表示。",
	"ms_inputTooLong2": "输入的字符串过长。用半角英文字母{0}文字可以输入。\n全角文字包含在内时全角文字算做约3个文字。",
	"ms_urlGetInfoException1": "获取信息失败。请确认输入的URL是否有错。{0} -- {1}",
	"lb_noDiplayItem": "没有表示的信息。",
	"lb_gadget": "小工具",
	"ms_changeToFixedTab": "标签'{0}'被变更成为固定标签。 所有的个性化领域的小工具被收集到了回收站。",
	"ms_showWidgetByClick": "点击表示这个小工具",
	"lb_countryIE": "爱尔兰",
	"ms_inputCredential": "请输入认证信息。",
	"ms_widgetonExceptionAt": "{0}「{1}」上发生错误。{2}",
	"lb_weekdayFri": "周五",
	"lb_langZH": "中国语",
	"lb_messageClose": "关闭消息",
	"lb_countryCH": "瑞士",
	"ms_menuNotFound": "未找到菜单。",
	"lb_generalSetting": "一般设定",
	"lb_closeAll": "全部关闭",
	"ms_iCalLoadFailed": "日历的读取失败。 {0} : {1} -- {2}",
	"lb_clearConfigurationDesc1": "把门户画面恢复到初始画面。",
	"lb_refreshKey": "更新(R)",
	"ms_authFailure": "认证失败。请输入正确的用户名/密码。",
	"ms_classNotFounf": "看不到类{0。",
	"lb_addContentsExGadget": "http://www.infoscoop.org/gadgets/hello.xml",
	"ms_stopRefresh": "中止更新",
	"lb_logout": "退出",
	"lb_mergeView": "一揽子表示",
	"lb_countryDK": "丹麦",
	"lb_makeEffective": "设为有效",
	"lb_sendMail": "邮件发送",
	"lb_creator": "作者",
	"lb_notGathering": "不归纳",
	"lb_rssViewSetting": "RSS表示设定",
	"lb_noNewInfo": "没有新到的信息。",
	"lb_preview": "预览",
	"lb_notfound": "没有要表示的消息。",
	"ms_commandonFailure": "命令的执行失败。 {0} -- {1}",
	"ms_userSearchComplete": "获得用户搜索结果。",
	"lb_noDisplayFrameBorder": "不显示小工具的框：",
	"ms_containerLoadon404": "Error 404: location \"{0} /widsrv \" is not found.",
	"lb_clearConfigurationButton": "自定义信息的初始化",
	"ms_infosccopInitializing": "infoScoop在初始化。",
	"lb_notConfirm": "今后不确认",
	"lb_newBox": "新BOX",
	"lb_any": "{0}",
	"ms_pleaseTurnbackAndSetAuthInfo": "为参照消息，请解除最大化并登录认证信息。",
	"ms_widgetBuildError": "小工具制作中发生错误。",
	"ms_updatePasswordError": "密码更新失败。",
	"lb_resetColumnWidth": "统一列的幅度",
	"ms_sessionTimeout": "因不明原因Session中断。请再登录。",
	"lb_maximizeSendMail": "{0} %0D%0A%0D%0A {1}",
	"ms_invalidIconType": "在使用无效的表头图标。{0}[type={1}",
	"lb_langDE": "德语",
	"lb_resizeFontSmaller": "缩小字符尺寸",
	"lb_getCustomInfoonFailure2": "未能取得画面自定义信息。请稍后继续登录。",
	"ms_loadtimeoutAt": "在{0}「{1}」读取超时。",
	"lb_yesterday": "昨天",
	"ms_menuLoadonFailure": "菜单读取失败。",
	"lb_langFR": "法语",
	"ms_mergeCategoryError": "{0} : 发生错误。",
	"lb_langDA": "丹麦语",
	"ms_iframeForbiddenURL": "网站「{0}」由于管理员限制了门户内的表示，所以不能表示新的窗口。",
	"lb_itemCount": "文章数: {0}件",
	"ms_invalidFormat": "请指定正确的格式。",
	"ms_iCalParseFailed": "日历解析失败。 {0} : {1}",
	"ms_urlEncodingonException": "URL编码处理失败。 {0} -- {1} : {2}({3})",
	"lb_setupUnfinished": "小工具在所有设定完成之前不能表示。",
	"lb_countryIN": "印度",
	"lb_rename": "名称变更",
	"lb_widgetDesignSetting": "小工具的设计设定",
	"lb_new": "New!!",
	"lb_type": "类型",
	"lb_topMenu": "顶部菜单",
	"ms_rssreaderUnreadable": "不能读取RssReader设定。",
	"lb_changeApply": "适用变更",
	"ms_forbiddenURL": "输入的URL网站由于管理员的限制而不能阅览。",
	"lb_bracketTrashEmptyAll": "[清空回收站]",
	"ms_changeTabFailed": "栏标切换失败。{0}",
	"ms_doubleEntryFailure": "{0}由于第二次执行失败，被废弃。",
	"lb_userSearch": "用户搜索",
	"lb_countryIT": "意大利",
	"ms_logofftimeSavingfailure": "退出处理失败。{0}",
	"lb_addContentsExWebSite": "http://www.infoscoop.org/index.php/ja/",
	"ms_widgetBkgcolorError": "{0}「{1}」上发生错误。背景颜色不能设定。",
	"lb_userNotAddedGroup": "该组中用户没有追加。",
	"lb_langEN": "英语",
	"lb_urlExample": "URL输入示例",
	"ms_gtZeroNum": "输入0以上的适当数字。",
	"lb_notitle": "没有标题",
	"ms_urlNoInput": "请输入URL。",
	"ms_urlTooLong": "URL 过长。URL的长度在半角拉丁数字2000字以下。如果含有\n全角文字时全角文字被数为约9个文字。",
	"ms_noPermissionAt": "没有{0}「{1}」的读取权限。",
	"lb_searchCondition": "搜索条件",
	"ms_menuLoadon10408": "菜单的读取超时",
	"ms_clearConfigurationFailed": "自定义信息的初始化失败",
	"lb_widget": "小工具",
	"lb_1weekAgo": "一周前",
	"lb_addContentsExRSS": "http://www.infoscoop.org/index.php/ja/news.feed",
	"lb_wallPaperSetting": "壁纸设定",
	"lb_addUser": "追加用户",
	"lb_openMySiteMap": "打开我的网站地图",
	"lb_containerLoadonException": "未能构成画面: {0}",
	"ms_errorSetAuthInfo": "输入的用户名/密码的认证失败。用户名D/密码未能更新。",
	"ms_lastlogoutSavingfailure": "上次退出时的客户自定义信息没有保存。",
	"ms_inputURL": "请输入URL。",
	"lb_closeAddContents": "关闭内容追加",
	"ms_minimizeFailure": "{0}最小化失败: {1}",
	"lb_illegalToolbarItem": "不正确的工具栏窗标。不明的种类 [{0}]",
	"lb_editGroup": "组的编辑",
	"lb_error": "错误",
	"lb_sendMailTitle": "[{0}]{1}",
	"lb_containerLoginonException": "未能构成画面。自定义信息的数据可能出现不整合。请向系统管理员询问。",
	"ms_userIdEmpty": "请输入用户名。",
	"lb_countryES": "西班牙",
	"lb_langNO": "挪威语",
	"ms_iCalCreateFailed": "日历的生成失败。 {0}",
	"ms_datecreatorChangeFailed": "{0}的日期/作者的表示/非表示设定的变更失败: {1}",
	"lb_delete": "删除",
	"ms_lineChangeFailure": "{0}的改行设定变更失败: {1}",
	"lb_turnbackMaximize": "还原",
	"lb_prev": "向前",
	"ms_confirmDeleteGroup": "删除组，可以吗？",
	"lb_noInfoOnMaximize": "最大化中没有可表示的信息。",
	"lb_trashBox": "回收站",
	"lb_authType": "认证类型",
	"ms_widgetDuplicateWarn": "同一小工具已经存在，不能追加。({0})",
	"lb_mail": "邮件",
	"lb_deployAll": "全部展开",
	"lb_widgetTitle": "小工具标题",
	"lb_selectWidgetHeaderImage": "请从下面选择小工具的头的背景使用的画像。",
	"ms_failedCheckCharLength": "输入文字列的长度检查失败。",
	"ms_invalidCharset": "不正确编码。",
	"lb_countryNO": "挪威",
	"lb_saveFilterSetting": "[日期]以外的缩小项目作为RSS前导字符被保存。",
	"ms_getdataerror404": "错误 404: 没有找到区域 {0}.",
	"lb_countryFR": "法国",
	"lb_select": "选择",
	"lb_weekdaySat": "周六",
	"lb_openMenu": "打开菜单",
	"lb_doubleAdd": "选择的小工具已经追加。",
	"lb_messageConsole": "消息控制",
	"ms_emptyAt": "{0}未输入。",
	"ms_mergeCategoryError10408": "{0} : 读取超时。",
	"lb_adminLink": "至管理画面",
	"lb_countryCN": "中国",
	"lb_getCustomInfoon404": "未能取得画面自定义信息。服务器设定有误。请向系统管理员询问。",
	"ms_invalidWidget": "该小工具现在不能使用。",
	"lb_category": "类别",
	"lb_deleteDate": "删除日",
	"lb_langFI": "芬兰语",
	"ms_configNotFound": "{0}构成文件不存在。",
	"lb_edit": "编辑",
	"lb_closeSitemap": "关闭侧栏菜单",
	"lb_minimize": "最小化",
	"ms_trashLoadonFailure": "无法取得回收站信息。{0} -- {1}",
	"lb_mergeConfirmDialog": "小工具确认对话",
	"lb_scheduleMonthFormat": "yyyy年 M月",
	"lb_weekdayThu": "周四",
	"ms_revertWidget": "追加到标签{0}」。鼠标点击后返回。",
	"lb_gadgetColon": "小工具:",
	"ms_cannotAddGadgetToThisTab": "不能对这个标签追加小工具。",
	"lb_rssColon": "RSS:",
	"lb_deleteUser": "删除用户",
	"lb_enableRoundCorner": "小工具的边角弄成圆的：",
	"ms_menuIconException": "菜单「{0}」的图标表示设定发生错误：{1}",
	"lb_countryJP": "日本",
	"ms_errorOnWindowResize": "ウィンドウリサイズ時の処理でエラーが発生しました: {0}",
	"lb_weekdayMon": "周一",
	"lb_resizeFontLarger": "扩大字符尺寸",
	"ms_clearConfigurationForceReload": "由于自定义信息已被初始化，进行重载。",
	"lb_langSV": "瑞典语",
	"ms_mergeCategoryError403": "{0} : 没有读取权限。",
	"lb_addGroup": "组追加",
	"ms_iCalLoadTimeout": "日历读取已超时。 {0}",
	"lb_changeNotApply": "不变更",
	"ms_menuLoadonException": "菜单读取失败。{0}",
	"lb_countryKR": "韩国",
	"lb_openAddContents": "打开内容追加",
	"ms_addCheckedUser": "※把选择的用户追加到［{0}］上",
	"msg_title": "消息控制台",
	"lb_closeLink": "关闭<<",
	"lb_initTab": "初始化标签的构成",
	"lb_weekdayWed": "周三",
	"ms_overMaxIntValue": "超过最大值。最大值为2147483647。",
	"lb_countryFI": "芬兰",
	"lb_maximize": "最大化",
	"lb_setAuth": "认证信息设定",
	"lb_turnback": "还原",
	"ms_passwordResetConfirm": "设定的密码在以下的URL上认证失败，要设定吗？",
	"lb_getCustomInfoonFailure1": "未能取得画面自定义信息。: {0} -- {1}",
	"lb_bracketClose": "[关闭]",
	"lb_userID": "用户名",
	"lb_password": "密码",
	"ms_inputOverMaxValue": "超过限定最大数。请设定在{0}以下。",
	"ms_urlEncodingFailed": "URL编码处理失败。 {0} : {1}({2})",
	"lb_reload": "再读",
	"lb_filterDescSettingLink": "详细的缩小设定 >>",
	"ms_gtZeroOrAuto": "请输入auto或大于0的数字。",
	"lb_countryRU": "俄罗斯",
	"ms_trashonException": "无法取得回收站信息。{0}",
	"lb_deploy": "展开",
	"lb_widgetEditHelp": "帮助",
	"lb_businessDate": "工作日",
	"ms_needsAuthentication": "为了把小工具最大化，请登录认证信息。",
	"lb_clearConfigurationDesc2": "如果自定义信息初始化的话，追加的标签和小工具将全部被删除。",
	"lb_widgetTitle_empty": "请输入小工具标题。",
	"lb_selectSubWidgetHeaderImage": "请从以下选择副小工具的头的背景色。",
	"lb_countryNL": "荷兰",
	"lb_newTab": "新栏标",
	"ms_getdatafailure": "Error {0} -- {1}",
	"ms_clearTabConfigurationConfirm": "删除所有追加的小工具，可以吗？\n(删除掉的小工具进入回收站)",
	"lb_canBeAddContents": "可以追加的内容",
	"lb_dateFilterInfo": "输入{0}",
	"ms_customizeWidthByDrag": "用拖拉方式可以调整宽度",
	"lb_cancel": "取消",
	"lb_info": "信息",
	"lb_countryBR": "巴西",
	"lb_messageMore": "表示剩余的消息",
	"ms_autoReloadCancel": "在下载中，取消自动恢复。{0}",
	"lb_addContents": "内容的追加",
	"lb_change": "变更",
	"lb_resizeFontNormal": "把字符尺寸定为标准",
	"lb_authInfo": "认证信息",
	"lb_langRU": "俄罗斯语",
	"ms_propertyLoadonFailure": "属性读取失败。",
	"ms_noPermission": "没有读取权限。",
	"lb_urlList": "URL一览",
	"lb_belong": "类别",
	"ms_widgetonFailureAt": "{0}「{1}」上发生错误。{2} -- {3}",
	"lb_entry": "登录",
	"lb_name": "姓名",
	"lb_siteMap": "网页地图",
	"lb_previewError": "不能表示预览画面。",
	"lb_refreshMenu": "菜单更新",
	"ms_custmizeFailedReload": "自定义信息保存失败。再下载浏览器。",
	"ms_timeOut": "超时。",
	"ms_noURL": "没有链接的URL",
	"ms_clearConfigurationConfirm": "删除所有追加的标签和小工具，可以吗？\n(删除掉的小工具进入回收站)",
	"lb_changeColumn": "列数变更"
}
