var IS_R = {
	"ms_urlEncodeonExceptionAt": "在{0}上URL编码处理失败。 {1} : {2}({3})",
	"lb_searchConfigOn10408": "搜索设定文件的读取超时。",
	"lb_searchResultsOnNewWindow": "在新的窗口显示搜索结果",
	"lb_langNL": "荷兰语",
	"ms_userSearchonException": "用户搜索发生例外。",
	"lb_1monthAgo": "一个月前",
	"lb_countryUK": "英国",
	"ms_menuLoadOnUnSuccess": "菜单读取失败。 {0} -- {1}",
	"lb_countrySE": "瑞典",
	"lb_summaryAllView": "表示汇总/表示全文",
	"lb_newGroup": "新的组",
	"ms_menuadded": "追加了菜单[{0}]。",
	"lb_weekdaySun": "周日",
	"lb_dateDisplay": "表示详细日期/不表示",
	"lb_openSiteMap": "打开侧栏菜单",
	"ms_propertyNotFound": "找不到属性。",
	"ms_mergeCategoryError404": "{0} : 未找到要表示的信息。",
	"ms_atompubPostonFauilure": "「在i{0}」上发生错误。\n{1} -- {2}\n{3}",
	"lb_titleEdit": "标题编辑",
	"ms_menuNotFound2": "未找到菜单「{0}」。",
	"lb_nextPage": "下一页",
	"lb_pageNum": "页{0}",
	"ms_authServiceAccessFailed": "不能正常链接认证服务。请咨询系统管理员。",
	"ms_noInputComment": "请记入回复。",
	"lb_otherLayout": "画面及其它",
	"lb_sentMessageOfArticle": "传送关于该新闻的消息",
	"ms_customizeSavingonException": "自定义信息保存失败。 {0}",
	"ms_invalidURL": "不是有效的ＵＲＬ",
	"ms_notCoverage": "不是搜索对象。",
	"lb_gathering": "归纳",
	"lb_webSiteColon": "网页:",
	"lb_readingtimeout": "表示的消息读取时间超时。此功能暂时不能使用。",
	"lb_all": "所有",
	"lb_shortcutsKeyList": "快捷键一览",
	"ms_dragNoMerge": "一直压下Ctrl键，RSS阅读器之间不能进行归并。",
	"ms_gadgetFuncNotFound": "小工具「{0}上「{1}」这一函数不存在。",
	"lb_add": "追加",
	"lb_countryMX": "墨西哥",
	"ms_closeMySiteMap": "关闭网站地图",
	"lb_incomingMessage": "收到的消息",
	"ms_selectSearchSite": "请选择只是一个搜索网站。",
	"lb_messageOf": "{0}的消息",
	"lb_siteCategory": "网页类别",
	"lb_refresh": "更新",
	"ms_reportfailure1": "故障报告障害報告処理に失敗しました。 {0} -- {1} : {2}({3})",
	"ms_validateError": "验证检验失败。{0}",
	"ms_getdatafailed": "没有取得数据。",
	"lb_maximizeShortcutsitemAndSummary": "(项目选择时 &amp；汇总表示时)",
	"lb_previewScreen": "确认画面",
	"ms_invalidRssType": "是不能处理的RSS形式: {0}",
	"ms_trashContextExplanation": "右击鼠标可以[还原]/[删除]。",
	"ms_thisIsFixedTab": "这个标签是固定标签。不能自定义。",
	"ms_invalidDateFormat": "不正确日期格式。",
	"lb_countryUS": "美国",
	"lb_langPtBR": "葡萄牙语",
	"ms_mergeConfirm": "把「{1}」归并到「{0}」上吗？",
	"ms_searchEngineLoadon10408": "对搜索网页「{0}」的要求超时。",
	"ms_up_update_from_default_by_admin": "「{0}」小工具的用户设定「{1}」的值被管理员从初期值变为「{2}」。",
	"ms_confirmDeleteUser": "可以删除用户吗？",
	"lb_toTopPage": "首页",
	"lb_countryNZ": "新西兰",
	"lb_searchForm": "搜索表格",
	"lb_erroronWidgetMove": "在小工具「{0}」的移动处理中出现错误",
	"lb_fullDisplay": "全文表示",
	"lb_selectWallPaperImage": "请从以下选择壁纸设定画像。",
	"lb_familyName": "姓",
	"lb_default": "默认",
	"lb_invalidate": "设为无效",
	"lb_setupAll": "全体设定",
	"lb_doNotMerge": "不合并（返回）",
	"lb_noInfo": "没有可能表示的信息。",
	"ms_up_update_by_admin": "「{0}」小工具的用户设定「{1}」的值被管理员从「{2}」变为「{3}」。",
	"lb_dropAll": "一并向下拖放",
	"ms_commandonException": "命令的执行失败。 {0}",
	"lb_selectSearchSite": "选择检索网站",
	"ms_iCalNoPermission": "没有读取日历「{0}」的权限。",
	"ms_deletaTabFailed": "栏标「{0}」删除失败。",
	"lb_comment": "答复",
	"lb_displayAll": "全部表示",
	"lb_reset": "重置",
	"lb_date": "日期",
	"ms_requiredItem": "是必须项目",
	"lb_langES": "西班牙语",
	"lb_today": "今天",
	"lb_warn": "警告",
	"ms_inputTooLong": "输入的字符串过长。请限定在{0}文字以下。",
	"lb_search": "搜索",
	"lb_addTabLink": ">>追加栏标",
	"lb_searchConditionNotSet": "未设定搜索条件。",
	"ms_mergeCategoryError10550": "{0} : 不能解析信息。",
	"lb_minute": "分",
	"lb_debug": "调试",
	"ms_failedLoadIcons": "小工具图标读取失败。",
	"lb_langKO": "韩语",
	"ms_customizeSavingFailure1": "自定义信息保存失败。{0}",
	"lb_sendBroadcastMsg": "向所有用户发送通知",
	"ms_urlEncodingUnsuccess": "URL编码处理失败。 {0} : ({1})",
	"lb_freshdaysTerm": "新到图标的表示期限",
	"ms_targetGroupNotFound": "※没有可追加用户的组。请创建组。",
	"lb_accessStatsTitle": "访问统计 - {0}",
	"lb_noEntry": "没有登录",
	"lb_administrator": "管理员",
	"lb_readMore": "阅读更多",
	"lb_close": "关闭",
	"ms_gatheringWidgets": "归纳一下小工具。",
	"ms_tabNameTooLong": "标签名过长。",
	"lb_searchOption": "搜索选项",
	"lb_setting": "设定",
	"lb_changeColnumFailure": "列变更失败。column={0}, msg=[{1}]",
	"lb_doMerge": "合并",
	"lb_userSearchNoResult": "搜索结果为0件。",
	"lb_added": "追加完毕",
	"lb_getSystemMessageFailure": "新消息的收取失败。",
	"ms_widgetTitleEmpty": "请输入小工具标题。",
	"lb_initialize": "初始化",
	"ms_cacheDeleteFailure": "缓存删除失败。 {0} -- {1}",
	"lb_langIT": "意大利语",
	"lb_credentialList": "认证信息一览",
	"lb_displayRSS": "表示RSS",
	"lb_transmission": "送信",
	"lb_addOtherWidget": "追加其它小工具",
	"lb_recentSixMonth": "最近六个月",
	"lb_weekdayTue": "周二",
	"ms_previewMenuPath": "在菜单中设定。",
	"ms_loadTimeout": "读取超时。",
	"lb_descLink": "详细>>",
	"ms_showTabByClick": "点击时表示这个标签",
	"lb_lastmodified": "最后更新日期",
	"lb_keywordTooLong": "搜索文字列过长。",
	"ms_deleteTabConfirm": "「删除{0}」。可以吗？",
	"lb_showAllLatestItems": "表示新到信息",
	"ms_loadCancel": "正在下载中，取消下载。{0}",
	"lb_inspectionCount": "阅览次数",
	"lb_countryDE": "德国",
	"lb_noCreator": "无作者",
	"ms_sessionTimeoutReLogin": "Session中断。请再登录。",
	"ms_gtOneNum": "输入1以上的适当数字。",
	"lb_langJA": "日语",
	"lb_title": "标题",
	"lb_countryCA": "加拿大",
	"lb_3DaysAgo": "三天前",
	"lb_hour": "时间",
	"lb_addSchedule": "日程的新规追加",
	"ms_requiredItem2": "是必须项目",
	"lb_ranking": "热门搜索",
	"lb_countryAU": "澳大利亚",
	"lb_ref": "浏览",
	"ms_multiRssReaderDeleteSubcategory": "MultiRssReader「{0}」类别「{1}」被删除。",
	"ms_askToSystemManager": "请咨询系统管理员。",
	"ms_infoNotFoundAt": "未找到{0}「{1}」中表示的信息。",
	"ms_invalidRegexp": "不正确的正规表示。",
	"ms_inputTooLong2": "输入的字符串过长。用半角英文字母{0}文字可以输入。\n全角文字包含在内时全角文字算做约3个文字。",
	"ms_urlGetInfoException1": "获取信息失败。请确认输入的URL是否有错。{0} -- {1}",
	"ms_rankingDurationFailed": "排列次序「{0}」的期间不能取得。{1}",
	"lb_noDiplayItem": "没有表示的信息。",
	"lb_gadget": "小工具",
	"ms_changeToFixedTab": "标签'{0}'被变更成为固定标签。 所有的个性化领域的小工具被收集到了回收站。",
	"ms_showWidgetByClick": "点击表示这个小工具",
	"ms_closeGroupSelect": "关闭组选择",
	"lb_next": "下一步",
	"ms_searchEngineLoadonException": "搜索网页「{0}」上发生错误。{1}",
	"lb_countryIE": "爱尔兰",
	"ms_inputCredential": "请输入认证信息。",
	"ms_widgetonExceptionAt": "{0}「{1}」上发生错误。{2}",
	"lb_weekdayFri": "周五",
	"lb_langZH": "中国语",
	"lb_messageClose": "关闭消息",
	"lb_countryCH": "瑞士",
	"lb_checkNewArriedMessageFailure": "新到消息的检查失败。",
	"ms_menuNotFound": "未找到菜单。",
	"lb_system": "系统",
	"lb_span": "期间",
	"ms_needLoginForUseWidget": "使用该小工具需要登录。",
	"lb_generalSetting": "一般设定",
	"lb_obstacleReort": "没有出错的报告",
	"ms_getMessageListFailure": "消息一栏的获取失败。",
	"lb_closeAll": "全部关闭",
	"ms_iCalLoadFailed": "日历的读取失败。 {0} : {1} -- {2}",
	"lb_clearConfigurationDesc1": "把门户画面恢复到初始画面。",
	"lb_searchConfigOn404": "搜索设定文件的读取失败。\nError 404: location \"{0}\" is not found.\n 服务器设定有错。请咨询系统管理员。",
	"lb_refreshKey": "更新(R)",
	"ms_authFailure": "认证失败。请输入正确的用户名/密码。",
	"ms_classNotFounf": "看不到类{0。",
	"lb_outboundMessage": "送出的消息",
	"lb_addContentsExGadget": "http://www.infoscoop.org/gadgets/hello.xml",
	"ms_stopRefresh": "中止更新",
	"lb_postMessageToPublic": "提交公开消息",
	"lb_logout": "退出",
	"lb_mergeView": "一揽子表示",
	"lb_countryDK": "丹麦",
	"lb_makeEffective": "设为有效",
	"lb_sendMail": "邮件发送",
	"lb_creator": "作者",
	"ms_up_revert_by_admin": "「{0}」小工具的用户设定「{1}」的值被管理员从复原回初期值。",
	"lb_notGathering": "不归纳",
	"lb_rssViewSetting": "RSS表示设定",
	"lb_noNewInfo": "没有新到的信息。",
	"lb_i18n": "国际化",
	"lb_preview": "预览",
	"lb_notfound": "没有要表示的消息。",
	"lb_searchConfigException": "搜索设定文件的读取失败。搜索设定有误。请咨询系统管理员。\n{0}",
	"ms_commandonFailure": "命令的执行失败。 {0} -- {1}",
	"ms_userSearchComplete": "获得用户搜索结果。",
	"lb_dateCategory": "日期分类",
	"lb_summaryView": "表示汇总",
	"lb_noDisplayFrameBorder": "不显示小工具的框：",
	"ms_containerLoadon404": "Error 404: location \"{0} /widsrv \" is not found.",
	"lb_clearConfigurationButton": "自定义信息的初始化",
	"ms_infosccopInitializing": "infoScoop在初始化。",
	"lb_notConfirm": "今后不确认",
	"lb_newBox": "新BOX",
	"lb_any": "{0}",
	"ms_pleaseTurnbackAndSetAuthInfo": "为参照消息，请解除最大化并登录认证信息。",
	"ms_widgetBuildError": "小工具制作中发生错误。",
	"ms_updatePasswordError": "密码更新失败。",
	"lb_creatorFilterLabel": "从\"{0}\" 开始的作者",
	"lb_resetColumnWidth": "统一列的幅度",
	"ms_sessionTimeout": "因不明原因Session中断。请再登录。",
	"lb_lastAccessDate": "最后访问日期",
	"lb_proxy": "代理服务器",
	"ms_rankingNoInfo": "未能找到Ranking「{0}」上表示的信息。",
	"lb_maximizeSendMail": "{0} %0D%0A%0D%0A {1}",
	"ms_rankingonException": "排列次序「{0}」上发生错误。{1}",
	"ms_invalidValue2": "输入不正确的数值。请重新设定。",
	"lb_rankingUnit": "{0}位&nbsp;",
	"ms_urlEncodeonFailureAt": "在{0}上URL编码处理失败。 {1} -- {2} : {3}({4})",
	"lb_execute": "执行",
	"ms_invalidIconType": "在使用无效的表头图标。{0}[type={1}",
	"lb_openNewWindow": "打开新的窗户",
	"lb_group": "{0}组",
	"ms_rssSearchFailure": "RSS信息搜索失败。",
	"lb_creatorCategory": "作者分类",
	"lb_langDE": "德语",
	"lb_destination": "传送地址",
	"lb_resizeFontSmaller": "缩小字符尺寸",
	"lb_getCustomInfoonFailure2": "未能取得画面自定义信息。请稍后继续登录。",
	"ms_loadtimeoutAt": "在{0}「{1}」读取超时。",
	"lb_firstPage": "首页",
	"lb_yesterday": "昨天",
	"ms_menuLoadonFailure": "菜单读取失败。",
	"lb_langFR": "法语",
	"ms_duplicateGroupName": "同一名称的群已经存在。",
	"ms_mergeCategoryError": "{0} : 发生错误。",
	"lb_defaultPanel": "初始画面",
	"lb_langDA": "丹麦语",
	"lb_setupSchedule": "日程的设定",
	"ms_iframeForbiddenURL": "网站「{0}」由于管理员限制了门户内的表示，所以不能表示新的窗口。",
	"lb_itemCount": "文章数: {0}件",
	"lb_toOnlineManual": "换至在线手册",
	"ms_invalidFormat": "请指定正确的格式。",
	"lb_year": "年",
	"lb_information": "通知",
	"ms_iCalParseFailed": "日历解析失败。 {0} : {1}",
	"ms_urlEncodingonException": "URL编码处理失败。 {0} -- {1} : {2}({3})",
	"lb_reportFailure": "报告失败",
	"ms_forbiddenurlPage": "选择的网站由于管理员的限制不能在门户内表示。",
	"lb_setupUnfinished": "小工具在所有设定完成之前不能表示。",
	"ms_unsetting": "未设定。",
	"ms_RankingNoPermission": "没有排列次序「{0}」的读取权限。",
	"lb_administration": "管理",
	"lb_countryIN": "印度",
	"lb_rename": "名称变更",
	"ms_getResultFailureAt": "用{0}「{1}」取得搜索结果失败。",
	"lb_newArriedMessage": "收到新的消息。",
	"lb_widgetDesignSetting": "小工具的设计设定",
	"lb_tab": "标栏",
	"ms_atompubPostonException": "「在{0}」上发生错误。\n{1}\n{2}",
	"ms_selectProfile": "选择配置文件。",
	"ms_searchNotFound": "搜索结果为0件。",
	"lb_new": "New!!",
	"lb_sec": "秒",
	"lb_type": "类型",
	"lb_low": "低",
	"ms_invalidUsernameOrPassword": "用户名或密码错误。",
	"lb_topMenu": "顶部菜单",
	"ms_maximizeRefreshAfterTimeover": "在自动刷新超时被取消时，为了关闭最大化的小工具请开始刷新",
	"lb_resetToDefaultSettings": "返还到默认值",
	"ms_rssreaderUnreadable": "不能读取RssReader设定。",
	"lb_changeApply": "适用变更",
	"ms_forbiddenURL": "输入的URL网站由于管理员的限制而不能阅览。",
	"lb_bracketTrashEmptyAll": "[清空回收站]",
	"lb_prevPage": "上一页",
	"ms_changeTabFailed": "栏标切换失败。{0}",
	"ms_doubleEntryFailure": "{0}由于第二次执行失败，被废弃。",
	"lb_userSearch": "用户搜索",
	"lb_countryIT": "意大利",
	"ms_rankingTimeout": "排列次序「{0}」的取得超时。",
	"ms_logofftimeSavingfailure": "退出处理失败。{0}",
	"lb_addContentsExWebSite": "http://www.infoscoop.org/index.php/ja/",
	"ms_widgetBkgcolorError": "{0}「{1}」上发生错误。背景颜色不能设定。",
	"lb_messageOfGroup": "{0}组的消息",
	"lb_userNotAddedGroup": "该组中用户没有追加。",
	"lb_langEN": "英语",
	"lb_urlExample": "URL输入示例",
	"ms_sorry": "对不起...",
	"ms_gtZeroNum": "输入0以上的适当数字。",
	"lb_notitle": "没有标题",
	"ms_urlNoInput": "请输入URL。",
	"ms_urlTooLong": "URL 过长。URL的长度在半角拉丁数字2000字以下。如果含有\n全角文字时全角文字被数为约9个文字。",
	"ms_noPermissionAt": "没有{0}「{1}」的读取权限。",
	"ms_getRssInfoonException": "RSS信息获取失败。请确认输入的URL是否正确。{0} -- {1}",
	"lb_searchUser": "日历的搜索和表示",
	"lb_saveSettings": "保存设定",
	"ms_searchEngineLoadonFailure": "搜索网页「{0}」上发生错误。{1} -- {2}",
	"ms_getRssInfoonFailure": "RSS信息获取失败。请确认输入的URL是否正确。",
	"lb_searchCondition": "搜索条件",
	"ms_erroronSubWidgetMove": "サブカテゴリ「{0}」の移動処理でエラーが発生しました",
	"ms_noInputPassword": "没有输入用户密码。",
	"ms_menuLoadon10408": "菜单的读取超时",
	"ms_getInfoFailureAt": "用{0} 「{1}」取得详细信息失败。",
	"ms_clearConfigurationFailed": "自定义信息的初始化失败",
	"lb_high": "高",
	"lb_widget": "小工具",
	"lb_1weekAgo": "一周前",
	"lb_addContentsExRSS": "http://www.infoscoop.org/index.php/ja/news.feed",
	"lb_showHelp": "表示帮助",
	"lb_wallPaperSetting": "壁纸设定",
	"lb_addUser": "追加用户",
	"ms_getRssInfoonUnsccess": "RSS信息获取失败。请确认输入的URL是否正确。{0}",
	"lb_month": "月",
	"lb_openMySiteMap": "打开我的网站地图",
	"lb_maximizeShortcutsItemAndFull": "(项目选择时 &amp; 全文表示时)",
	"lb_endOfUserSearch": "用户搜索完毕",
	"lb_containerLoadonException": "未能构成画面: {0}",
	"lb_mySiteMap": "我的网站地图",
	"ms_errorSetAuthInfo": "输入的用户名/密码的认证失败。用户名D/密码未能更新。",
	"ms_lastlogoutSavingfailure": "上次退出时的客户自定义信息没有保存。",
	"ms_duplicateProfile": "有重复的配置文件",
	"ms_inputURL": "请输入URL。",
	"lb_closeAddContents": "关闭内容追加",
	"lb_addRssFeed": "追加RSS源",
	"ms_minimizeFailure": "{0}最小化失败: {1}",
	"ms_maximizeCloseRefresh": "为了关闭最大化的小工具请开始刷新",
	"lb_illegalToolbarItem": "不正确的工具栏窗标。不明的种类 [{0}]",
	"lb_editGroup": "组的编辑",
	"lb_error": "错误",
	"lb_sendMailTitle": "[{0}]{1}",
	"lb_containerLoginonException": "未能构成画面。自定义信息的数据可能出现不整合。请向系统管理员询问。",
	"ms_userIdEmpty": "请输入用户名。",
	"lb_countryES": "西班牙",
	"ms_tabsRefresh": "更新配置在所有标签上的小工具",
	"lb_langNO": "挪威语",
	"ms_iCalCreateFailed": "日历的生成失败。 {0}",
	"lb_countOneDay": "一天前",
	"ms_datecreatorChangeFailed": "{0}的日期/作者的表示/非表示设定的变更失败: {1}",
	"lb_delete": "删除",
	"ms_lineChangeFailure": "{0}的改行设定变更失败: {1}",
	"lb_turnbackMaximize": "还原",
	"lb_org": "部门",
	"lb_prev": "向前",
	"ms_confirmDeleteGroup": "删除组，可以吗？",
	"ms_sendMessageFailed": "消息送信失败。",
	"lb_noInfoOnMaximize": "最大化中没有可表示的信息。",
	"ms_widgeTitleTooLong": "小工具标题里超过指定的文字数。",
	"ms_inputTxtBox": "请在写字框中输入内容。",
	"ms_shortcutsNotice": "※快捷键不能使用时请试把日语输入转为无效。",
	"lb_trashBox": "回收站",
	"lb_recentOneWeek": "最近一周",
	"lb_authType": "认证类型",
	"ms_widgetDuplicateWarn": "同一小工具已经存在，不能追加。({0})",
	"ms_RankingCriticalerror": "出现错误。<br/>{0}<br/>该小工具现在不能使用。",
	"lb_mail": "邮件",
	"ms_onSheetReaderSSOonException": "OnSheet一键登录处理失败。{0}",
	"lb_deployAll": "全部展开",
	"lb_detailAndBlank": "详细&nbsp;&nbsp;",
	"lb_widgetTitle": "小工具标题",
	"ms_loginFailed": "登录失败。",
	"lb_latestMessage": "最新消息",
	"lb_selectWidgetHeaderImage": "请从下面选择小工具的头的背景使用的画像。",
	"ms_failedCheckCharLength": "输入文字列的长度检查失败。",
	"ms_invalidCharset": "不正确编码。",
	"ms_customizeDeleteonFailure": "自定义信息删除失败。 {0} -- {1}",
	"lb_noMessage": "没有消息。",
	"lb_countryNO": "挪威",
	"lb_saveFilterSetting": "[日期]以外的缩小项目作为RSS前导字符被保存。",
	"ms_getRssInfoTimeout": "RSS信息获取已超时",
	"ms_getdataerror404": "错误 404: 没有找到区域 {0}.",
	"ms_customizeDeleteonException": "自定义信息删除失败。 {0}",
	"lb_countryFR": "法国",
	"lb_select": "选择",
	"ms_toggleEditElementByClick": "点击切换至 {0}要素内容的编辑画面。",
	"lb_weekdaySat": "周六",
	"ms_widgetonExceptionNotAvailableAt": "{0}「{1}」上发生错误。<br/>{2}<br/>这一小工具现在不能使用。",
	"lb_openMenu": "打开菜单",
	"lb_saveLoginState": "保存登录状态",
	"ms_noRssInfo": "该网页没有RSS信息。",
	"lb_doubleAdd": "选择的小工具已经追加。",
	"ms_atomRegetonException": "Atom的再取得失败。\n{0}",
	"lb_messageConsole": "消息控制",
	"ms_selectValidProfile": "请选择有效地配置文件。",
	"ms_emptyAt": "{0}未输入。",
	"ms_mergeCategoryError10408": "{0} : 读取超时。",
	"lb_adminLink": "至管理画面",
	"ms_inputTitle": "请输入标题。",
	"lb_countryCN": "中国",
	"lb_getCustomInfoon404": "未能取得画面自定义信息。服务器设定有误。请向系统管理员询问。",
	"ms_invalidWidget": "该小工具现在不能使用。",
	"lb_category": "类别",
	"lb_deleteDate": "删除日",
	"lb_day": "日",
	"lb_forbiddenURL": "禁止URL",
	"ms_invalidOldPassword": "旧密码是错误的。",
	"lb_changePassword": "密码的变更",
	"lb_langFI": "芬兰语",
	"ms_oauthFailed": "认证处理失败。",
	"ms_getSearchResultFailure": "搜索结果的获取失败。",
	"ms_configNotFound": "{0}构成文件不存在。",
	"ms_searchEngineLoadon404": "未能找到搜索网页「{0}」上表示的信息。",
	"lb_edit": "编辑",
	"lb_loginTitle": "登录",
	"lb_closeSitemap": "关闭侧栏菜单",
	"lb_newpass": "新密码",
	"lb_toLogin": "换至登录画面",
	"lb_middle": "中",
	"lb_minimize": "最小化",
	"ms_trashLoadonFailure": "无法取得回收站信息。{0} -- {1}",
	"lb_mergeConfirmDialog": "小工具确认对话",
	"lb_groupList": "组一览",
	"lb_sentMessageTo": "向{0传送消息",
	"lb_noDate": "无日期",
	"lb_scheduleMonthFormat": "yyyy年 M月",
	"lb_weekdayThu": "周四",
	"ms_revertWidget": "追加到标签{0}」。鼠标点击后返回。",
	"lb_gadgetColon": "小工具:",
	"ms_cannotAddGadgetToThisTab": "不能对这个标签追加小工具。",
	"lb_rssColon": "RSS:",
	"lb_deleteUser": "删除用户",
	"lb_enableRoundCorner": "小工具的边角弄成圆的：",
	"ms_menuIconException": "菜单「{0}」的图标表示设定发生错误：{1}",
	"lb_countryJP": "日本",
	"ms_errorOnWindowResize": "ウィンドウリサイズ時の処理でエラーが発生しました: {0}",
	"lb_weekdayMon": "周一",
	"lb_addWebPage": "网页的追加",
	"lb_resizeFontLarger": "扩大字符尺寸",
	"ms_customizeSavingFailure2": "自定义信息保存失败。 {0} -- {1}",
	"lb_nationalHoliday": "节日",
	"ms_clearConfigurationForceReload": "由于自定义信息已被初始化，进行重载。",
	"ms_onSheetReaderSSOonFailure": "OnSheet一键登录处理失败。 {0} -- {1}",
	"lb_langSV": "瑞典语",
	"lb_browserNotSupported": "不支持现在使用的浏览器。",
	"ms_mergeCategoryError403": "{0} : 没有读取权限。",
	"lb_addGroup": "组追加",
	"ms_iCalLoadTimeout": "日历读取已超时。 {0}",
	"lb_changeNotApply": "不变更",
	"lb_showRssInSite": "表示网页内RSS：<br/>&nbsp;&nbsp;http://www.nikkeibp.co.jp/<br/>",
	"ms_noInputDestination": "输入传送地址。",
	"lb_pageTop": "首页",
	"lb_allUsersPublicMessage": "全用户的公开信息",
	"ms_menuLoadonException": "菜单读取失败。{0}",
	"lb_doReply": "回信",
	"lb_countryKR": "韩国",
	"lb_openAddContents": "打开内容追加",
	"ms_addCheckedUser": "※把选择的用户追加到［{0}］上",
	"msg_title": "消息控制台",
	"lb_closeLink": "关闭<<",
	"lb_initTab": "初始化标签的构成",
	"lb_reportFinished": "报告结束",
	"lb_weekdayWed": "周三",
	"lb_searchConfigOnFailure": "搜索设定文件的读取失败。{0} --  {1}",
	"ms_overMaxIntValue": "超过最大值。最大值为2147483647。",
	"ms_teleconSetupRequire": "使用这个小工具需要初期设定。请设定<br/>搜索关键词。",
	"lb_lastPage": "最后页",
	"ms_enrtyNotFound": "没有找到符合{0}的输入。",
	"ms_urlGetInfoException2": "获取信息失败。请确认输入的URL是否有错。{0}",
	"ms_customizeSaved": "保存了自定义信息。",
	"lb_login": "登录",
	"lb_countryFI": "芬兰",
	"ms_on10998": "infoScoop已在其它浏览器上启动。在此浏览器上的更新信息没有得到反映。",
	"lb_maximize": "最大化",
	"lb_oldPassword": "旧密码",
	"lb_postMessageAsPublic": "作为公开消息投稿",
	"lb_setAuth": "认证信息设定",
	"lb_subscribes": "购买阅读{0",
	"ms_menuMoveonError": "菜单「{0}」的移动处理出错",
	"lb_turnback": "还原",
	"lb_urlDirectInput": "使用示例<br/>直接输入URL：<br/>&nbsp;&nbsp;http://www.nikkeibp.co.jp/index.rdf<br/>",
	"ms_passwordResetConfirm": "设定的密码在以下的URL上认证失败，要设定吗？",
	"lb_nextPageLink": "下一页>>",
	"lb_getCustomInfoonFailure1": "未能取得画面自定义信息。: {0} -- {1}",
	"lb_bracketClose": "[关闭]",
	"lb_userID": "用户名",
	"lb_password": "密码",
	"lb_holiday": "假日",
	"ms_duplicateDeleteConfirm": "「{0}」已经表示在标栏「{1}」上。可以从\n「{2}」删除小工具吗？",
	"lb_relogin": "再登录",
	"ms_authServiceNotWork": "认证服务不能正常使用。",
	"ms_inputOverMaxValue": "超过限定最大数。请设定在{0}以下。",
	"ms_changePasswordFailed": "密码变更失败。",
	"ms_invalidValue": "不正确的数值。",
	"lb_searchResult": "搜索结果",
	"ms_urlEncodingFailed": "URL编码处理失败。 {0} : {1}({2})",
	"lb_reload": "再读",
	"lb_filterDescSettingLink": "详细的缩小设定 >>",
	"ms_gtZeroOrAuto": "请输入auto或大于0的数字。",
	"ms_passwordChanged": "密码已经变更。",
	"lb_countryRU": "俄罗斯",
	"ms_trashonException": "无法取得回收站信息。{0}",
	"lb_deploy": "展开",
	"ms_rssSearchTimeout": "RSS信息搜索超时。",
	"lb_widgetEditHelp": "帮助",
	"lb_eMail": "E-Mail",
	"lb_businessDate": "工作日",
	"ms_needsAuthentication": "为了把小工具最大化，请登录认证信息。",
	"lb_menu": "菜单",
	"lb_clearConfigurationDesc2": "如果自定义信息初始化的话，追加的标签和小工具将全部被删除。",
	"lb_widgetTitle_empty": "请输入小工具标题。",
	"lb_prevItem": "前面的项目",
	"lb_changePass": "密码变更",
	"lb_selectSubWidgetHeaderImage": "请从以下选择副小工具的头的背景色。",
	"messsage_invalidDefaultValue": "设定了无效的初期值 : {0} UserPref[@name={1}]",
	"lb_countryNL": "荷兰",
	"lb_newTab": "新栏标",
	"lb_countDown": "到「{0}」为止、剩余",
	"lb_recentOneMonth": "最近一个月",
	"lb_property": "属性",
	"ms_getdatafailure": "Error {0} -- {1}",
	"ms_clearTabConfigurationConfirm": "删除所有追加的小工具，可以吗？\n(删除掉的小工具进入回收站)",
	"lb_canBeAddContents": "可以追加的内容",
	"lb_dateFilterInfo": "输入{0}",
	"ms_customizeWidthByDrag": "用拖拉方式可以调整宽度",
	"lb_cancel": "取消",
	"lb_loading": "Loading...",
	"ms_rankingonFailure": "排列次序「{0}」上发生错误。{1} -- {2}",
	"lb_info": "信息",
	"ms_gadgetError": "小工具「{0}」中发生错误。",
	"lb_countryBR": "巴西",
	"ms_title_update_by_admin": "「{0}」小工具的标题被管理员变更为「{1}」。",
	"ms_refferenceAt": "从  可以参照。",
	"lb_messageMore": "表示剩余的消息",
	"ms_autoReloadCancel": "在下载中，取消自动恢复。{0}",
	"lb_addContents": "内容的追加",
	"lb_change": "变更",
	"ms_noPermission401": "请输入用户ID和密码。",
	"lb_resizeFontNormal": "把字符尺寸定为标准",
	"ms_sessionTimeoutByOtherLogin": "Session中断。<br/>有可能在别的浏览器上登录。<br/>请再登录。<br/>",
	"lb_authInfo": "认证信息",
	"lb_langRU": "俄罗斯语",
	"ms_propertyLoadonFailure": "属性读取失败。",
	"lb_nextItem": "下面的项目",
	"lb_editSummary": "编辑概要",
	"ms_noPermission": "没有读取权限。",
	"lb_urlList": "URL一览",
	"lb_editDesc": "编辑详细内容",
	"lb_belong": "类别",
	"ms_widgetonFailureAt": "{0}「{1}」上发生错误。{2} -- {3}",
	"lb_entry": "登录",
	"lb_name": "姓名",
	"lb_attention": "*",
	"lb_here": "这里",
	"lb_releaseMaximize": "还原（最大化解除）",
	"lb_siteMap": "网页地图",
	"lb_previewError": "不能表示预览画面。",
	"lb_refreshMenu": "菜单更新",
	"ms_reportfailure2": "故障报告处理失败。 {0}",
	"ms_custmizeFailedReload": "自定义信息保存失败。再下载浏览器。",
	"ms_timeAlert": "是「{0}」的时间。",
	"ms_timeOut": "超时。",
	"ms_noURL": "没有链接的URL",
	"ms_searchNotAvailable": "不能读取搜索设定。现在不能进行搜索。",
	"ms_clearConfigurationConfirm": "删除所有追加的标签和小工具，可以吗？\n(删除掉的小工具进入回收站)",
	"ms_atomRegetFailure": "Atom的再取得失败。\n{0} -- {1}",
	"lb_changeColumn": "列数变更"
}
