var ISA_R = {
	"alb_selectFragmentArea": "Select fragment area",
	"alb_matchingFromTop": "Matching is executed from top.",
	"ams_searchEngineNotFound": "Search engine is not found.",
	"ams_externalServiceDataNotDelete": "External service URL can not be deleted.",
	"ams_failedUpdateProperties": "Failed to update properties.",
	"alb_valueColon": "Value:",
	"alb_targetAutoSelect": "auto detect",
	"alb_proxyAuthSettings": "Proxy authentication settings",
	"ams_widgetNotFound": "Gadget is not found.",
	"alb_searchOptionDefaultSettings": "Search option default settings",
	"ams_failedCommitProxy": "Failed to commit proxy settings.",
	"ams_noMenuSelect": "No menu can be selected.",
	"alb_widgetWithRSS": "Gadget with RSS",
	"ams_errorWhileWidget": "Error occurred while creating Gadget.",
	"ams_changeUpdated": "Change is applied",
	"alb_multiUserEdit": "Following user is editting the selected menu.",
	"ams_failedDeleteCommandBar": "Failed to delete command bar items.:",
	"alb_serchSiteSetting": "Search site settings",
	"ams_confirmChangeLost": "The changes you made will be lost without saving. Are you sure?",
	"alb_editing": "Editting",
	"ams_failedLoadingMessage": "Failed to laod {0}.",
	"ams_deleteSetWidget": "The Gadget set is deleted.",
	"ams_confirmNoTop3": "Are you sure to not display [Toppage] button?",
	"alb_substitutionURL": "Substitution URL",
	"alb_delete": "Delete",
	"ams_failedDeleteLocale": "Failed to delete locale.",
	"ams_menuNotFound": "Menu is not found.",
	"ams_gadgetResourceUpdateFailed": "It failed in the preservation of the resource.",
	"alb_title": "Title",
	"alb_rssPattern": "RSS pattern",
	"ams_notSet": "Not set.",
	"alb_setToTitle": "Set to title information",
	"alb_portalframe": "Frame in portal",
	"alb_durationMinute": "Duration(minute)",
	"alb_displayLinkSettings": "Display link settings:",
	"alb_gadgetsList": "Gadgets List",
	"alb_userOperationLog": "User operation log",
	"alb_addLinkMessage": "Link for displaying on command bar can be added",
	"alb_gadgetResourceCreateDescrption": "A new resource is made for the directory.",
	"alb_linkUrl": "Link URL",
	"alb_layout": "Layout",
	"ams_selectFragmentArea": "Select fragment element by mouse pointer. Decide fragment element by right clicking menu..",
	"alb_externalServiceURL": "External service URL:",
	"ams_failedToUpdateFURL": "Failed to update forbidden URL..",
	"ams_confirmNoTop1": "Toppage is not displayed normally at displaying inline frame if this function is off.",
	"alb_gadgetResourcesZipDownload": "Archive Download",
	"alb_widgetSettings": "Gadget settings",
	"alb_oauthConsumerSecret": "Consumer secret",
	"alb_directoryTitle": "Directory Title",
	"alb_edit": "Edit",
	"alb_ajaxRequest": "Ajax requests",
	"alb_saveSettings": "Save settings",
	"alb_column": "Column",
	"ams_toppageSettingsNF": "Top page settings are not found.",
	"alb_numberOfItems": "Results",
	"ams_failedToloadPortalLayout": "Failed to load other layout settings.",
	"alb_originalHTTPHeader": "Original HTTP headers",
	"ams_localeAlreadyAdded": "The specified locale[{0}_{1}] is already added",
	"ams_failedLoadIcons": "Failed to load gadget icons.",
	"alb_oauthCertificate": "Certificate",
	"alb_executeImport": "Import",
	"ams_typeTitle": "Type title.",
	"alb_topmenu": "Topmenu",
	"alb_editByOtherUser": "Other user [{0}] is editting.",
	"ams_failedLoadingTreeMenuAdmins": "Failed to load treeMenu admins.",
	"ams_failedDeleteMenu": "Failed to delete menu.",
	"alb_cutSelectedEelement": "Cut selected element.",
	"alb_selectWidetOnTop": "The Gadget displayed on top page can be selected from menu.",
	"alb_newRegularExpression": "New regular expression",
	"alb_cacheSeetings": "Cache settings",
	"alb_keyWordSearchRanking": "Search Keyword Ranking",
	"alb_getTtitleInfromation": "Get title information",
	"ams_applyingChanges": "Applying changes...",
	"alb_systemSetup": "System settings",
	"ams_failedLoadingMenu": "Failed to load menu.",
	"ams_notFoundMessage": "{0} is not found.",
	"alb_oauthConsumerKey": "Consumer key",
	"ams_fragmentNotSelected": "Fragment element is not selected",
	"ams_widgetAlreadySelected": "The selected Gadget is already set.",
	"alb_forbiddenURL": "Forbidden URL",
	"alb_port": "Port",
	"alb_editSettings": "Customization",
	"ams_invalidOAuthSetting": "There is error in \"{1}\" of line {0}.",
	"alb_add": "Add",
	"alb_regularExpressionColon": "Regular expression:",
	"alb_selectPermissionLevel": "Select the permission level,then click Preview.",
	"alb_editByClick": "Edit by clicking",
	"alb_addLocale": "Add locale",
	"alb_linkDisplayOn": "Link display on",
	"ams_continueDelete": "Continue to delete?",
	"alb_save": "Save",
	"alb_host": "Host",
	"alb_addLink": "Add a link",
	"alb_deleteMenu": "Delete menu",
	"alb_addGadget": "Add a Gadget",
	"alb_settingMenuLink": "Menu link settings",
	"alb_setupAll": "Global settings",
	"alb_uploadGadget": "Upload Gadget",
	"ams_adminNotFound": "Administrator is not found.",
	"alb_noTitle": "No title",
	"alb_others": "Others",
	"ams_gadgetResourceUploadConfirm": "Are all present content annulled, and is it good?",
	"ams_failedLockOrder": "Failed to lock order.",
	"ams_gadgetResourceDeleteConfirm": "Resource [{0}] is deleted. Is it good?",
	"alb_holidaySettings": "Holiday settings",
	"alb_menuTree": "menu tree",
	"alb_advancedSettingsMessage": "Red labels are setting of behavior of the internal program or not supported in current version.",
	"alb_URLregularExpression": "URL(regular expression)",
	"alb_preview": "Preview",
	"alb_gadgetUrl": "Gadget URL",
	"alb_sertLinkCommandbar": "Set a link to display on command bar.",
	"ams_failedUpdatingMenu": "Failed to update menu.",
	"alb_adressPattern": "Address pattern",
	"alb_addMenuTree": "Add menu tree",
	"alb_closeAll": "Close all",
	"alb_order": "Order",
	"alb_titleLink": "Title link",
	"alb_sendNoCookie": "Not sending cookie",
	"ams_failedAddProxy": "Failed to add proxy settings.",
	"alb_newMenu": "New menu",
	"alb_singleton": "Singleton",
	"ams_failedToSaveTop": "Failed to save top page settings.",
	"alb_editMenu": "Edit menu",
	"alb_titleLinkColon": "Title link:",
	"alb_displayOrNot": "Display/Not display",
	"alb_properties": "Properties",
	"ams_failedDeleteEdittingMenuData": "Failed to delete editting menu data.",
	"ams_deleteGadgetConfirm": "Is the gadget deleted, and is it good?",
	"ams_failedGetTitleInfo": "Failed to get title infromation",
	"alb_method": "Method:",
	"alb_searchAdress": "Search adress",
	"alb_addTab": ">>Add a tab",
	"alb_previewTop": "Preview Top page",
	"alb_roleNameColon": "Role name:",
	"ams_duplicatedID": "Duplicated ID can not be registered.",
	"alb_oauthConsumerSettings": "OAuth consumer settings",
	"alb_oauthTwoLeggedConsumerSettings": "2-legged OAuth consumer settings",
	"alb_defaultProxy": "Default proxy",
	"alb_alertSettingsColon": "Alert settings:",
	"alb_user": "User",
	"alb_sendAllCookies": "Send all cookies",
	"ams_widgetList": "Built-in Gadget list",
	"ams_failedSavingValueEdit": "Failed to save value edittings.",
	"alb_none": "none",
	"alb_oauthContainerCertificate": "Container's Certificate",
	"alb_publicSettings": "Public settings",
	"ams_failedSaveSearchEngine": "Failed to save search engine.",
	"ams_notPreview": "Previrew can not be displayed.",
	"alb_bgcolor": "Back groung color",
	"alb_changeLockOrder": "Do menu tree addition/order change.",
	"alb_menuLinksAndWHS": "Link on menu/Gadget header settings",
	"ams_typeAdminSettings": "Type the value on line {0} of administrator settings.",
	"ams_failedToGetRole": "Failed to get role information.",
	"alb_settingOf": "Settings of {0}",
	"alb_changeApply": "Apply changes",
	"alb_userInformation": "User Infromation",
	"alb_restricted": "Restricted",
	"alb_select": "Select",
	"ams_invalidCharHeader2": "The characters that can be used for headers is",
	"alb_addHtmlMessage": "HTML for displaying on command bar can be added",
	"alb_backToList": "Back to the list",
	"ams_iCalSavedUTF8": "iCalender file needed to be save in UTF-8 encoding.",
	"ams_failedToGetOAuthSettings": "Failed to get OAuth settings.",
	"alb_gadgetResourceDeleteDescription": "The resource is deleted.",
	"alb_searchResultsOnNewWindow": "Display search results on new window.",
	"alb_oauthSignatureAlgorithm": "Signature algorithm",
	"alb_forbiddenURLsettings": "Forbidden URL settings",
	"alb_insiteSearchSettings": "In-site search settings",
	"ams_failedLoadingSearchEngine": "Failed to load search engine.",
	"ams_failedUpdateOtherPotal": "Failed to update other portal settings.",
	"alb_selectSiteExecutingByDefault": "Default",
	"ams_failedCommitWidget": "Failed to commit a Gadget.",
	"alb_selectedXPath": "XPath currently selected:",
	"alb_informNewMenu": "Setting for displaying message on the user screen to inform that a new menu is added.",
	"alb_lockAndEdit": "Lock and edit",
	"ams_failedUpdateLocale": "Failed to update locale.",
	"alb_noBorder": "Not displaying border：",
	"alb_Ticker": "Ticker",
	"ams_sameSubjectForRE": "Same subject is used for same regular expression.",
	"ams_typeRoleSetting": "Type the value on line {0} of role settings.",
	"alb_updateGadget": "Update Gadget",
	"alb_gadgetResourceUploadFileEncodeDescription": "* When the text file is edited, encode must be UTF-8.",
	"alb_subject": "Subject",
	"alb_selectUpdateProperties": "Select update properties",
	"ams_noPossibleSettings": "No settings items can be editted.",
	"alb_noDefault": "Do not use default",
	"ams_failedLockMenu": "Failed to lock menu.",
	"ams_deleteThisTab": "Deleting this tab",
	"ams_failedReplaceProxySettings": "Failed to replace proxy settings.",
	"alb_replaceAll": "Replace all",
	"alb_entry": "Submit",
	"alb_selectLayout": "Select layout",
	"alb_rankingSetting": "Ranking settings",
	"alb_deleteGadget": "Delete Gadget",
	"alb_menuItemlist": "Menu items list",
	"alb_reloadWithourSaving": "Reload without saving",
	"alb_descOfUseCacheForSearchResults": "Do cash and reuse search results at the time of the number acquisition. When using cash, there is a advantage for performance, but there is the case that the indication of search results collapses.",
	"ams_selectWidget": "Select a Gadget.",
	"alb_paramNameOfUserId": "Parameter/Header name of UserID:",
	"ams_gadgetResourceUploadFailed": "Upload failed.",
	"alb_proxy": "Proxy",
	"alb_gadgetResourcesZipDescription": "- Arrange the gadget configuration file in most significant in the ZIP archive, and the name [Names of ZIP archive except extension. xml] It is necessary to set.",
	"alb_trashBox": "Trash Bin",
	"alb_titleUrl": "Title URL",
	"alb_advancedSettings": "Display all properties",
	"alb_selectTemplate": "Select a template below by clicking.",
	"alb_encoding": "Encoding",
	"alb_addMenu": "Add menu",
	"alb_deleting": "Deleting",
	"alb_porpety": "Property",
	"alb_noLinkMenu": "No links on menu",
	"alb_description": "Description",
	"alb_search": "Search",
	"alb_sideMenu": "Sidemenu",
	"alb_disableCustomizedArea": "Do not use the personalized area.",
	"alb_noLinkMenuColon": "No links on menu:",
	"alb_height": "Height",
	"alb_backToDefault": "Back to default settings",
	"alb_pulic": "Publish:",
	"alb_fixedArea": "Fixed area settings",
	"alb_customizedArea": "Personalized area: Initial display of gadget setting",
	"alb_notDisplaySetting": "Menu is set as not to be displayed",
	"alb_referToTopURL": "Refer to the same URL as top menu",
	"alb_logout": "Logout",
	"alb_gadgetResources": "Gadget Resources",
	"alb_cancel": "Cancel",
	"alb_oauthServiceName": "Service name",
	"alb_changeOrder": "Change order",
	"alb_resourceUrl": "Resource URL",
	"ams_changeUpdatedPeriod": "Change is applied.",
	"ams_failedReplaceSearchEngine": "Failed to replace search engine.",
	"alb_useCacheForSearchResults": "Use cache:",
	"alb_language": "Language",
	"alb_newContents": "New contents",
	"alb_setWidgetCompulsory": "Set Gadget compulsory",
	"ams_gadgetResourceUploading": "The resource is uploading.",
	"ams_failedloadingGadgetFile": "Failed to load gadget setting file.",
	"alb_toTopPage": "TopPage",
	"ams_failedToGetFURL": "Failed to get forbidden URL.",
	"alb_clearConfigurationButton": "Initialization of customized information",
	"alb_editUserSettings": "User settings(initial value)",
	"ams_fixedAreaTemplateNR": "Failed to load templates of fixed area.",
	"alb_gadgetResourcesUpdateDescription": "All present content is annulled, and the ZIP archive of a new gadget configuration file or the gadget is up-loaded.",
	"alb_authentication": "Authentication",
	"alb_clearConfigurationDesc": "Customized information is initialized.",
	"alb_selectHeader": "Select headers to send",
	"alb_deployAll": "Open all",
	"alb_checkAllItems": "Check all items",
	"alb_messageSettings": "Message settings",
	"alb_editHTMLandOk": "Edit HTML and click [OK] button.",
	"ams_failedReplaceMenu": "Failed to replace menu.",
	"alb_newWindow": "New window",
	"alb_credentialList": "Credential List",
	"ams_confirmNoTop2": "Do not off this function except alternate function is described on the header.",
	"alb_noneSetting": "None settings",
	"alb_searchForm": "Search form",
	"alb_roleName2": "Role name",
	"alb_gadgetResourcesZipDownloadDescription": "It downloads it bringing all files together with the ZIP archive.",
	"ams_failedLoadingProperty": "Failed to load property.",
	"alb_menu": "Menu",
	"alb_externalServiceAuthType": "External service authentication type:",
	"alb_oauthPrivateKey": "Private key",
	"ams_failedLoadingStaticInfo": "Failed to load statistics information.",
	"ams_typeRankingSettings": "Type ranking settings.",
	"ams_staticInfoNotFound": "Statistics Information is not found.",
	"alb_roleName": "Role name",
	"alb_defaultSettings": "Default settings",
	"alb_selectWidgetFromList": "Select a Gadget to set from the list below.",
	"ams_roleDeleted": "Role is deleted",
	"ams_failedLoadingProxy": "Failed to load proxy settings.",
	"ams_FailedGetInfo": "Failed to get information. Confirm that typed URL is not valid.",
	"ams_failedDeleteGadget": "Failed to delete Gadget.",
	"alb_adminSettings": "Administrator settings",
	"alb_selectUploadingGadget": "Select a file to upload and click [Upload] button.",
	"ams_fixedAreaTemplateNF": "Templates of fixed area is not found.",
	"alb_ranking": "Ranking",
	"alb_adminList": "Administrators list",
	"ams_blankRegularExpression": "Regular expression is blank.",
	"ams_proxyNotFound": "Proxy setting is not found.",
	"alb_authServerColon": "Authentication server",
	"alb_gadgetResourceEditDescription": "The resource is edited.",
	"alb_tabName": "Tab name",
	"ams_notMoveMenuTree": "Can not move to menu tree",
	"alb_statisticsInformation": "Statistics Information",
	"alb_regularExpression": "Regular expression",
	"alb_loginSessionSetting": "Login/Session",
	"alb_selectColumnNumber": "Select column nuber,then click OK button",
	"alb_userCustomization": "User customization",
	"alb_message": "Message",
	"ams_failedCommitMenu": "Failed to commit menu.",
	"alb_columnNumber": "Column number:",
	"alb_home": "Home",
	"alb_widgetTypeColon": "Type of Gadget：",
	"ams_oauthCertificateNote": "Note that the default public key is sample. It must be changed.<br>Everyone can get a public key of infoScoop from the following url.<br><a href=\"{0}\">{1}</a><br>Please tell this url to developers who develop web service supported oauth and signed request.",
	"ams_invalidCharHeader": "Header name includes invalid characters.",
	"ams_setAlreadyExist": "The settings set are already existed.",
	"alb_newTab": "New tab",
	"alb_apply": "Apply",
	"alb_public": "Publish",
	"ams_pleaseDefaultSelectedSearchSite": "Please select at least one default search site.",
	"alb_paramNameOfPasswd": "Parameter/Header name of Password:",
	"alb_subjectColon": "Subject:",
	"alb_gadgetUrlSpecified": "Gadget(Specifying URL)",
	"alb_defaultPanel": "Default Layout",
	"ams_i18nNotFound": "I18N message is not found.",
	"alb_editRole": "Edit role",
	"ams_failedLoadingHolidays": "Failed to load holiday settings.",
	"alb_totalUsersNumber": "Total number of users",
	"alb_propertiesList": "Properties List",
	"alb_domain": "Domain",
	"alb_accessedUsersToday": "Number of users accessed today",
	"alb_editWidgetSettings": "Gadget settings",
	"ams_oauthPrivateKeyNote": "Note that the default private key is sample. It must be changed.<br>Ensure that you won't publish this private key to anyone.",
	"ams_gadgetResourceUpdating": "The resource has been updated.",
	"alb_backTop": "Back",
	"alb_editColumnAndWidth": "Edit column number/width",
	"ams_typeRSSfeedingURL": "Type RSS feeding URL.",
	"ams_gadgetResourceDeleteFailed": "It failed in the deletion of the resource.",
	"alb_forcedUpdatePrefsMessage": "As for checked properties, a value is reflected to the gadget which is already dropped on a user screen.",
	"alb_import": "Import",
	"ams_confirmDeleting": "Are you sure to delete?",
	"alb_admin": "Administrators",
	"alb_link": "Link",
	"alb_newTitle": "New site",
	"alb_changingOrder": "Changing order",
	"ams_failedAnalysisGadgetFile": "Failed to analyse gadget setting file.",
	"ams_regularExpressionAlreadyReg": "This regular expression is already registered.",
	"ams_changeCanNotApplied": "Change can not be applied because some items are causing error.",
	"alb_displayingName": "Displaying name",
	"alb_name": "Name",
	"alb_multiUserEdit2": "Editting data of this user is lost if editting is continued.",
	"alb_newRole": "New role",
	"alb_widget": "Gadget",
	"alb_alertSettings": "Alert settings",
	"alb_activeUserNumber": "Number of active users",
	"ams_failedCommitSearchForm": "Failed to commit search form.",
	"alb_intranet": "Intranet",
	"alb_sendAllHeader": "Send all headers",
	"alb_proxyAndURLSettings": "Proxy/Substitution URL settings",
	"alb_enable": "Enable",
	"ams_gadgetResourceDeleting": "The resource has been deleted.",
	"ams_failedToloadTS": "Failed to load Top page settings.",
	"ams_requiredItem": "is required.",
	"alb_permission": "permission",
	"alb_type": "Type",
	"ams_failedLoadingAdmin": "Failed to load administrator.",
	"alb_setWidgetDefailt": "Common settings of each Gadget and default values are set here.",
	"alb_otherLayout": "Other Layout",
	"alb_ok": "OK",
	"alb_i18n": "I18N",
	"ams_treeMenuAdminsNotFound": "treeMenu admins is not found.",
	"alb_displayMessage": "Displaying message",
	"alb_close": "Close",
	"alb_roleSettings": "Role settings",
	"ams_failedUpdateAdmin": "Failed to update administrator.",
	"alb_headerTransmission": "Header transmission",
	"alb_widgetHeaderSettings": "Gadget Header Settings",
	"alb_notSet": "Can not be set",
	"ams_failedToUpdateOAuthSettings": "Failed to save OAuth settings.",
	"alb_uncheckAllItems": "Uncheck all items",
	"alb_adminLink": "To Management Page",
	"alb_userName": "User name",
	"ams_typeWebURL": "Type URL of web site and select the area to be displayed.",
	"ams_propertyNotFound": "Property is not found.",
	"alb_country": "Country",
	"alb_value": "Value",
	"alb_fillDifference": "Fill differences",
	"alb_changeFont": "Change font size",
	"alb_destroyOldSettings": "The old settings are lost if a template is selected.",
	"alb_noAlert": "No alert",
	"ams_failedAddSearchEngine": "Failed to add search engine.",
	"alb_export": "Export",
	"alb_clearConfigurationChooseUser": "Please specify the user whose customized information is to be initialized.",
	"alb_rssFeedUrl": "RSS feeding URL",
	"ams_menusIllegalEdit": "The following trees were not able to be updated. There is a possibility that it was edited by another user. Please do all lock release, and edit it after a while again.",
	"alb_bundle": "Bundle",
	"alb_addHtml": "Add a HTML",
	"ams_failedAddMenu": "Failed to add menu.",
	"ams_oauthConsumerKeyNote": "Note that the default consumer key is sample. It must be changed.<br>Please tell this consumer key to developers who develop web service supported oauth and signed request.",
	"ams_menusTimeout": "Failed in the acquisition of temporary data. There is a possibility that time-out occurred during the process or that it was edited by other users. Please release all locks, and edit it after a while again.",
	"ams_deleteLocale": "Are you sure to delete locale [{0}_{1}]?",
	"alb_newLink": "New link",
	"ams_deleteGadget": "Gadget is deleted.",
	"alb_enalbeMultiDrop": "Enable multiple drops",
	"alb_newRssPattern": "New RSS pattern",
	"ams_failedLoadingWidget": "Failed to load Gadget.",
	"alb_gadgetResourcesCreateDescription": "The ZIP archive of a new gadget configuration file or the gadget is up-loaded.",
	"ams_invalidCharHeader3": "It is ASCII characters when except the {0} and blank tab character.",
	"ams_gadgetResourceListFailed": "It failed in the acquisition of the gadget resource list.",
	"alb_resultDisplaying": "Result is displayed here",
	"alb_gadgetResourceCreate": "Addition of resource",
	"alb_specifySendingCookies": "Specify sending cookies",
	"ams_gadgetResourceFetchFailed": "It failed in the acquisition of the resource.",
	"ams_otherLocaleMessageDelete": "Message of same ID in Other locale is all deleted if default locale is deleted.",
	"ams_confirmForceUpdateUserPrefs": "Force update changes to gadget dropped on personalized area. \nBy a case, This process take dozens of seconds or several minutes.",
	"alb_noHeader": "Not displaying header：",
	"alb_editHTML": "Edit HTML",
	"alb_role": "Role",
	"alb_contentURL": "URL of content",
	"alb_allLockRelease": "All lock release",
	"alb_password": "Password",
	"alb_refresh": "Refresh",
	"ams_deleteEdittingMenuData": "Editting menu data is deleted.",
	"alb_titleColon": "Title:",
	"ams_typeValidURL": "Type valid URL..",
	"alb_autoRefresh": "Auto refresh",
	"alb_selectWidgetToSet": "Select a Gadget to change settings from Gadget list on the left side.",
	"ams_failedSaveProxy": "Failed to save proxy settings.",
	"ams_failedDeleteEdittingData": "Failed to delete editting data.",
	"alb_upload": "Upload",
	"property_desc_keywordEntry": "Search keyword ranking data is saved or not",
	"property_desc_gadgetProxyURL": "URL of Gadget proxy",
	"property_desc_activeUserCountPeriod": "Duration of counting number of active users(day) Set -1 for unlimited duration",
	"property_desc_menuAutoRefresh": "Use auto reload menu function or not",
	"property_desc_messagePriority": "Detail level of mesasge(1,2,3,4)",
	"property_desc_rssPageSize": "Divided RSS receiving count",
	"property_desc_maxColumnNum": "Maximum number of columns in a tab",
	"property_desc_searchEngineURL": "External search engine configuration file URL",
	"property_desc_widgetRefreshInterval": "Auto refresh interval of each gadget(second)",
	"property_desc_accessLogEntry": "Save access log or not",
	"property_desc_ajaxRequestTimeout": "Maximum wait time for AJAX request(mili seconds)",
	"property_desc_rssMaxCount": "Maximum number of RSS displayed",
	"property_desc_loginCredentialAuthType": "Credential authentication type if the login information used on normal login page is applied on authentication Gadget(basic or ntlm or postCredential)",
	"property_desc_maxTabs": "Maximum number of tabs adding to portal",
	"property_desc_freshDays": "Term of displaying new arrival(Sun shaped) icon",
	"property_desc_subWidgetRefreshInterval": "Auto refresh interval of RSS in multi RSS gadget(mili minute)",
	"property_desc_displaySideMenu": "Display settings of sidemenu(display, not display or same settings as topmenu)",
	"property_desc_displayTopMenu": "Display settings of topmenu(display or not display)",
	"property_desc_menuLockTimeout": "Lock time-out time of manager menu (minute)",
	"property_desc_staticContentURL": "URI of static content",
	"property_desc_defaultTheme": "The design applied when a user logged in for the first time",
	"property_desc_sideMenuTabs": "Displaying items of tab menu(The available character string is \"sidemenu\" or \"addContent\" or \"mySiteMap\")",
	"property_desc_loginStateKeepPeriod": "Preservation period in state of login(day). The function is invalidated by 0 or less.",
	"property_desc_ajaxRequestRetryCount": "Number of retry if AJAX request is timed out",
	"property_desc_refreshInterval": "Auto refresh interval(minute)",
	"property_desc_commandQueueWait": "Customized information transmission interval(second)",
	"property_desc_fixedPortalHeader": "Fix the header, and show the scroll bar only in the tab.",
	"property_desc_logCommandQueueWait": "User operation log transmission interval(second)",
	"property_desc_displayInlineHost": "URL displayed in inline frame(eg. hostname:80,hostname,hostname:8080)",
	"property_desc_logStoragePeriod": "Storage period of log and access log. Set -1 for unlimited duration",
	"property_desc_appsServiceURL": "URL of service for Google Apps",
	"property_enum_debug":"Debug",
	"property_enum_display":"Display",
	"property_enum_error":"Error",
	"property_enum_info":"Info",
	"property_enum_notDisplay":"Non-display",
	"property_enum_warn":"Warn",
	"property_enum_referenceTopMenu":"The same settings as topmenu",
	"property_regex_typeCorrectFormat":"Type in the correct format",
	"property_regex_typeInt":"Type a integer value",
	"property_regex_typeLessThanTen":"Type a positive integer of 1 to 10",
	"property_regex_typePositiveInt":"Type a positive integer value",
	"property_regex_typeValidURL":"Type a valid URL."
}
