package org.infoscoop.dao.model;

// Generated 2010/03/29 15:54:59 by Hibernate Tools 3.3.0.GA

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * IsLogs generated by hbm2java
 */
@Entity
@Table(name = "is_logs")
public class Log implements java.io.Serializable {

	private Integer id;
	private String uid;
	private int type;
	private String url;
	private String urlKey;
	private String rssurl;
	private String rssurlKey;
	private String date;

	public Log() {
	}

	public Log(String uid, int type, String url, String urlKey,
			String rssurl, String rssurlKey, String date) {
		this.uid = uid;
		this.type = type;
		this.url = url;
		this.urlKey = urlKey;
		this.rssurl = rssurl;
		this.rssurlKey = rssurlKey;
		this.date = date;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "UID", nullable = false, length = 150)
	public String getUid() {
		return this.uid;
	}

	public void setUid(String uid) {
		this.uid = uid;
	}

	@Column(name = "type", nullable = false)
	public int getType() {
		return this.type;
	}

	public void setType(int type) {
		this.type = type;
	}

	@Column(name = "url", nullable = false, length = 1024)
	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	@Column(name = "url_key", nullable = false, length = 256)
	public String getUrlKey() {
		return this.urlKey;
	}

	public void setUrlKey(String urlKey) {
		this.urlKey = urlKey;
	}

	@Column(name = "rssurl", nullable = false, length = 1024)
	public String getRssurl() {
		return this.rssurl;
	}

	public void setRssurl(String rssurl) {
		this.rssurl = rssurl;
	}

	@Column(name = "rssurl_key", nullable = false, length = 256)
	public String getRssurlKey() {
		return this.rssurlKey;
	}

	public void setRssurlKey(String rssurlKey) {
		this.rssurlKey = rssurlKey;
	}

	@Column(name = "DATE", nullable = false, length = 24)
	public String getDate() {
		return this.date;
	}

	public void setDate(String date) {
		this.date = date;
	}

}
