package org.infoscoop.dao.model;

// Generated 2010/03/29 15:54:59 by Hibernate Tools 3.3.0.GA

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;
import javax.persistence.UniqueConstraint;

import org.infoscoop.util.XmlUtil;
import org.w3c.dom.Document;
import org.w3c.dom.Element;
import org.xml.sax.SAXException;

/**
 * IsMenusTemp generated by hbm2java
 */
@Entity
@Table(name = "is_menus_temp", uniqueConstraints = @UniqueConstraint(columnNames = {
		"type", "siteTopId" }))
public class MenuTemp implements java.io.Serializable {

	private Integer id;
	private String type;
	private String siteTopId;
	private String data;
	private String workingUid;
	private Date lastmodified;

	public MenuTemp() {
	}

	public MenuTemp(String type, String siteTopId, String data,
			Date lastmodified) {
		this.type = type;
		this.siteTopId = siteTopId;
		this.data = data;
		this.lastmodified = lastmodified;
	}

	public MenuTemp(String type, String siteTopId, String data,
			String workingUid, Date lastmodified) {
		this.type = type;
		this.siteTopId = siteTopId;
		this.data = data;
		this.workingUid = workingUid;
		this.lastmodified = lastmodified;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "type", nullable = false, length = 150)
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	@Column(name = "siteTopId", nullable = false, length = 150)
	public String getSiteTopId() {
		return this.siteTopId;
	}

	public void setSiteTopId(String siteTopId) {
		this.siteTopId = siteTopId;
	}

	@Column(name = "data", nullable = false, length = 65535)
	public String getData() {
		return this.data;
	}

	public void setData(String data) {
		this.data = data;
	}

	@Column(name = "workingUid", length = 150)
	public String getWorkingUid() {
		return this.workingUid;
	}

	public void setWorkingUid(String workingUid) {
		this.workingUid = workingUid;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "lastmodified", nullable = false, length = 19)
	public Date getLastmodified() {
		return this.lastmodified;
	}

	public void setLastmodified(Date lastmodified) {
		this.lastmodified = lastmodified;
	}


	@Transient
	public Element getElement() throws SAXException {
		Document doc = (Document) XmlUtil.string2Dom(getData());
		return doc.getDocumentElement();
	}

	public void setElement(Element conf) {
		setData(XmlUtil.dom2String(conf));
	}
}
