package org.infoscoop.dao.model;

// Generated 2010/03/29 15:54:59 by Hibernate Tools 3.3.0.GA

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

import org.infoscoop.util.HtmlUtil;

/**
 * IsMessages generated by hbm2java
 */
@Entity
@Table(name = "is_messages")
public class Message implements java.io.Serializable {
	public static final String MESSAGE_PUBLIC = "MSGPUBLIC";
	public static final String MESSAGE_FROM = "MSGFROM";
	public static final String MESSAGE_TO = "MSGTO";
	public static final String MESSAGE_BROADCAST = "MSGBC";
	public static final String FYI_PUBLIC = "FYIPUBLIC";
	public static final String FYI_FROM = "FYIFROM";
	public static final String FYI_TO = "FYITO";
	public static final String SYSTEM = "SYS";

	private Integer id;
	private String from;
	private String displayFrom;
	private String to;
	private String toJson;
	private String body;
	private Date postedTime;
	private String type;
	private String option;

	public Message() {
	}

	public Message(String from, Date postedTime, String type) {
		this.from = from;
		this.postedTime = postedTime;
		this.type = type;
	}

	public Message(String from, String displayFrom, String to,
			String toJson, String body, Date postedTime, String type,
			String option) {
		this.from = from;
		this.displayFrom = displayFrom;
		this.to = to;
		this.toJson = toJson;
		this.body = body;
		this.postedTime = postedTime;
		this.type = type;
		this.option = option;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "FROM", nullable = false, length = 150)
	public String getFrom() {
		return this.from;
	}

	public void setFrom(String from) {
		this.from = from;
	}

	@Column(name = "displayFrom", length = 150)
	public String getDisplayFrom() {
		return this.displayFrom;
	}

	public void setDisplayFrom(String displayFrom) {
		this.displayFrom = displayFrom;
	}

	@Column(name = "TO", length = 150)
	public String getTo() {
		return this.to;
	}

	public void setTo(String to) {
		this.to = to;
	}

	@Column(name = "toJSON", length = 65535)
	public String getToJson() {
		return this.toJson;
	}

	public void setToJson(String toJson) {
		this.toJson = toJson;
	}

	@Column(name = "body", length = 2048)
	public String getBody() {
		return this.body;
	}

	public void setBody(String body) {
		this.body = body;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "posted_time", nullable = false, length = 19)
	public Date getPostedTime() {
		return this.postedTime;
	}

	public void setPostedTime(Date postedTime) {
		this.postedTime = postedTime;
	}

	@Column(name = "type", nullable = false, length = 10)
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	@Column(name = "OPTION", length = 65535)
	public String getOption() {
		return this.option;
	}

	public void setOption(String option) {
		this.option = option;
	}


	@Transient
	public String getHtmlBody() {
		String body = getBody();
		body = HtmlUtil.resolveHtmlEntities(body);
		body = body.replaceAll(
				"(http:\\/\\/[-_.!~*'()a-zA-Z0-9;/?:@&=+$,%#]+)",
				"<a href='$1' target='_blank'>$1</a>");
		body = body.replaceAll("\n", "<br>");
		return body;
	}
}
