package org.infoscoop.dao.model;

// Generated 2010/03/29 15:54:59 by Hibernate Tools 3.3.0.GA

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * IsPortallayouts generated by hbm2java
 */
@Entity
@Table(name = "is_portallayouts", uniqueConstraints = @UniqueConstraint(columnNames = "name"))
public class Portallayout implements java.io.Serializable {

	private Integer id;
	private String name;
	private String layout;

	public Portallayout() {
	}

	public Portallayout(String name, String layout) {
		this.name = name;
		this.layout = layout;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "name", unique = true, nullable = false, length = 50)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "layout", nullable = false, length = 65535)
	public String getLayout() {
		return this.layout;
	}

	public void setLayout(String layout) {
		this.layout = layout;
	}

}
