package org.infoscoop.dao.model;

// Generated 2010/03/29 15:54:59 by Hibernate Tools 3.3.0.GA

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Transient;

import org.infoscoop.util.XmlUtil;
import org.w3c.dom.Document;
import org.w3c.dom.Element;
import org.xml.sax.SAXException;

/**
 * IsProxyconfs generated by hbm2java
 */
@Entity
@Table(name = "is_proxyconfs")
public class Proxyconf implements java.io.Serializable {

	private ProxyconfId id;

	public Proxyconf() {
	}

	public Proxyconf(ProxyconfId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides( {
			@AttributeOverride(name = "temp", column = @Column(name = "temp", nullable = false)),
			@AttributeOverride(name = "data", column = @Column(name = "data", nullable = false, length = 65535)),
			@AttributeOverride(name = "lastmodified", column = @Column(name = "lastmodified", nullable = false, length = 19)) })
	public ProxyconfId getId() {
		return this.id;
	}

	public void setId(ProxyconfId id) {
		this.id = id;
	}


	@Transient
	public Element getElement() throws SAXException {
		Document doc = (Document) XmlUtil.string2Dom(getId().getData());
		return doc.getDocumentElement();
	}

	public void setElement(Element conf) {
		getId().setData(XmlUtil.dom2String(conf));
	}
}
