package org.infoscoop.dao.model;

// Generated 2010/03/29 15:54:59 by Hibernate Tools 3.3.0.GA

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * IsRsscaches generated by hbm2java
 */
@Entity
@Table(name = "is_rsscaches", uniqueConstraints = @UniqueConstraint(columnNames = {
		"UID", "url_key", "pageNum" }))
public class Rsscache implements java.io.Serializable {

	private Integer id;
	private String uid;
	private String urlKey;
	private int pageNum;
	private byte[] rss;

	public Rsscache() {
	}

	public Rsscache(String uid, String urlKey, int pageNum) {
		this.uid = uid;
		this.urlKey = urlKey;
		this.pageNum = pageNum;
	}

	public Rsscache(String uid, String urlKey, int pageNum, byte[] rss) {
		this.uid = uid;
		this.urlKey = urlKey;
		this.pageNum = pageNum;
		this.rss = rss;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "UID", nullable = false, length = 150)
	public String getUid() {
		return this.uid;
	}

	public void setUid(String uid) {
		this.uid = uid;
	}

	@Column(name = "url_key", nullable = false, length = 128)
	public String getUrlKey() {
		return this.urlKey;
	}

	public void setUrlKey(String urlKey) {
		this.urlKey = urlKey;
	}

	@Column(name = "pageNum", nullable = false)
	public int getPageNum() {
		return this.pageNum;
	}

	public void setPageNum(int pageNum) {
		this.pageNum = pageNum;
	}

	@Column(name = "rss")
	public byte[] getRss() {
		return this.rss;
	}

	public void setRss(byte[] rss) {
		this.rss = rss;
	}

}
