package org.infoscoop.dao.model;

// Generated 2010/03/29 15:54:59 by Hibernate Tools 3.3.0.GA

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Transient;

import org.infoscoop.util.XmlUtil;
import org.w3c.dom.Document;
import org.xml.sax.SAXException;

/**
 * IsSearchengines generated by hbm2java
 */
@Entity
@Table(name = "is_searchengines")
public class Searchengine implements java.io.Serializable {

	private SearchengineId id;

	public Searchengine() {
	}

	public Searchengine(SearchengineId id) {
		this.id = id;
	}
	
	public Searchengine(Integer temp, String data){
		this.id = new SearchengineId();
		this.id.setTemp(temp);
		this.id.setData(data);
	}

	@EmbeddedId
	@AttributeOverrides( {
			@AttributeOverride(name = "temp", column = @Column(name = "temp", nullable = false)),
			@AttributeOverride(name = "data", column = @Column(name = "data", nullable = false, length = 65535)) })
	public SearchengineId getId() {
		return this.id;
	}

	public void setId(SearchengineId id) {
		this.id = id;
	}

	
	@Transient
	public String getData(){
		return getId().getData();
	}
	
	public void setData(String data){
		getId().setData(data);
	}
	
	@Transient
	public Document getDocument() throws SAXException {
		Document doc = (Document) XmlUtil.string2Dom(getData());
		return doc;
	}

	public void setDocument(Document doc) {
		setData(XmlUtil.dom2String(doc));
	}

}
