package org.infoscoop.dao.model;

// Generated 2010/03/29 15:54:59 by Hibernate Tools 3.3.0.GA

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * IsSearchenginesId generated by hbm2java
 */
@Embeddable
public class SearchengineId implements java.io.Serializable {

	private int temp;
	private String data;

	public SearchengineId() {
	}

	public SearchengineId(int temp, String data) {
		this.temp = temp;
		this.data = data;
	}

	@Column(name = "temp", nullable = false)
	public int getTemp() {
		return this.temp;
	}

	public void setTemp(int temp) {
		this.temp = temp;
	}

	@Column(name = "data", nullable = false, length = 65535)
	public String getData() {
		return this.data;
	}

	public void setData(String data) {
		this.data = data;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof SearchengineId))
			return false;
		SearchengineId castOther = (SearchengineId) other;

		return (this.getTemp() == castOther.getTemp())
				&& ((this.getData() == castOther.getData()) || (this.getData() != null
						&& castOther.getData() != null && this.getData()
						.equals(castOther.getData())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getTemp();
		result = 37 * result
				+ (getData() == null ? 0 : this.getData().hashCode());
		return result;
	}

}
