package org.infoscoop.dao.model;

// Generated 2010/03/29 15:54:59 by Hibernate Tools 3.3.0.GA

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * IsSessions generated by hbm2java
 */
@Entity
@Table(name = "is_sessions", uniqueConstraints = @UniqueConstraint(columnNames = "UID"))
public class Session implements java.io.Serializable {

	private Integer id;
	private String uid;
	private String sessionId;
	private Date logindatetime;

	public Session() {
	}

	public Session(String uid, String sessionId, Date logindatetime) {
		this.uid = uid;
		this.sessionId = sessionId;
		this.logindatetime = logindatetime;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "UID", unique = true, nullable = false, length = 150)
	public String getUid() {
		return this.uid;
	}

	public void setUid(String uid) {
		this.uid = uid;
	}

	@Column(name = "sessionId", nullable = false, length = 256)
	public String getSessionId() {
		return this.sessionId;
	}

	public void setSessionId(String sessionId) {
		this.sessionId = sessionId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "LOGINDATETIME", nullable = false, length = 19)
	public Date getLogindatetime() {
		return this.logindatetime;
	}

	public void setLogindatetime(Date logindatetime) {
		this.logindatetime = logindatetime;
	}

}
