package org.infoscoop.dao.model;

// Generated 2010/03/29 15:54:59 by Hibernate Tools 3.3.0.GA

import static javax.persistence.GenerationType.IDENTITY;

import java.util.ArrayList;
import java.util.Collection;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Transient;

/**
 * IsSystemmessages generated by hbm2java
 */
@Entity
@Table(name = "is_systemmessages")
public class SystemMessage implements java.io.Serializable {

	private Integer id;
	private String to;
	private String body;
	private String resourceId;
	private String replaceValues;
	private Integer isRead;

	public SystemMessage() {
	}

	public SystemMessage(String to) {
		this.to = to;
	}

	public SystemMessage(String to, String body, String resourceId,
			String replaceValues, Integer isRead) {
		this.to = to;
		this.body = body;
		this.resourceId = resourceId;
		this.replaceValues = replaceValues;
		this.isRead = isRead;
	}
	
	public SystemMessage(String to, String body, String replaceValues) {
		this(to, body, null, replaceValues, null);
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "TO", nullable = false, length = 150)
	public String getTo() {
		return this.to;
	}

	public void setTo(String to) {
		this.to = to;
	}

	@Column(name = "body", length = 2048)
	public String getBody() {
		return this.body;
	}

	public void setBody(String body) {
		this.body = body;
	}

	@Column(name = "resourceId", length = 512)
	public String getResourceId() {
		return this.resourceId;
	}

	public void setResourceId(String resourceId) {
		this.resourceId = resourceId;
	}

	@Column(name = "replaceValues", length = 2048)
	public String getReplaceValues() {
		return this.replaceValues;
	}

	public void setReplaceValues(String replaceValues) {
		this.replaceValues = replaceValues;
	}

	@Column(name = "isRead")
	public Integer getIsRead() {
		return this.isRead;
	}

	public void setIsRead(Integer isRead) {
		this.isRead = isRead;
	}


	@Transient
	public Collection<String> getReplaceValueCollection() {
		String[] values = getReplaceValues().split(",");
		Collection<String> msgs = new ArrayList<String>();
		for(int i = 0; i < values.length; i++){
			msgs.add(values[i].trim());
		}
		return msgs;
	}
}
