package org.infoscoop.dao.model;

// Generated 2010/03/29 15:54:59 by Hibernate Tools 3.3.0.GA

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * IsUserprefsId generated by hbm2java
 */
@Embeddable
public class UserprefId implements java.io.Serializable {

	private int fkWidgetId;
	private String name;
	private String value;
	private String longValue;

	public UserprefId() {
	}

	public UserprefId(int fkWidgetId, String name) {
		this.fkWidgetId = fkWidgetId;
		this.name = name;
	}

	public UserprefId(int fkWidgetId, String name, String value,
			String longValue) {
		this.fkWidgetId = fkWidgetId;
		this.name = name;
		this.value = value;
		this.longValue = longValue;
	}

	@Column(name = "fk_widget_id", nullable = false)
	public int getWidgetId() {
		return this.fkWidgetId;
	}

	public void setWidgetId(int fkWidgetId) {
		this.fkWidgetId = fkWidgetId;
	}

	@Column(name = "name", nullable = false)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "value", length = 4000)
	public String getValue() {
		return this.value;
	}

	public void setValue(String value) {
		this.value = value;
	}

	@Column(name = "long_value", length = 65535)
	public String getLongValue() {
		return this.longValue;
	}

	public void setLongValue(String longValue) {
		this.longValue = longValue;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof UserprefId))
			return false;
		UserprefId castOther = (UserprefId) other;

		return (this.getWidgetId() == castOther.getWidgetId())
				&& ((this.getName() == castOther.getName()) || (this.getName() != null
						&& castOther.getName() != null && this.getName()
						.equals(castOther.getName())))
				&& ((this.getValue() == castOther.getValue()) || (this
						.getValue() != null
						&& castOther.getValue() != null && this.getValue()
						.equals(castOther.getValue())))
				&& ((this.getLongValue() == castOther.getLongValue()) || (this
						.getLongValue() != null
						&& castOther.getLongValue() != null && this
						.getLongValue().equals(castOther.getLongValue())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getWidgetId();
		result = 37 * result
				+ (getName() == null ? 0 : this.getName().hashCode());
		result = 37 * result
				+ (getValue() == null ? 0 : this.getValue().hashCode());
		result = 37 * result
				+ (getLongValue() == null ? 0 : this.getLongValue().hashCode());
		return result;
	}

}
